### ISSUE TITLE
Implementation and performance difference between XDP_REDIRECT with bpf_redirect() and bpf_redirect_map()

### ISSUE THREAD

**Issue by simonhf** [xdp-project/xdp-tutorial#104]
I'm working through the tutorial and read here [1]:

> Besides the ability to transmit packets back from the same interface, there is an option to forward packets to egress ports of other interfaces (if the corresponding driver supports this feature). This can be done using the bpf_redirect or bpf_redirect_map helpers. These helpers will return the XDP_REDIRECT value and this is what should the program return. The bpf_redirect helper actually shouldn’t be used in production as it is slow and can’t be configured from user space.

I also came across this old post [2] which -- presuming xdp_redirect_map is old terminology for bpf_redirect_map() -- also suggests that using bpf_redirect() for XDP_REDIRECT is about half as slow as other XDP return values, or XDP_REDIRECT with bpf_redirect_map().

Questions:
- It's suggested that bpf_redirect() is not okay for production use. Is bpf_redirect_map() okay for production use?
- Are the performance figures in [2] from July 2017 still in the right ball park in Feb. 2020?
- Reading up on bpf_redirect_map() here [3] it's not clear how the packet reaches the other interface. Is the packet copied in memory, and how to find out more about the internal implementation?

[1] https://github.com/xdp-project/xdp-tutorial/tree/master/packet03-redirecting#redirecting-packets-to-other-interfaces
[2] https://lwn.net/Articles/728146/
[3] http://man7.org/linux/man-pages/man7/bpf-helpers.7.html

**Comment by tohojo** [comment]
Simon Hardy-Francis <notifications@github.com> writes:

> I'm working through the tutorial and read here [1]:
>
>> Besides the ability to transmit packets back from the same interface,
>> there is an option to forward packets to egress ports of other
>> interfaces (if the corresponding driver supports this feature). This
>> can be done using the bpf_redirect or bpf_redirect_map helpers. These
>> helpers will return the XDP_REDIRECT value and this is what should
>> the program return. The bpf_redirect helper actually shouldn’t be
>> used in production as it is slow and can’t be configured from user
>> space.
>
> I also came across this old post [2] which -- presuming
> xdp_redirect_map is old terminology for bpf_redirect_map() -- also
> suggests that using bpf_redirect() for XDP_REDIRECT is about half as
> slow as other XDP return values, or XDP_REDIRECT with
> bpf_redirect_map().

Actually we fixed the performance difference in Linux 5.6:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1d233886dd904edbf239eeffe435c3308ae97625

> Questions:
> - It's suggested that bpf_redirect() is not okay for production use.
>   Is bpf_redirect_map() okay for production use?

Well, whether something is 'ready for production use' kinda depends on
the use case, I'd say. Given the above patch, the main difference
between bpf_redirect() and bpf_redirect_map() is that the latter will
return an error immediately to the program if the supplied map index is
not populated, whereas bpf_redirect() can result in silent drops if
supplied with an invalid ifindex. Also, redirect_map() supports other
types of redirect, and of course you can change the redirect targets by
updating the map which you can't do with the non-map-based version.

> - Are the performance figures in [2] from July 2017 still in the right
> ball park in Feb. 2020?

See above.

> - Reading up on bpf_redirect_map() here [3] it's not clear how the
> packet reaches the other interface. Is the packet copied in memory,
> and how to find out more about the internal implementation?

The packet is not copied; the buffer will be passed directly to the
egress interface, and there's a return mechanism to the originating
driver. The requirement to implement this is the reason why not all
drivers that support XDP have support for XDP_REDIRECT. The redirect
mechanism will also perform bulking to increase performance: all packets
in each NAPI polling period will be put into a bulking queue on the
egress interface and released at once.

For the implementation, see the kernel code. The map itself is in
kernel/bpf/devmap.c and the code implementing the redirect is in
net/core/filter.c (grep for xdp_redirect and xdp_do_redirect).

**Comment by tohojo** [comment]
Closing this - please reopen if the comments above did not resolve your problem.
