### ISSUE TITLE
advanced03-AF_XDP make error:undefined reference to symbol 'gzopen64@@ZLIB_1.2.3.3'

### ISSUE THREAD

**Issue by Ruijuan-Cao** [xdp-project/xdp-tutorial#112]
Hi guys,
I'm studying the AF_XDP and learning about 'advanced03-AF_XDP' prog.
I encountered a problem while compiling and trying to make in my machine (linux kernel 5.6, x86_64 architecture),  a ld error like this, I wanna know why. Thanks a lot.
```
make[1]: Leaving directory '/root/xdp-tutorial/common'
cc -Wall -I/root/libbpf/src//build/usr/include/ -g -I../headers/ -L/root/libbpf/src/ -o af_xdp_user ../common//common_params.o ../common//common_user_bpf_xdp.o \
 af_xdp_user.c -l:libbpf.a -lelf  -lpthread
/usr/bin/ld: /root/libbpf/src//libbpf.a(libbpf.o): undefined reference to symbol 'gzopen64@@ZLIB_1.2.3.3'
/usr/bin/ld: /usr/lib64/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [../common//common.mk:107: af_xdp_user] Error 1
```
Thanks,
Alex

**Comment by tohojo** [comment]
You've managed to install a too-new version of libbpf. See https://github.com/xdp-project/xdp-tutorial/issues/93#issuecomment-575558020

**Comment by Ruijuan-Cao** [comment]
Oh yes!!! Thank you very much😊 It works very well following what you said. Love❤️

**Comment by tohojo** [comment]
Great! You're welcome :)
