### ISSUE TITLE
advanced03-AF_XDP: reply with a new udp packet

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#113]
https://github.com/xdp-project/xdp-tutorial/blob/master/advanced03-AF_XDP/af_xdp_user.c#L287

In this example，receive a icmp request and reply with a icmp echo.

Would you please make another demo, that receive a udp packet, and then reply a new udp packet assembled in process_packet function.

The new udp packet is completely assembled from layer 2, 3, 4. Not make a little change like the icmp echo demo.

I can parse a udp packet and assemble a udp packet, but can not send it out successfully.

@chaudron

**Comment by chaudron** [comment]
Can you share your code, as it should be rather straight forward... What if you keep the L2/L3 header, and only modify the type to UDP?

**Comment by glennWang** [comment]
@chaudron 

Please forgive the coarseness of my code. 

All demo code is in https://github.com/glennWang/xdp-playground.

`./af_xdp_user -d veth-adv03 -F --progsec --filename af_xdp_kern.o`

You can use client to send udp packet under veth0 ns.

The problem line:
https://github.com/glennWang/xdp-playground/blob/master/advanced03-AF_XDP/af_xdp_user.c#L803

**Comment by chaudron** [comment]
`			    xsk_ring_prod__tx_desc(&xsk->tx, tx_idx)->addr = (uint64_t)(ether_frame); // &ether_frame (uint64_t)
			    xsk_ring_prod__tx_desc(&xsk->tx, tx_idx)->len = frame_length;
			    xsk_ring_prod__submit(&xsk->tx, 1);
			    xsk->outstanding_tx++;`

Your descriptor is some local memory, `ether_frame`, it should be umem, so if you do not want to re-use the previous buffer (addr) you should allocate one with xsk_alloc_umem_frame().

**Comment by glennWang** [comment]
Thanks very much for your reminder .

 Later, I'll have a try again.

**Comment by glennWang** [comment]
Under your guidance, I have implemented UDP response by re-use the previous buffer (addr).

As the following:
https://github.com/glennWang/xdp-playground/blob/master/advanced03-AF_XDP/af_xdp_user.c#L564

This line initialize umem frame allocation:
https://github.com/xdp-project/xdp-tutorial/blob/master/advanced03-AF_XDP/af_xdp_user.c#L203

Hower, what the following line mean?
https://github.com/xdp-project/xdp-tutorial/blob/master/advanced03-AF_XDP/af_xdp_user.c#L153

**Comment by waqas-hafique** [comment]
@glenn-wang I tried you example and it works fine on localhost however when I try between two Linux machine I get following error
```
Unknown eth_type = 0x0000
```
How can I use your example between two linux machines?
