### ISSUE TITLE
Question: Is there anything like this for other BPF program types?

### ISSUE THREAD

**Issue by rtkaratekid** [xdp-project/xdp-tutorial#114]
Hi, I think this tutorial is fantastic. I've been fiddling with libbpf for a couple months now and this has been **extremely** helpful with learning more about XDP programs as well as using libbpf itself.

Being new to system programming and the Linux kernel, is there anything like this for other BPF program types or maybe just more cohesive documentation about libbpf as a whole? It's been a frustrating experience to have a "pretty good" grasp of how programs should be written, but then having a nightmare of a time compiling. In particular, using bpf_load.h has been so frustrating that I've considered just writing all my own loading code. Almost makes be want to go back to just using BCC, but I just really like fewer dependencies and standalone builds like what CO-RE is aiming for.

I'd be willing to work on a tutorial similar to this to help people not have the same frustrations as myself with libbpf in the future-- if some more experience people are willing to pick up my technical slack I can make sure it's very clear and helpful?

Edit to say: perhaps I should've sent this to the mailing list instead?

**Comment by tohojo** [comment]
rtkaratekid <notifications@github.com> writes:

> Hi, I think this tutorial is fantastic. I've been fiddling with libbpf
> for a couple months now and this has been **extremely** helpful with
> learning more about XDP programs as well as using libbpf itself.

Thank you! Glad you're finding it useful :)

> Being new to system programming and the Linux kernel, is there
> anything like this for other BPF program types or maybe just more
> cohesive documentation about libbpf as a whole? It's been a
> frustrating experience to have a "pretty good" grasp of how programs
> should be written, but then having a nightmare of a time compiling. In
> particular, using bpf_load.h has been so frustrating that I've
> considered just writing all my own loading code. Almost makes be want
> to go back to just using BCC, but I just really like fewer
> dependencies and standalone builds like what CO-RE is aiming for.

No, I'm not aware of any similar efforts for other uses of BPF, sadly.

> I'd be willing to work on a tutorial similar to this to help people
> not have the same frustrations as myself with libbpf in the future--
> if some more experience people are willing to pick up my technical
> slack I can make sure it's very clear and helpful?

While we could probably add a few lessons to this tutorial for related
BPF things, we really do want to keep the focus on XDP. So it's probably
better to do a separate one for other aspects of BPF. I'd suggest
emailing the BPF list, or opening an issue on the libbpf repo and ask if
anyone is interested?

**Comment by rtkaratekid** [comment]
>
> While we could probably add a few lessons to this tutorial for related
> BPF things, we really do want to keep the focus on XDP. So it's probably
> better to do a separate one for other aspects of BPF. I'd suggest
> emailing the BPF list, or opening an issue on the libbpf repo and ask if
> anyone is interested?


Perfectly understandable that you'd want to keep this in XDP. It (from my
outside perspective) seems like a whole world inside BPF on its own.
I think perhaps I will open an issue on the libbpf repo and see if anyone
is interested. I think there's more interest in using libbpf (instead of
BCC) than maybe some people realize, but it's not exactly easy to track
down how to do much more than some of the basics. On the mailing list just
yesterday I learned that bpf_load.h/c is deprecated, and, by consequence,
most things in samples/bpf/ are as well. I think this reason alone is a
good point for why tutorials like yours are helpful and should be
maintained if we want people using the technology.
