### ISSUE TITLE
Conceptual Question

### ISSUE THREAD

**Issue by yarochewsky** [xdp-project/xdp-tutorial#118]
Hi, I’m having trouble understanding docker networking with xdp, and thought someone here could help clarify something. 

I write an xdp program to just print the source and dest ips of packets coming in. Spin up a container and attach the program to the vethxxxx interface associated with the container. I the ping 1.1.1.1 from the container and look at the tracing pipe on the host. What I see surprises me: I only see packets with dst 1.1.1.1. Doesn’t xdp only support ingress? Why am I not seeing src: 1.1.1.1? Tcpdump on the same veth from the host shows both the request and reply for ICMP.

**Comment by tohojo** [comment]
Daniel Fonseca Yarochewsky <notifications@github.com> writes:

> Hi, I’m having trouble understanding docker networking with xdp, and
> thought someone here could help clarify something.
>
> I write an xdp program to just print the source and dest ips of
> packets coming in. Spin up a container and attach the program to the
> vethxxxx interface associated with the container. I the ping 1.1.1.1
> from the container and look at the tracing pipe on the host. What I
> see surprises me: I only see packets with dst 1.1.1.1. Doesn’t xdp
> only support ingress? Why am I not seeing src: 1.1.1.1? Tcpdump on the
> same veth from the host shows both the request and reply for ICMP.

Think of the veth interface on the host as being connected to the
container by a virtual wire. So packets coming *from* the container is
going *into* the veth device on the host. This is also the case for the
test environment we use in the tutorial, so you can refer to this
diagram, just substitue 'host' for 'root namespace' and 'container' for
'testenv namespace':
https://github.com/xdp-project/xdp-tutorial/tree/master/testenv#understanding-the-network-topology

**Comment by yarochewsky** [comment]
Thanks! So, in effect if I wanted to see the ingress from the container's point of view I'd have to attach the xdp program inside the container by hoping into it and attaching to eth0, right?

**Comment by yarochewsky** [comment]
Or since it's a matter of perspective interpret dst as src and src as dst

**Comment by tohojo** [comment]
Daniel Fonseca Yarochewsky <notifications@github.com> writes:

> Thanks! So, in effect if I wanted to see the ingress from the
> container's point of view I'd have to attach the xdp program inside
> the container by hoping into it and attaching to eth0, right?

Yup. Or attach to the physical interface on the host and filter the
traffic to only what's destined for the container (if you don't have any
container-to-container traffic, that is). Or use the TC hook on egress
on the host interface.

There's also work in progress to implement an egress hook for XDP as
well, but until that lands those are your options.

**Comment by yarochewsky** [comment]
Awesome, thanks a lot!

**Comment by tohojo** [comment]
Daniel Fonseca Yarochewsky <notifications@github.com> writes:

> Or since it's a matter of perspective interpret dst as src and src as
> dst if attaching to vethXXX

But you'll only see traffic in one direction...

**Comment by yarochewsky** [comment]
yeah, because XDP is ingress only, right? But eventually if it were to support egress as well

**Comment by tohojo** [comment]
Daniel Fonseca Yarochewsky <notifications@github.com> writes:

> Awesome, thanks a lot!

You're welcome :)

**Comment by tohojo** [comment]
Daniel Fonseca Yarochewsky <notifications@github.com> writes:

> yeah, because XDP is ingress only, right? But eventually if it were to
> support egress as well

Ah, yes, once there's an egress hook you could obviously do that :)
