### ISSUE TITLE
basic03 percpu stats counter is incorrect

### ISSUE THREAD

**Issue by lrouter** [xdp-project/xdp-tutorial#121]
I have compiled and run basic 03 and 04. They both contains per cpu stats map. But the test result shows that it could not fetch correct packet counter.
My test environment is :
host1 eth1 send packets ---> host 2 xdp eth1.
I could capture these high rates packets with tcpdump,  but when using xdp_stats the counter is wrong.

**Comment by tohojo** [comment]
lrouter <notifications@github.com> writes:

> I have compiled and run basic 03 and 04. They both contains per cpu stats map. But the test result shows that it could not fetch correct packet counter.
> My test environment is :
> host1 eth1 send packets ---> host 2 xdp eth1.
> I could capture these high rates packets with tcpdump,  but when using xdp_stats the counter is wrong.

A bit more detail would be good. What do you mean the counter is
'wrong'?

**Comment by lrouter** [comment]
I attach the prog to dev eth1, not the veth port created by testenv.sh. When I am ping host2 eth1 from host1 eth1, the rate counter is increasing, not show the rate at pps and bps. For example, the counter is from 1 pps to 100 pps.
After I reattach the prog veth, the counter is correct now. The eth1 is intel 82599 nic.

**Comment by tohojo** [comment]
lrouter <notifications@github.com> writes:

> I attach the prog to dev eth1, not the veth port created by
> testenv.sh. When I am ping host2 eth1 from host1 eth1, the rate
> counter is increasing, not show the rate at pps and bps. For example,
> the counter is from 1 pps to 100 pps.

Could you please try pasting the exact command you're running, and the
output? Both for the working and non-working cases...

**Comment by lrouter** [comment]
sorry for the confusions. I tried again following the tutotial step by step. The counter is correct.
