### ISSUE TITLE
advanced03-AF_XDP: reply with tcp syn ack packet leading to tcp spurious retransmission

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#122]
When advanced03-AF_XDP receive a syn packet, then it reply with a tcp syn+ack packet.
This operation leads to tcp spurious retransmission.

Why ?

The reply packet is  modified based on the received syn package.
The main codes are as follows:
```
				if(tcphdr->syn == 1){
				    tcphdr->th_win = htons(0);
				    tcphdr->ack_seq = htonl(ntohl(tcphdr->seq) + 1);
				    tcphdr->seq = htonl(1);
				    tcphdr->ack = 1;

				    iphdr->check = 0;
 
				    iphdr->check = ip_csum((unsigned short int *)iphdr, (int)sizeof(struct iphdr));

				    tcphdr->check = 0;

				    uint8_t tmp_mac[ETH_ALEN];
			            struct in_addr tmp_ip;
				    u_int16_t tmp_port = 0;

                                //  mac switch
			        memcpy(tmp_mac, eth->h_dest, ETH_ALEN);
			        memcpy(eth->h_dest, eth->h_source, ETH_ALEN);
			        memcpy(eth->h_source, tmp_mac, ETH_ALEN);

			    	//  IP switch
			        memcpy(&tmp_ip, &iphdr->saddr, sizeof(tmp_ip));
			        memcpy(&iphdr->saddr, &iphdr->daddr, sizeof(tmp_ip));
			        memcpy(&iphdr->daddr, &tmp_ip, sizeof(tmp_ip));

                                //  port switch
			        memcpy(&tmp_port, &tcphdr->source, sizeof(tmp_port));
			        memcpy(&tcphdr->source, &tcphdr->dest, sizeof(tmp_port));
			        memcpy(&tcphdr->dest, &tmp_port, sizeof(tmp_port));
				} 
```

Wireshark display:
10.11.1.2 is a simple tcp socket client.

<img width="1266" alt="图片" src="https://user-images.githubusercontent.com/7918942/80924939-b77dd080-8dbe-11ea-9809-d1fadbe1f165.png">

**Comment by chaudron** [comment]
Something is still wrong with your reply packet as the other side is not accepting it. Probably the TCP checksum as you are not recalculating it.

Also, why are you using memcpy for ip and port?

**Comment by glennWang** [comment]
> Something is still wrong with your reply packet as the other side is not accepting it. Probably the TCP checksum as you are not recalculating it.
> 
> Also, why are you using memcpy for ip and port?

I want to implement syn proxy based on af_xdp.

I have tested af_xdp to reply to udp client by using UDP packet that has no recalculating checksum. It has no problem.

And if I do not use memcpy for ip and port, is there other good method ?

**Comment by chaudron** [comment]
UDP might use checksum as 0, which is not supported by TCP, guess you should check the packet in wireshark and see what the TCP checksum says.

**Comment by glennWang** [comment]
Is there any af_xdp config that can offloads computing tcp header checksum to NIC ?

**Comment by glennWang** [comment]
> UDP might use checksum as 0, which is not supported by TCP, guess you should check the packet in wireshark and see what the TCP checksum says.

The problem is such in the case as you said.

Is there any af_xdp config that can offloads computing tcp header checksum to NIC ?

**Comment by chaudron** [comment]
> Is there any af_xdp config that can offloads computing tcp header checksum to NIC ?

No, currently there is no HW offload support in combination with XDP. It's being worked on upstream.

**Comment by glennWang** [comment]
https://gist.github.com/glennWang/6875018d41191e2558848012c38ec9ab

Find several calculation methods, this method works for me.

**Comment by glennWang** [comment]
```
    uint8_t packet[2048];
    uint16_t packet_len;
```

Asumed that I have assembled a ICMP6 reply packet as shown above rather than re-use the previous buffer.

How can I fill the umem with the packet in order to get the addr and len, and then send it ? 

@chaudron 

Would you please have time to make demo snippets on the following position ?

https://github.com/xdp-project/xdp-tutorial/blob/master/advanced03-AF_XDP/af_xdp_user.c#L288
