### ISSUE TITLE
advanced03: outstanding_tx

### ISSUE THREAD

**Issue by YuvRad** [xdp-project/xdp-tutorial#128]
Hi,
    shouldn't outstanding_tx be reset in complete_tx after sendto (...)?

    There doesn't seem to be any code resetting it at any point.

    Thanks,
         Yuval.

**Comment by chaudron** [comment]
Don't fully understand your question, but once the kernel is complete with the buffer, it will be returned in the xsk->umem->cq ring.

**Comment by tohojo** [comment]
Closing this - please reopen if the comments above did not resolve your problem.
