### ISSUE TITLE
XDP_TX | XDP_REDIRECT

### ISSUE THREAD

**Issue by alex60217101990** [xdp-project/xdp-tutorial#129]
Can you please tell me what conditions regarding the interface you need to fulfill in order for the return codes XDP_REDIRECT and XDP_TX to work correctly? For example, I change the destination port, and return the XDP_PASS code, the packet does not get in this interface to the server running on the port that I changed in the package:
struct tcphdr *tcp = ctx->data_start + ctx->nh_offset; tcp->dest = (__u16)bpf_ntohs(some_port_value); // 5555 for example...
Then I tried using the return code XDP_REDIRECT, followed by redirecting the packet to the external interface, but this just led to freezing the external network interface:
`INTERNAL __u32 redirect(struct context *ctx)
{
struct bpf_fib_lookup fib_params = {};
__u32 action = XDP_PASS;

if (ctx->v4 && ctx->tcp)
{

    /* populate the fib_params fields to prepare for the lookup */
	fib_params.family	= AF_INET;
	fib_params.tos		= ctx->v4->tos;
	fib_params.l4_protocol	= ctx->v4->protocol;
	fib_params.sport	= ctx->tcp->source;
	fib_params.dport	= some_port_value;
	fib_params.tot_len	= bpf_ntohs(ctx->v4->tot_len);
	fib_params.ipv4_src	= ctx->v4->saddr;
	fib_params.ipv4_dst	= ctx->v4->daddr;
    /* Set a proper destination address */
       memcpy(custom_ctx.eth->h_dest, , ETH_ALEN);
       action = bpf_redirect_map(&tx_port, 0, 0);
}

fib_params.ifindex = 1;
/* this is where the FIB lookup happens. If the lookup is successful */
/* it will populate the fib_params.ifindex with the egress interface index */
__u16 h_proto = ctx->eth->h_proto;
int rc = bpf_fib_lookup(ctx, &fib_params, sizeof(fib_params), 0);
switch (rc) {
case BPF_FIB_LKUP_RET_SUCCESS:         /* lookup successful */
 	   /* we are a router, so we need to decrease the ttl */
 	if (h_proto == bpf_htons(ETH_P_IP))
 		ip_decrease_ttl(ctx->v4);
 	else if (h_proto == bpf_htons(ETH_P_IPV6))
 		ctx->v6->hop_limit--;
 	/* set the correct new source and destionation mac addresses */
 	/* can be found in fib_params.dmac and fib_params.smac */
 	memcpy(ctx->eth->h_dest, fib_params.dmac, ETH_ALEN);
 	memcpy(ctx->eth->h_source, fib_params.smac, ETH_ALEN);
 	/* and done, now we set the action to bpf_redirect_map with fib_params.ifindex which is the egress port as paramater */
 	action = bpf_redirect_map(&tx_port, fib_params.ifindex, 0);
 	break;
 case BPF_FIB_LKUP_RET_BLACKHOLE:    /* dest is blackholed; can be dropped */
 case BPF_FIB_LKUP_RET_UNREACHABLE:  /* dest is unreachable; can be dropped */
 case BPF_FIB_LKUP_RET_PROHIBIT:     /* dest not allowed; can be dropped */
 	action = XDP_DROP;
 	break;
 case BPF_FIB_LKUP_RET_NOT_FWDED:    /* packet is not forwarded */
 case BPF_FIB_LKUP_RET_FWD_DISABLED: /* fwding is not enabled on ingress */
 case BPF_FIB_LKUP_RET_UNSUPP_LWT:   /* fwd requires encapsulation */
 case BPF_FIB_LKUP_RET_NO_NEIGH:     /* no neighbor entry for nh */
 case BPF_FIB_LKUP_RET_FRAG_NEEDED:  /* fragmentation required to fwd */
 	/* PASS */
 	break;
 }

return action; 
}`

**Comment by tohojo** [comment]
alex60217101990 <notifications@github.com> writes:

> Can you please tell me what conditions regarding the interface you need to fulfill in order for the return codes XDP_REDIRECT and XDP_TX to work correctly? For example, I change the destination port, and return the XDP_PASS code, the packet does not get in this interface to the server running on the port that I changed in the package:
> struct tcphdr *tcp = ctx->data_start + ctx->nh_offset; tcp->dest =
> (__u16)bpf_ntohs(some_port_value); // 5555 for example...

If you're not fixing up the checksum, the packet is going to be dropped
by the stack...


> Then I tried using the return code XDP_REDIRECT, followed by
> redirecting the packet to the external interface, but this just led to
> freezing the external network interface:

Freezing how? Which driver?

**Comment by alex60217101990** [comment]
but could you tell me how to correctly recalculate the checksum of the packet, after changing the destination port?

**Comment by tohojo** [comment]
alex60217101990 <notifications@github.com> writes:

> but could you tell me how to correctly recalculate the checksum of the
> packet, after changing the destination port?

There's an example of how to do this for ICMP packets in the packet03
lesson. Note that this will not be enough if you're actually trying to
connect to a TCP service this way - the replies are going to look wrong
to the client and will be dropped there unless you also rewrite the
replies somehow...

**Comment by tohojo** [comment]
Closing this - please reopen if the comments above did not resolve your problem.
