### ISSUE TITLE
Does kernel create two map instances ?

### ISSUE THREAD

**Issue by lrouter** [xdp-project/xdp-tutorial#133]
I have a ebpf object file with 2 prog sections. 
Both prog sections reference to a same map "stats_map".  If I firstly attach prog A to eth0, then attach prog B to eth2. I run loader bin twice to finish the attachments.
The loader pins map into bpf fs based on the interface name. 
I see two map files under the fs directory. Are there two map instances in the kernel at the same time ?

**Comment by tohojo** [comment]
lrouter <notifications@github.com> writes:

> I have a ebpf object file with 2 prog sections. 
> Both prog sections reference to a same map "stats_map".  If I firstly attach prog A to eth0, then attach prog B to eth2. I run loader bin twice to finish the attachments.
> The loader pins map into bpf fs based on the interface name. 
> I see two map files under the fs directory. Are there two map instances in the kernel at the same time ?

I would expect so, yeah. You can check with bpftool - just run 'bpftool
map' as root, and it'll give you a list of all maps currently in the
kernel.

You can also make the programs explicitly reuse the maps; there is an
example of how to do this in the basic04 lesson.

**Comment by tohojo** [comment]
Closing this - please reopen if the comments above did not resolve your problem.
