### ISSUE TITLE
Does XDP support core pinning?

### ISSUE THREAD

**Issue by stevelorenz** [xdp-project/xdp-tutorial#137]
Dear XDP developers,

I have searched online and "grep" in the tutorials and xdp-tools before asking the question here. 
May I ask does XDP supports core-pinning like DPDK applications ? I am currently working on a comparison of CPU energy consumption between XDP and DPDK for flow monitoring (Firstly without NIC offloading, and I will show XDP-based solution is much better :wink: ). `turbostat` is used for energy management. It can measure the energy consumption of each core.  In order to avoid the impact of background processes, I have used `isolcpus` in kernel command line to run unrelated processes on one core, then used pinning function e.g. provided by DPDK to run the monitoring process on a another core for measurement. Does XDP loader also supports core pinning?

Thanks so much for your information.

**Comment by tohojo** [comment]
Zuo Xiang <notifications@github.com> writes:

> Dear XDP developers,
>
> I have searched online and "grep" in the tutorials and xdp-tools
> before asking the question here. May I ask does XDP supports
> core-pinning like DPDK applications ? I am currently working on a
> comparison of CPU energy consumption between XDP and DPDK for flow
> monitoring (Firstly without NIC offloading, and I will show XDP-based
> solution is much better :wink: ). `turbostat` is used for energy
> management. It can measure the energy consumption of each core. In
> order to avoid the impact of background processes, I have used
> `isolcpus` in kernel command line to run unrelated processes on one
> core, then used pinning function e.g. provided by DPDK to run the
> monitoring process on a another core for measurement. Does XDP loader
> also supports core pinning?

It does indirectly: the XDP program will be run on whatever CPU receives
the packet. So you can program the NIC (with RSS configuration) to send
packets to a particular receive queue, and then pin the IRQs for that
receive queue on a CPU. That will cause all XDP work (and other network
stack work) to be pinned to that CPU (or set of CPUs).

**Comment by stevelorenz** [comment]
Thanks so much for your quick and detailed response :+1: :+1: :+1: .

**Comment by tohojo** [comment]
On 15 July 2020 13:33:41 CEST, Zuo Xiang <notifications@github.com> wrote:
>Thanks so much for your quick and detailed response :+1: :+1: :+1: .

You're welcome! :)
