### ISSUE TITLE
advanced03-AF_XDP: whether af_xdp support the function on user space like XDP_PASS in the BPF program ?

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#144]
For example:

I transfer all packets to af_xdp by using bpf_redirect_map, and then parse the packets on user space.

If some packet is icmp or arp, I can forward the packet to the kernel, the kernel is responsible for repling such packet.

**Comment by tohojo** [comment]
Yes, you can do that, but you'll have to make the decision in the BPF program before you redirect via bpf_redirect_map. There is no way to re-inject the packet into the kernel once it has been forwarded to the AF_xdp socket. But doing so before is one of the neat thing made possible by XDP :)
