### ISSUE TITLE
advanced03-AF_XDP: whether eBPF program return XDP_PASS or XDP_DROP , af_xdp socket always receive packet on user space

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#145]
It is strange.

```
SEC("xdp_sock")
int xdp_sock_prog(struct xdp_md *ctx) {
//    return XDP_PASS;
    return XDP_DROP;
}
```

**Comment by tohojo** [comment]
glennWang <notifications@github.com> writes:

> It is strange.
>
> ```
> SEC("xdp_sock")
> int xdp_sock_prog(struct xdp_md *ctx) {
> //    return XDP_PASS;
>     return XDP_DROP;
> }
> ```

Hmm, are you sure the right program is actually installed on the
interface? Try dumping the byte code from the kernel with bpftool...
