### ISSUE TITLE
packet02 rewirte port number not work

### ISSUE THREAD

**Issue by woodliu** [xdp-project/xdp-tutorial#146]
i copy the code from `xdp_prog_kern02.c` as:
```
int xdp_patch_ports_func(struct xdp_md *ctx)
{
	int action = XDP_PASS;
	int eth_type, ip_type;
	struct ethhdr *eth;
	struct iphdr *iphdr;
	struct ipv6hdr *ipv6hdr;
	struct udphdr *udphdr;
	struct tcphdr *tcphdr;
	void *data_end = (void *)(long)ctx->data_end;
	void *data = (void *)(long)ctx->data;
	struct hdr_cursor nh = { .pos = data };

	eth_type = parse_ethhdr(&nh, data_end, &eth);
	if (eth_type < 0) {
		action = XDP_ABORTED;
		goto out;
	}

	if (eth_type == bpf_htons(ETH_P_IP)) {
		ip_type = parse_iphdr(&nh, data_end, &iphdr);
	} else if (eth_type == bpf_htons(ETH_P_IPV6)) {
		ip_type = parse_ip6hdr(&nh, data_end, &ipv6hdr);
	} else {
		goto out;
	}

	if (ip_type == IPPROTO_UDP) {
		if (parse_udphdr(&nh, data_end, &udphdr) < 0) {
			action = XDP_ABORTED;
			goto out;
		}
		udphdr->dest = bpf_htons(bpf_ntohs(udphdr->dest) - 1);
	} else if (ip_type == IPPROTO_TCP) {
		if (parse_tcphdr(&nh, data_end, &tcphdr) < 0) {
			action = XDP_ABORTED;
			goto out;
		}
		tcphdr->dest = bpf_htons(bpf_ntohs(tcphdr->dest) - 1);
	}

out:
	return xdp_stats_record_action(ctx, action);
}
```
But when i use `ssh` or `nc` to send TCP/UDP to port 2000, it always shows 2000, not 1999. I have see the other issue, just send packet from one interface(set up by testenv.sh) and use tcpdump the catch it from another interface. The operation like:
In the new network namespace i create UDP socket use `nc -u -l 2000`, out of this network namespace, i connect to the UDP server use `nc -u 10.11.1.2 2000`

**Comment by tohojo** [comment]
charlie <notifications@github.com> writes:

> @tohojo Hi，I just use tcpdump to monitor the packets，the port not
> change(neither from source interface, nor destination interface)...

Hmm, then I guess the packet parsing is failing? Have you checked (with
xdp-monitor, for instance) what your XDP program is actually returning?
If it's XDP_ABORTED that would be a good indication that it is failing
to parse the packet...

**Comment by woodliu** [comment]
@tohojo Hi ,sorry for so late to reply, i will try this recently and tell you the result, thank you for your kind!

**Comment by tohojo** [comment]
Closing this - please reopen if the comments above did not resolve your problem.
