### ISSUE TITLE
Best way to represent 5 tuple information (srcip, dstip, srcport, dstport, protocol) as a key to the maps

### ISSUE THREAD

**Issue by sbibek** [xdp-project/xdp-tutorial#147]
I am experimenting on collecting flow metrics which are identified by 5 tuple (srcip, dstip, srcport, dstport, protocol). I need a way to transform this information into the key for use in the maps in such a way that key is same for packet originating from any of the communicating hosts. I have found some examples using just plain XOR to do this, I am not sure if that is the good way. Please suggest.

**Comment by tohojo** [comment]
Just define your own struct and use that as the map key? For hashmaps that will work just fine...

**Comment by tohojo** [comment]
Closing this - please reopen if the comments above did not resolve your problem.
