### ISSUE TITLE
basic01-xdp-pass: Function not implemented

### ISSUE THREAD

**Issue by HypoGump** [xdp-project/xdp-tutorial#148]
I followed the tutorial [Setup dependencies](https://github.com/xdp-project/xdp-tutorial/blob/3a1c469cc8e7f1113452a940770a7707164e81ce/setup_dependencies.org). But when I loaded `xdp_pass_kern.o` with `xdp_pass_user`, I get following error:
```
[root@centos /data/xdp-tutorial/basic01-xdp-pass]# ./xdp_pass_user --dev lo --skb-mode
libbpf: Error in bpf_object__probe_name():Function not implemented(38). Couldn't load basic 'r0 = 0' BPF program.
libbpf: Error in bpf_object__probe_global_data():Function not implemented(38). Couldn't create simple
array map.
libbpf: load bpf program failed: Function not implemented
libbpf: failed to load program 'xdp'
libbpf: failed to load object 'xdp_pass_kern.o'
ERR: loading BPF-OBJ file(xdp_pass_kern.o) (-22): Invalid argument
ERR: loading file: xdp_pass_kern.o
``` 

Setup
- Linux kernel 5.4.32
- Centos 7.6

**Comment by tohojo** [comment]
Xunqi Lai <notifications@github.com> writes:

> I followed the tutorial [Setup dependencies](https://github.com/xdp-project/xdp-tutorial/blob/3a1c469cc8e7f1113452a940770a7707164e81ce/setup_dependencies.org). But when I loaded `xdp_pass_kern.o` with `xdp_pass_user`, I get following error:
> ```
> [root@centos /data/xdp-tutorial/basic01-xdp-pass]# ./xdp_pass_user --dev lo --skb-mode
> libbpf: Error in bpf_object__probe_name():Function not implemented(38). Couldn't load basic 'r0 = 0' BPF program.
> libbpf: Error in bpf_object__probe_global_data():Function not implemented(38). Couldn't create simple
> array map.
> libbpf: load bpf program failed: Function not implemented
> libbpf: failed to load program 'xdp'
> libbpf: failed to load object 'xdp_pass_kern.o'
> ERR: loading BPF-OBJ file(xdp_pass_kern.o) (-22): Invalid argument
> ERR: loading file: xdp_pass_kern.o
> ``` 
>
> Setup
> - Linux kernel 5.4.32
> - Centos 7.6

This looks like you have not enabled BPF support in your kernel config?

**Comment by tohojo** [comment]
Closing this - please reopen if the comments above did not resolve your problem.
