### ISSUE TITLE
Can see packets only of one direction but not the other in XDP

### ISSUE THREAD

**Issue by sbibek** [xdp-project/xdp-tutorial#149]
My XDP program shows only packets from one specific direction of a TCP session. The packets from other direction doesn't show up at all.  I was able to confirm this behavior using the wireshrak and logging the incoming packets on the XDP program. Is there anything I need to be able to see packets of both direction?

**Comment by netoptimizer** [comment]
XDP is only a RX-hook, so this is expected behavior.
