### ISSUE TITLE
How to clear or empty the bpf hash map?

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#150]
There are methods to look and update the bpf hash map, but how to clear or empty it?

**Comment by tohojo** [comment]
bpf_map_delete_elem()?

**Comment by glennWang** [comment]
> bpf_map_delete_elem()?


I have 1M key-value, with some structure as key, I want to clean up before exit the program. 

Can I traverse the entire hash map and clean it up ?

**Comment by tohojo** [comment]
There's a get_next_key () method you can use to traverse the map. There's also a batch delete method, but you still have to supply all the keys; there's no "reset".

If you're removing all the BPF programs on exit (so the map is no longer used), you don't have to clear it first, the kernel will happily remove a map that still has items in it...
