### ISSUE TITLE
A strange question, bpf_map_lookup_elem not always work successfully on af_xdp userspace.

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#152]
```
struct ip_5_tuple
{
    __u32 ip_src;    /* network-byte-order */
    __u32 ip_dest;   /* network-byte-order */
    __u16 port_src;  /* network-byte-order */
    __u16 port_dest; /* network-byte-order */
    __u8 proto;      /* tcp: 6 udp: 17 */
};

struct bpf_map_def SEC("maps") conns_map = {
    .type = BPF_MAP_TYPE_HASH,
    .key_size = sizeof(struct ip_5_tuple),
    .value_size = sizeof(struct conns*),
    .max_entries = 32,
};
```

After bpf_map_update_elem(..., BPF_ANY), 

bpf_map_lookup_elem() sometimes can look up the k-v, sometimes can not look up the k-v. 

The key is the same.

**Comment by tohojo** [comment]
You'll get one byte of padding at the end of that structure, so it may be that that is just not being zeroed properly? You can try packing it, or manually adding another u8 that you always set to zero...

**Comment by glennWang** [comment]
> You'll get one byte of padding at the end of that structure, so it may be that that is just not being zeroed properly? You can try packing it, or manually adding another u8 that you always set to zero...

This is really the problem.

Before assign  values, initialize the struct with memset can deal with the problem.

`memset(&conn_key, 0, sizeof(struct ip_5_tuple));`
