### ISSUE TITLE
How can I make xdp program running on specified cpu core ?

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#157]
As the title said.

**Comment by tohojo** [comment]
By making sure your NIC delivers the packets on that core. This usually requires fiddling with the NIC settings in ethtool, specifically configuring RSS and pinning receive queues to CPUs.

**Comment by glennWang** [comment]
To get the highest performance, I envisioned a plan:

- Make the XDP program running on the specified cpu core.

- By using XDP_ SHARED_ UMEM flag, create multiple af_xdp socket, each af_xdp socket runs in a separate thread (bound to the different cpu core).

- In xdp program, by using bpf_ redirect_ map redirects frames to different af_ xdp socket

Is this feasible?

**Comment by glennWang** [comment]
> By making sure your NIC delivers the packets on that core. This usually requires fiddling with the NIC settings in ethtool, specifically configuring RSS and pinning receive queues to CPUs.

I think the xdp bytecode is running in eBPF VM.

Put it with another way, how to make eBPF VM running on the specified cpu core ?

**Comment by tohojo** [comment]
glennWang <notifications@github.com> writes:

>> By making sure your NIC delivers the packets on that core. This usually requires fiddling with the NIC settings in ethtool, specifically configuring RSS and pinning receive queues to CPUs.
>
> I think the xdp bytecode is running in eBPF VM.
>
> Put it with another way, how to make eBPF VM running on the specified
> cpu core ?

As I said, by steering the NIC processing. An eBPF program is run in
response to an event in the kernel; in the case of XDP that event is a
packet arriving. So you need to steer the kernel to process that packet
on a particular CPU, which is what you do with RSS config + IRQ
affinity.

As for the rest of your proposed scheme, I *think* it will work (not
quite sure how shared_umem works for XSK, but I believe that's roughly the
use case...)

**Comment by glennWang** [comment]
thanks a lot

**Comment by glennWang** [comment]
@tohojo 

I`m a little confused.

An umem is associated to a netdev and a specific queue id of that netdev.

A socket is bound to a netdev device and a specific queue id on that device too.

Multiple sockets can be bound to the same umem.

bpf_redirect_map(&xsks_map, rr, 0) can decide frame to which socket by setting rr.

If the nic has more than one rx queue, for good performance, this means that the quantity of umem is the same as the quantity of rx queue.

Am I right ?

**Comment by tohojo** [comment]
glennWang <notifications@github.com> writes:

> @tohojo 
>
> I`m a little confused.
>
> An umem is associated to a netdev and a specific queue id of that netdev.
>
> A socket is bound to a netdev device and a specific queue id on that device too.
>
> Multiple sockets can be bound to the same umem.
>
> bpf_redirect_map(&xsks_map, rr, 0) can decide frame to which socket by setting rr.
>
> If the nic has more than one rx queue, for good performance, this means that the quantity of umem is the same as the quantity of rx queue.
>
> Am I right ?

Yeah, you're right, you'll need a separate umem area for each RXQ; the
shared umem doesn't help you there, my bad :)

**Comment by AmanTrance** [comment]
> [@tohojo](https://github.com/tohojo)
> 
> I`m a little confused.
> 
> An umem is associated to a netdev and a specific queue id of that netdev.
> 
> A socket is bound to a netdev device and a specific queue id on that device too.
> 
> Multiple sockets can be bound to the same umem.
> 
> bpf_redirect_map(&xsks_map, rr, 0) can decide frame to which socket by setting rr.
> 
> **If the nic has more than one rx queue, for good performance, this means that the quantity of umem is the same as the quantity of rx queue.**
> 
> Am I right ?

UMEM is different than `RX` Queue, the memory region is a place where you store data and RX queue handles the ownership of the pointer which is pointing to a offset in UMEM
