### ISSUE TITLE
How to use BPF_MAP_TYPE_PERCPU_HASH?

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#158]
BPF_MAP_TYPE_PERCPU_ARRAY is used as the following. However how to use BPF_MAP_TYPE_PERCPU_HASH ?

BPF_MAP_TYPE_PERCPU_ARRAY: kernel programs implicitly write to a per-CPU allocated array which minimizes lock contention in BPF program context. When bpf_map_lookup_elem() is called, it retrieves NR_CPUS values. For example, if we are summing a stat across CPUs, we would do something like this:
  ```
                      long values[nr_cpus];
                                                ...

                        ret = bpf_map_lookup_elem(map_fd, &next_key, values);
                        if (ret) {
                                perror("Error looking up stat");
                                continue;
                        }

                        for (i = 0; i < nr_cpus; i++) {
                                sum += values[i];
                        }

```

**Comment by tohojo** [comment]
Have a look at the stats example, that uses a percpu array...
