### ISSUE TITLE
cannot ping root from namespace created by testenv

### ISSUE THREAD

**Issue by tlodge** [xdp-project/xdp-tutorial#159]
Hi,

I have been running through the examples on Fedora (32 Workstation Edition) with no issues, but then did a fresh install of Fedora, and now it seems as though any test network that I create using` testenv.sh setup --name [netname] ` fails to ping between the new namespace and host (i.e I get 100% packet loss) - this is before I attach any xdp programs to the interface.  The odd thing is that when it was working, this was also off a fresh install.  

Looking at the ipv6 routing table for the newly created namespace, I have:
| Destination          | Next Hop  |               Flag | Met | Ref | Use | If |
|----------------------|---------------|-------------------|--------|-------|-----|-----|
fc00:dead:cafe:1::/64      |    [::]           |             U   |  256 | 5   |   0 | veth0
fc00:dead:cafe::/48         |    fc00:dead:cafe:1::1     |    UG  |  1024 | 1 |     0 | veth0
fe80::/64              |         [::]            |            U  |  256 |  2 |     0 | veth| 0| 
[::]/0         |                 [::]        |                !n |   -1 |  1   |   0|  lo| 
localhost/128      |             [::]      |                 Un |   0 |   2   |   0|  lo| 
localhost-live/128 |            [::]        |                Un  |  0 |   5 |     0|  veth0| 
localhost-live/128   |           [::]     |                   Un |   0  |  2    |  0|  veth0| 
[::]/0      |                    [::]    |                    !n  |  -1 |  1 |    0|  lo| 

and on the host machine I have

| Destination          | Next Hop  |               Flag | Met | Ref | Use | If |
|----------------------|---------------|-------------------|--------|-------|-----|-----|
localhost/128             |     [::]            |           U |   256 |1  |   0| lo|
fc00:dead:cafe:1::/64      |    [::]      |                U  |  256| 3   |  0 |veth-basic02|
fe80::/64             |         [::]             |          U   | 256| 1 |    0 |veth-basic02|
fe80::/64            |          [::]          |             U   | 600| 2 |    0 |wlp1s0|
[::]/0                    |     [::]              |         !n | -1 | 1 |    0 |lo|
localhost/128           |       [::]       |                Un|   0 |  3 |   0 |lo|
localhost-live/128      |       [::]       |                Un  | 0 |  3  |   0 |veth-basic02|
localhost-live/128      |       [::]       |                Un  | 0 | 3 |    0 |wlp1s0|
ff00::/8               |        [::]             |          U  |  256| 7  |   0 |wlp1s0|
ff00::/8               |        [::]             |          U |   256 |5 |    0 |veth-basic02|
[::]/0                   |      [::]                |     !n |  -1 | 1  |   0| lo|

Incidentally I am able to attach and run programs - though whether I run an xdp_drop or xdp_pass, no pings get through.  When I run xdp_abort, the output from perf gives me:

```
ping6 37436 [003]  2732.923002: xdp:xd>
ping6 37436 [003]  2733.947080: xdp:xd>
ping6 37436 [003]  2734.971054: xdp:xd>
ping6 37436 [003]  2735.995046: xdp:xd>
```
Which suggests at least that the problem is just to do with testenv.sh.   I'm happy to provide any more info - and any suggestions gratefully received!

**Comment by tohojo** [comment]
Which direction are you pinging? Does the other direction work? Can you see the packets with tcpdump?

**Comment by tlodge** [comment]
Thanks for the response.  I am pinging from veth-basic02 to the host.  When I run tcpdump on the host (`tcpdump -i veth1 "icmp6 && ip6[40] == 128"`) I don't see any packets come in.  I have just tried to run an alternative script that I found [here](https://blogs.igalia.com/dpino/2016/05/02/network-namespaces-ipv6/) and that seems to work, insofar as it creates a veth1 and vpeer1 and I can ping the veth1 ipv6 address from inside vpeer1 (and see the packets come in on tcpdump).  I'm planning on seeing what the difference is between this script and testenv.sh to see I can figure out what's happening.

**Comment by tohojo** [comment]
Hmm, check 'ip neigh' both inside and outside? The testenv script sets up permanent neighbour entries to avoid queries on the link (because xdp can interfere with that), so maybe those are wrong?

**Comment by tlodge** [comment]
Thanks.  On the host I have:

```
192.168.1.1 dev wlp1s0 lladdr 10:0c:6b:23:7e:32 REACHABLE
fc00:dead:cafe:1::2 dev veth-basic02 lladdr e6:5c:9c:99:6b:a9 PERMANENT
```
and in the veth-basic02 namespace I have:

`fc00:dead:cafe:1::1 dev veth0 lladdr 72:7d:f3:0a:e9:7d PERMANENT`

**Comment by tohojo** [comment]
tlodge <notifications@github.com> writes:

> Thanks.  On the host I have:
>
> ```
> 192.168.1.1 dev wlp1s0 lladdr 10:0c:6b:23:7e:32 REACHABLE
> fc00:dead:cafe:1::2 dev veth-basic02 lladdr e6:5c:9c:99:6b:a9 PERMANENT
> ```
> and in the veth-basic02 namespace I have:
>
> `fc00:dead:cafe:1::1 dev veth0 lladdr 72:7d:f3:0a:e9:7d PERMANENT`

And do those MAC addresses match the respective addresses (i.e., veth0
should have e6:5c:9c:99:6b:a9 and veth-basic02 should have
72:7d:f3:0a:e9:7d)? Does tcpdump show anything if you do not supply it
with any filters?

**Comment by tlodge** [comment]
Ah, so veth0 does have the correct corresponding mac address (e6:5c:9c:99:6b:a9), but veth-basic02 has a different mac address:

```
veth-basic02: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::6ca7:4ff:fe53:7b11  prefixlen 64  scopeid 0x20<link>
        inet6 fc00:dead:cafe:1::1  prefixlen 64  scopeid 0x0<global>
        ether 6e:a7:04:53:7b:11  txqueuelen 1000  (Ethernet)
        RX packets 644  bytes 75900 (74.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 51  bytes 7536 (7.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Guess that's the problem?

**Comment by tlodge** [comment]
Just updated the neighbour entry on veth0 with the correct mac address and all now works.  Thank you so much for your help, much appreciated!

**Comment by tohojo** [comment]
tlodge <notifications@github.com> writes:

> Just updated the neighbour entry on veth0 with the correct mac address
> and all now works.  Thank you so much for your help, much appreciated!

Right, awesome! Still doesn't explain why the testenv script gets it
wrong, though. Could you please post the output of the following
commands on your system (as root):

ip link add dev vethX type veth peer name vethY
ip -br link show dev vethX
ip -br link show dev vethY
ip netns add testing
ip link set dev vethY netns testing
ip -br -n testing link show

**Comment by tlodge** [comment]
sure - I have the following:

```
[root@localhost ~]# ip link add dev vethX type veth peer name vethY
[root@localhost ~]# ip -br link show dev vethX
vethX@vethY      DOWN           ae:c9:cf:0f:b0:31 <BROADCAST,MULTICAST,M-DOWN> 
[root@localhost ~]# ip -br link show dev vethY
vethY@vethX      DOWN           ea:ab:de:4e:76:f1 <BROADCAST,MULTICAST,M-DOWN> 
[root@localhost ~]# ip netns add testing
[root@localhost ~]# ip link set dev vethY netns testing
[root@localhost ~]# ip -br -n testing link show
lo               DOWN           00:00:00:00:00:00 <LOOPBACK> 
vethY@if7        DOWN           ea:ab:de:4e:76:f1 <BROADCAST,MULTICAST> 
```

**Comment by tohojo** [comment]
tlodge <notifications@github.com> writes:

> sure - I have the following:
>
> ```
> [root@localhost ~]# ip link add dev vethX type veth peer name vethY
> [root@localhost ~]# ip -br link show dev vethX
> vethX@vethY      DOWN           ae:c9:cf:0f:b0:31 <BROADCAST,MULTICAST,M-DOWN> 
> [root@localhost ~]# ip -br link show dev vethY
> vethY@vethX      DOWN           ea:ab:de:4e:76:f1 <BROADCAST,MULTICAST,M-DOWN> 
> [root@localhost ~]# ip netns add testing
> [root@localhost ~]# ip link set dev vethY netns testing
> [root@localhost ~]# ip -br -n testing link show
> lo               DOWN           00:00:00:00:00:00 <LOOPBACK> 
> vethY@if7        DOWN           ea:ab:de:4e:76:f1 <BROADCAST,MULTICAST> 
> ```

Hmm, that all looks completely normal. Odd. I just pushed a change that
simplifies the setup a bit, could you please check if that helps (i.e.,
do a git pull and try a new "testenv setup")?

**Comment by tlodge** [comment]
Just pulled the new version, but unfortunately I get the same issue:

```
sudo ../testenv/testenv.sh setup --name veth-basic02
Setting up new environment 'veth-basic02'
Setup environment 'veth-basic02' with peer ip fc00:dead:cafe:1::2.

Running ping from inside test environment:

PING fc00:dead:cafe:1::1(fc00:dead:cafe:1::1) 56 data bytes

--- fc00:dead:cafe:1::1 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

**Comment by tohojo** [comment]
tlodge <notifications@github.com> writes:

> Just pulled the new version, but unfortunately I get the same issue:
>
> ```
> sudo ../testenv/testenv.sh setup --name veth-basic02
> Setting up new environment 'veth-basic02'
> Setup environment 'veth-basic02' with peer ip fc00:dead:cafe:1::2.
>
> Running ping from inside test environment:
>
> PING fc00:dead:cafe:1::1(fc00:dead:cafe:1::1) 56 data bytes
>
> --- fc00:dead:cafe:1::1 ping statistics ---
> 1 packets transmitted, 0 received, 100% packet loss, time 0ms
> ```

OK, this is decidedly odd! Could you please try switching to the
'testenv-verbose' branch I just pushed, run the setup command again, and
post the output?

**Comment by tlodge** [comment]
sure:

```
sudo ./testenv/testenv.sh setup veth-basic02
Setting up new environment 'xdptut-7fc3'
ip link after create: 
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
eno1             DOWN           b8:ae:ed:ea:f5:17 <NO-CARRIER,BROADCAST,MULTICAST,UP> 
wlp1s0           UP             00:c2:c6:c8:89:f8 <BROADCAST,MULTICAST,UP,LOWER_UP> 
xdptut-7fc3@if2  DOWN           8e:8d:3d:c5:75:c1 <BROADCAST,MULTICAST> 
macaddr output: 'xdptut-7fc3@if2  DOWN           8e:8d:3d:c5:75:c1 <BROADCAST,MULTICAST> ' iface xdptut-7fc3 ns 
macaddr output: 'veth0@if5        DOWN           aa:76:19:6a:a1:f4 <BROADCAST,MULTICAST> ' iface veth0 ns xdptut-7fc3
outside mac: '8e:8d:3d:c5:75:c1' inside: 'aa:76:19:6a:a1:f4'
ip neigh/route outside: 
192.168.1.1 dev wlp1s0 lladdr 10:0c:6b:23:7e:32 REACHABLE
fc00:dead:cafe:1::2 dev xdptut-7fc3 lladdr aa:76:19:6a:a1:f4 PERMANENT
::1 dev lo proto kernel metric 256 pref medium
fc00:dead:cafe:1::/64 dev xdptut-7fc3 proto kernel metric 256 linkdown pref medium
fe80::/64 dev wlp1s0 proto kernel metric 600 pref medium
ip output inside after setup:
lo               UNKNOWN        127.0.0.1/8 ::1/128 
veth0@if5        UP             fc00:dead:cafe:1::2/64 fe80::a876:19ff:fe6a:a1f4/64 
fc00:dead:cafe:1::1 dev veth0 lladdr 8e:8d:3d:c5:75:c1 PERMANENT
fc00:dead:cafe:1::/64 dev veth0 proto kernel metric 256 pref medium
fc00:dead:cafe::/48 via fc00:dead:cafe:1::1 dev veth0 metric 1024 pref medium
fe80::/64 dev veth0 proto kernel metric 256 pref medium
Setup environment 'xdptut-7fc3' with peer ip fc00:dead:cafe:1::2.

Running ping from inside test environment:

PING fc00:dead:cafe:1::1(fc00:dead:cafe:1::1) 56 data bytes

--- fc00:dead:cafe:1::1 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

**Comment by tlodge** [comment]
sure:

```
sudo ./testenv/testenv.sh setup veth-basic02
Setting up new environment 'xdptut-7fc3'
ip link after create: 
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
eno1             DOWN           b8:ae:ed:ea:f5:17 <NO-CARRIER,BROADCAST,MULTICAST,UP> 
wlp1s0           UP             00:c2:c6:c8:89:f8 <BROADCAST,MULTICAST,UP,LOWER_UP> 
xdptut-7fc3@if2  DOWN           8e:8d:3d:c5:75:c1 <BROADCAST,MULTICAST> 
macaddr output: 'xdptut-7fc3@if2  DOWN           8e:8d:3d:c5:75:c1 <BROADCAST,MULTICAST> ' iface xdptut-7fc3 ns 
macaddr output: 'veth0@if5        DOWN           aa:76:19:6a:a1:f4 <BROADCAST,MULTICAST> ' iface veth0 ns xdptut-7fc3
outside mac: '8e:8d:3d:c5:75:c1' inside: 'aa:76:19:6a:a1:f4'
ip neigh/route outside: 
192.168.1.1 dev wlp1s0 lladdr 10:0c:6b:23:7e:32 REACHABLE
fc00:dead:cafe:1::2 dev xdptut-7fc3 lladdr aa:76:19:6a:a1:f4 PERMANENT
::1 dev lo proto kernel metric 256 pref medium
fc00:dead:cafe:1::/64 dev xdptut-7fc3 proto kernel metric 256 linkdown pref medium
fe80::/64 dev wlp1s0 proto kernel metric 600 pref medium
ip output inside after setup:
lo               UNKNOWN        127.0.0.1/8 ::1/128 
veth0@if5        UP             fc00:dead:cafe:1::2/64 fe80::a876:19ff:fe6a:a1f4/64 
fc00:dead:cafe:1::1 dev veth0 lladdr 8e:8d:3d:c5:75:c1 PERMANENT
fc00:dead:cafe:1::/64 dev veth0 proto kernel metric 256 pref medium
fc00:dead:cafe::/48 via fc00:dead:cafe:1::1 dev veth0 metric 1024 pref medium
fe80::/64 dev veth0 proto kernel metric 256 pref medium
Setup environment 'xdptut-7fc3' with peer ip fc00:dead:cafe:1::2.

Running ping from inside test environment:

PING fc00:dead:cafe:1::1(fc00:dead:cafe:1::1) 56 data bytes

--- fc00:dead:cafe:1::1 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

**Comment by tlodge** [comment]
..and  in xdptut-7fc3 I have

```
veth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::a876:19ff:fe6a:a1f4  prefixlen 64  scopeid 0x20<link>
        inet6 fc00:dead:cafe:1::2  prefixlen 64  scopeid 0x0<global>
        ether aa:76:19:6a:a1:f4  txqueuelen 1000  (Ethernet)
        RX packets 19  bytes 2659 (2.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 608 (608.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

and on the host I have:

```xdptut-7fc3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::ac2d:8bff:fef0:905d  prefixlen 64  scopeid 0x20<link>
        inet6 fc00:dead:cafe:1::1  prefixlen 64  scopeid 0x0<global>
        ether ae:2d:8b:f0:90:5d  txqueuelen 1000  (Ethernet)
        RX packets 6  bytes 608 (608.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19  bytes 2659 (2.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by tohojo** [comment]
tlodge <notifications@github.com> writes:

> sure:
>
> ```
> sudo ./testenv/testenv.sh setup veth-basic02
> Setting up new environment 'xdptut-7fc3'
> ip link after create: 
> lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
> eno1             DOWN           b8:ae:ed:ea:f5:17 <NO-CARRIER,BROADCAST,MULTICAST,UP> 
> wlp1s0           UP             00:c2:c6:c8:89:f8 <BROADCAST,MULTICAST,UP,LOWER_UP> 
> xdptut-7fc3@if2  DOWN           8e:8d:3d:c5:75:c1
> <BROADCAST,MULTICAST>

Hmm, looks like the link(s) are not brought up for some reason? Does 'ip
link set dev xdptut-7fc3 up' work?

Pushed another commit to testenv-verbose branch moving the 'link up' a
bit later; could you try that please?

**Comment by tlodge** [comment]
ok this is odd - did a teardown of xdptut-7f3c and ran the script again (without pulling the new version), and this time it worked:

```
sudo ./testenv/testenv.sh setup veth-basic02
Setting up new environment 'xdptut-11be'
ip link after create: 
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
eno1             DOWN           b8:ae:ed:ea:f5:17 <NO-CARRIER,BROADCAST,MULTICAST,UP> 
wlp1s0           UP             00:c2:c6:c8:89:f8 <BROADCAST,MULTICAST,UP,LOWER_UP> 
xdptut-11be@if2  DOWN           d6:e3:f2:a2:ce:21 <BROADCAST,MULTICAST> 
macaddr output: 'xdptut-11be@if2  DOWN           3e:88:5f:99:ae:d0 <BROADCAST,MULTICAST> ' iface xdptut-11be ns 
macaddr output: 'veth0@if6        DOWN           3a:c4:92:fe:b1:d1 <BROADCAST,MULTICAST> ' iface veth0 ns xdptut-11be
outside mac: '3e:88:5f:99:ae:d0' inside: '3a:c4:92:fe:b1:d1'
ip neigh/route outside: 
192.168.1.1 dev wlp1s0 lladdr 10:0c:6b:23:7e:32 REACHABLE
fc00:dead:cafe:1::2 dev xdptut-11be lladdr 3a:c4:92:fe:b1:d1 PERMANENT
::1 dev lo proto kernel metric 256 pref medium
fc00:dead:cafe:1::/64 dev xdptut-11be proto kernel metric 256 linkdown pref medium
fe80::/64 dev wlp1s0 proto kernel metric 600 pref medium
ip output inside after setup:
lo               UNKNOWN        127.0.0.1/8 ::1/128 
veth0@if6        UP             fc00:dead:cafe:1::2/64 fe80::38c4:92ff:fefe:b1d1/64 
fc00:dead:cafe:1::1 dev veth0 lladdr 3e:88:5f:99:ae:d0 PERMANENT
fc00:dead:cafe:1::/64 dev veth0 proto kernel metric 256 pref medium
fc00:dead:cafe::/48 via fc00:dead:cafe:1::1 dev veth0 metric 1024 pref medium
fe80::/64 dev veth0 proto kernel metric 256 pref medium
Setup environment 'xdptut-11be' with peer ip fc00:dead:cafe:1::2.

Running ping from inside test environment:

PING fc00:dead:cafe:1::1(fc00:dead:cafe:1::1) 56 data bytes
64 bytes from fc00:dead:cafe:1::1: icmp_seq=1 ttl=64 time=0.052 ms

**Comment by tohojo** [comment]
tlodge <notifications@github.com> writes:

> ..and  in xdptut-7fc3 I have
>
> ```
> veth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet6 fe80::a876:19ff:fe6a:a1f4  prefixlen 64  scopeid 0x20<link>
>         inet6 fc00:dead:cafe:1::2  prefixlen 64  scopeid 0x0<global>
>         ether aa:76:19:6a:a1:f4  txqueuelen 1000  (Ethernet)
>         RX packets 19  bytes 2659 (2.5 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 6  bytes 608 (608.0 B)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> ```

OK, now the links are up; maybe they're just being delayed? Does
'testenv ping' work?

**Comment by tlodge** [comment]
ah - sorry was midway through pulling new script - and I got the following:

```
sudo ./testenv/testenv.sh setup veth-basic02
Setting up new environment 'xdptut-2789'
ip link after create: 
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
eno1             DOWN           b8:ae:ed:ea:f5:17 <NO-CARRIER,BROADCAST,MULTICAST,UP> 
wlp1s0           UP             00:c2:c6:c8:89:f8 <BROADCAST,MULTICAST,UP,LOWER_UP> 
xdptut-2789@if2  DOWN           d6:90:76:09:20:0f <BROADCAST,MULTICAST> 
macaddr output: 'xdptut-2789@if2  DOWN           d6:90:76:09:20:0f <BROADCAST,MULTICAST> ' iface xdptut-2789 ns 
macaddr output: 'veth0@if7        DOWN           f2:ed:f8:bd:39:e7 <BROADCAST,MULTICAST> ' iface veth0 ns xdptut-2789
outside mac: 'd6:90:76:09:20:0f' inside: 'f2:ed:f8:bd:39:e7'
ip neigh/route outside: 
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
eno1             DOWN           b8:ae:ed:ea:f5:17 <NO-CARRIER,BROADCAST,MULTICAST,UP> 
wlp1s0           UP             00:c2:c6:c8:89:f8 <BROADCAST,MULTICAST,UP,LOWER_UP> 
xdptut-2789@if2  LOWERLAYERDOWN d6:90:76:09:20:0f <NO-CARRIER,BROADCAST,MULTICAST,UP> 
192.168.1.1 dev wlp1s0 lladdr 10:0c:6b:23:7e:32 REACHABLE
fc00:dead:cafe:1::2 dev xdptut-2789 lladdr f2:ed:f8:bd:39:e7 PERMANENT
::1 dev lo proto kernel metric 256 pref medium
fc00:dead:cafe:1::/64 dev xdptut-2789 proto kernel metric 256 linkdown pref medium
fe80::/64 dev wlp1s0 proto kernel metric 600 pref medium
RTNETLINK answers: No route to host
Error during setup, removing partially-configured environment 'xdptut-2789'
```

**Comment by tlodge** [comment]
Output is:

```
net.ipv6.conf.all.accept_dad = 0
```

incidentally I reverted to the previous debug commit and re-ran the script and it worked again.  I did a testenv.sh ping and after a short pause, the ping started to work.

**Comment by tohojo** [comment]
tlodge <notifications@github.com> writes:

> Output is:
>
> ```
> net.ipv6.conf.all.accept_dad = 0
> ```
>
> incidentally I reverted to the previous debug commit and re-ran the
> script and it worked again.  I did a testenv.sh ping and after a short
> pause, the ping started to work.

Right, added an explicit wait for that (still in the testenv-verbose
branch). Could you test that, please?

**Comment by tlodge** [comment]
Looks good!

```
sudo ./testenv/testenv.sh setup veth-basic02
Setting up new environment 'xdptut-3250'
ip link after create: 
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
eno1             DOWN           b8:ae:ed:ea:f5:17 <NO-CARRIER,BROADCAST,MULTICAST,UP> 
wlp1s0           UP             00:c2:c6:c8:89:f8 <BROADCAST,MULTICAST,UP,LOWER_UP> 
xdptut-3250@if2  DOWN           1a:fc:ec:23:b2:04 <BROADCAST,MULTICAST> 
macaddr output: 'xdptut-3250@if2  DOWN           fe:da:bf:d7:6c:a2 <BROADCAST,MULTICAST> ' iface xdptut-3250 ns 
macaddr output: 'veth0@if10       DOWN           b6:9d:aa:50:3f:36 <BROADCAST,MULTICAST> ' iface veth0 ns xdptut-3250
outside mac: 'fe:da:bf:d7:6c:a2' inside: 'b6:9d:aa:50:3f:36'
ip neigh/route outside: 
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
eno1             DOWN           b8:ae:ed:ea:f5:17 <NO-CARRIER,BROADCAST,MULTICAST,UP> 
wlp1s0           UP             00:c2:c6:c8:89:f8 <BROADCAST,MULTICAST,UP,LOWER_UP> 
xdptut-3250@if2  UNKNOWN        fe:da:bf:d7:6c:a2 <BROADCAST,MULTICAST,UP> 
192.168.1.1 dev wlp1s0  INCOMPLETE
fc00:dead:cafe:1::2 dev xdptut-3250 lladdr b6:9d:aa:50:3f:36 PERMANENT
::1 dev lo proto kernel metric 256 pref medium
fc00:dead:cafe:1::/64 dev xdptut-3250 proto kernel metric 256 linkdown pref medium
fe80::/64 dev wlp1s0 proto kernel metric 600 pref medium
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether b8:ae:ed:ea:f5:17 brd ff:ff:ff:ff:ff:ff
    altname enp0s31f6
3: wlp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:c2:c6:c8:89:f8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.15/24 brd 192.168.1.255 scope global dynamic noprefixroute wlp1s0
       valid_lft 83600sec preferred_lft 83600sec
    inet6 fe80::a265:241b:462b:ab62/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
10: xdptut-3250@if2: <BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether fe:da:bf:d7:6c:a2 brd ff:ff:ff:ff:ff:ff link-netns xdptut-3250
    inet6 fc00:dead:cafe:1::1/64 scope global 
       valid_lft forever preferred_lft forever
ip output inside after setup:
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
veth0@if10       UP             b6:9d:aa:50:3f:36 <BROADCAST,MULTICAST,UP,LOWER_UP> 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: veth0@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether b6:9d:aa:50:3f:36 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fc00:dead:cafe:1::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::b49d:aaff:fe50:3f36/64 scope link 
       valid_lft forever preferred_lft forever
fc00:dead:cafe:1::1 dev veth0 lladdr fe:da:bf:d7:6c:a2 PERMANENT
fc00:dead:cafe:1::/64 dev veth0 proto kernel metric 256 pref medium
fc00:dead:cafe::/48 via fc00:dead:cafe:1::1 dev veth0 metric 1024 pref medium
fe80::/64 dev veth0 proto kernel metric 256 pref medium
Setup environment 'xdptut-3250' with peer ip fc00:dead:cafe:1::2.
Waiting for interface configuration to settle...

Running ping from inside test environment:

PING fc00:dead:cafe:1::1(fc00:dead:cafe:1::1) 56 data bytes
64 bytes from fc00:dead:cafe:1::1: icmp_seq=1 ttl=64 time=0.050 ms

--- fc00:dead:cafe:1::1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.050/0.050/0.050/0.000 ms
```

**Comment by tohojo** [comment]
tlodge <notifications@github.com> writes:

> Looks good!

Great, thanks for confirming (and for sticking with me through all those
attempts!) :)
