### ISSUE TITLE
single-cpu update for per-cpu maps

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#165]
I find the following patch:

https://patchwork.ozlabs.org/project/netdev/patch/ec8fd77bb20881e7149f7444e731c510790191ce.1576673842.git.paul.chaignon@orange.com/

Is there any plan to support this feature ?

**Comment by tohojo** [comment]
What do you mean, "plan to support this"?

**Comment by glennWang** [comment]
> What do you mean, "plan to support this"?

Of course. 

If this feature is supported, it will be more flexible and efficient to be used.

For example, when a worker thread is bound to a cpu core, bpf per-cpu map can be used like NUMA variable in the worker thread in order to get more higher performance.

**Comment by tohojo** [comment]
Sure, but what is your question, exactly? You linked a kernel patch which is being discussed on the list... If you want to chime in on that discussion, the mailing list would be the place to do so :)
