### ISSUE TITLE
switching to xdp generic mode

### ISSUE THREAD

**Issue by sachints123** [xdp-project/xdp-tutorial#166]
Hi All,
I am new to ebpf and xdp. Trying tutorial programs and trying to adopt them to python user space program. Can you please let mw know how to set xdp generic mode using python BPF libraries? Also it will be helpful if you point me to reference guide for the same.

Thanks,
Sachin

**Comment by tohojo** [comment]
sachints123 <notifications@github.com> writes:

> Hi All,
> I am new to ebpf and xdp. Trying tutorial programs and trying to adopt
> them to python user space program. Can you please let mw know how to
> set xdp generic mode using python BPF libraries? Also it will be
> helpful if you point me to reference guide for the same.

Erm, which "Python BPF libraries" are you using? And if you know that,
surely you can also Google up the reference guide if one exists? :)

**Comment by sachints123** [comment]
> sachints123 <notifications@github.com> writes:
> Hi All, I am new to ebpf and xdp. Trying tutorial programs and trying to adopt them to python user space program. Can you please let mw know how to set xdp generic mode using python BPF libraries? Also it will be helpful if you point me to reference guide for the same.
> Erm, which "Python BPF libraries" are you using? And if you know that, surely you can also Google up the reference guide if one exists? :)

I downloaded bcc source and compiled it and installed python binding as per instructions(https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source) and I am referring https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#bcc-python .
But this has very limited info on xdp flags for python.

**Comment by tohojo** [comment]
sachints123 <notifications@github.com> writes:

>> sachints123 <notifications@github.com> writes:
>> Hi All, I am new to ebpf and xdp. Trying tutorial programs and trying to adopt them to python user space program. Can you please let mw know how to set xdp generic mode using python BPF libraries? Also it will be helpful if you point me to reference guide for the same.
>> Erm, which "Python BPF libraries" are you using? And if you know that, surely you can also Google up the reference guide if one exists? :)
>
> I downloaded bcc source and compiled it and installed python binding
> as per
> instructions(https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source)
> and I am referring
> https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#bcc-python
> .

> But this has very limited info on xdp flags for python.

Oh, I see. Yeah, BCC is focused on tracing, not XDP. Don't know of any
other XDP-focused libraries for Python, I'm afraid...

**Comment by sachints123** [comment]
> sachints123 <notifications@github.com> writes:
> > sachints123 ***@***.***> writes: > Hi All, I am new to ebpf and xdp. Trying tutorial programs and trying to adopt them to python user space program. Can you please let mw know how to set xdp generic mode using python BPF libraries? Also it will be helpful if you point me to reference guide for the same. > Erm, which "Python BPF libraries" are you using? And if you know that, surely you can also Google up the reference guide if one exists? :) I downloaded bcc source and compiled it and installed python binding as per instructions(https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source) and I am referring https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#bcc-python . But this has very limited info on xdp flags for python.
> Oh, I see. Yeah, BCC is focused on tracing, not XDP. Don't know of any other XDP-focused libraries for Python, I'm afraid...
Yeah, thanks for your response. I could get the relevant flags after extensively searching some examples on the internet.
Finally it uses CGROUP_INGRESS flag to run in xdp generic mode.

Thanks,
Sachin

**Comment by tohojo** [comment]
sachints123 <notifications@github.com> writes:

>> sachints123 <notifications@github.com> writes:
>> > sachints123 ***@***.***> writes: > Hi All, I am new to ebpf and xdp. Trying tutorial programs and trying to adopt them to python user space program. Can you please let mw know how to set xdp generic mode using python BPF libraries? Also it will be helpful if you point me to reference guide for the same. > Erm, which "Python BPF libraries" are you using? And if you know that, surely you can also Google up the reference guide if one exists? :) I downloaded bcc source and compiled it and installed python binding as per instructions(https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source) and I am referring https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#bcc-python . But this has very limited info on xdp flags for python.
>> Oh, I see. Yeah, BCC is focused on tracing, not XDP. Don't know of any other XDP-focused libraries for Python, I'm afraid...

> Yeah, thanks for your response. I could get the relevant flags after
> extensively searching some examples on the internet.
>
> Finally it uses CGROUP_INGRESS flag to run in xdp generic mode.

Pretty sure CGROUP_INGRESS is not actually XDP, but a different hook.
However, that hook may well be more relevant for what you're trying to
do - in general I would not recommend relying on XDP generic mode for
anything other than testing...

**Comment by sachints123** [comment]
> sachints123 <notifications@github.com> writes:
> > sachints123 ***@***.***> writes: > > sachints123 ***@***.***> writes: > Hi All, I am new to ebpf and xdp. Trying tutorial programs and trying to adopt them to python user space program. Can you please let mw know how to set xdp generic mode using python BPF libraries? Also it will be helpful if you point me to reference guide for the same. > Erm, which "Python BPF libraries" are you using? And if you know that, surely you can also Google up the reference guide if one exists? :) I downloaded bcc source and compiled it and installed python binding as per instructions(https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source) and I am referring https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#bcc-python . But this has very limited info on xdp flags for python. > Oh, I see. Yeah, BCC is focused on tracing, not XDP. Don't know of any other XDP-focused libraries for Python, I'm afraid... Yeah, thanks for your response. I could get the relevant flags after extensively searching some examples on the internet. Finally it uses CGROUP_INGRESS flag to run in xdp generic mode.
> Pretty sure CGROUP_INGRESS is not actually XDP, but a different hook. However, that hook may well be more relevant for what you're trying to do - in general I would not recommend relying on XDP generic mode for anything other than testing...

Thank you tohojo. I was experimenting both modes on my dev setup. I got a little hold of it now. Now exploring further, how can i replicate the packets at xdp layer to multiple ports so that I can receive same packet on different VMs. I am using DEVMAP for that but I could send to only one VM. Checking on how I can send to multiple ports at the same time.

**Comment by tohojo** [comment]
You can't, yet. There are work in progress patches to add this, but until they land you can only redirect to a single port...

**Comment by sachints123** [comment]
ok thank you :)
