### ISSUE TITLE
Can XDP be used to hook TX packets？

### ISSUE THREAD

**Issue by liuhycn** [xdp-project/xdp-tutorial#172]

**Comment by tohojo** [comment]
Nope. You can use the TC BPF hook for that...

**Comment by liuhycn** [comment]
@tohojo Thank you for your reply. Can tc bpf modify the source MAC address of the TX packet?

**Comment by tohojo** [comment]
Hongyan Liu <notifications@github.com> writes:

> @tohojo Thank you for your reply. Can tc bpf modify the source MAC
> address of the TX packet?

Yeah, that should be possible :)

**Comment by liuhycn** [comment]
Thanks!
