### ISSUE TITLE
docker container process the packet on host nic 

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#179]
Put AF_ XDP encapsulates to docker, starts the container, and processes the packets on the host network card.

Is this plan feasible?

And how to configure it?

Now, I have the following problem. How can I attach af_xdp_kern.o to host nic and use docker at the same time.
```
$ docker run --rm -ti --name deploy -v `pwd`:/af_xdp docker_deploy:0.0.1 af_xdp_user -d eth1 --filename af_xdp_kern.o

ERR: --dev name unknown err(19):No such device
Usage: ./af_xdp_user [options]
Use --help (or -h) to see full option list.
```

**Comment by tohojo** [comment]
glennWang <notifications@github.com> writes:

> Put AF_ XDP encapsulates to docker, starts the container, and processes the packets on the host network card.
>
> Is this plan feasible?

Not from within the container, unless you instruct docker to move the
physical NIC inside it. You could attach the XDP program on the host and
create an AF_XDP socket there, then somehow pass that to your program
inside the container. As for how to achieve that with docker, no idea...
