### ISSUE TITLE
advanced03-AF_XDP: outstanding_tx

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#180]
https://github.com/xdp-project/xdp-tutorial/issues/128#issue-623824122

@chaudron 
@YuvRad

I have the same question:

There is only the following increasing:
https://github.com/xdp-project/xdp-tutorial/blob/master/advanced03-AF_XDP/af_xdp_user.c#L329
```
		xsk_ring_prod__tx_desc(&xsk->tx, tx_idx)->addr = addr;
		xsk_ring_prod__tx_desc(&xsk->tx, tx_idx)->len = len;
		xsk_ring_prod__submit(&xsk->tx, 1);
		xsk->outstanding_tx++;
```

That lead to the judgment is meaningless and unnecessary calls sendto.
https://github.com/xdp-project/xdp-tutorial/blob/master/advanced03-AF_XDP/af_xdp_user.c#L234
```
	if (!xsk->outstanding_tx)
		return;

	sendto(xsk_socket__fd(xsk->xsk), NULL, 0, MSG_DONTWAIT, NULL, 0);
```

 **Maybe, the outstanding_tx should be decreased or reset on somewhere ?**

**Comment by glennWang** [comment]
https://github.com/xdp-project/xdp-tutorial/blob/master/advanced03-AF_XDP/af_xdp_user.c#L234

```
if (!xsk->outstanding_tx)

// Maybe, changing the code(L234) above to the following could solve the qusetion.

if(XSK_RING_PROD__DEFAULT_NUM_DESCS == xsk_prod_nb_free(&xsk->tx, XSK_RING_PROD__DEFAULT_NUM_DESCS))
```

**Comment by chaudron** [comment]
My test setup is currently in use for something else, but I guess add a line in the L245 "if (completed > 0)" branch like:
xsk->outstanding_tx -= completed < xsk->outstanding_tx ? completed : xsk->outstanding_tx;

should do the trick. If you could test this with a high volume of traffic to make sure it continues working. Else I'll try to do it next year.
