### ISSUE TITLE
advanced03-AF_XDP: only received packets when executed tcpdump simultaneously

### ISSUE THREAD

**Issue by Echo-chu331** [xdp-project/xdp-tutorial#186]
Based on this tutorial: https://github.com/xdp-project/xdp-tutorial/tree/master/advanced03-AF_XDP
When I want to receive packets from a physical interface， I execute this command ：`./af_xdp_user -d eno1`   .  But I cannot receive any packets. 
At the same time, I execute this command ：`tcpdump -i eno1` 
I can get the packets！ Why do we need to execute `tcpdump` at the same time？ What did I do wrong?

**Comment by chaudron** [comment]
XDP only received packets that would normally be accepted by the NIC. So only broadcast/multicast packets and packets with the destined MAC of the NIC. If you start tcpdump promiscuous mode is enabled, so all packets on the wire will be forwarded. 

Knowing the above you should see packets in XDP which are not destined for your host.

In addition, also make sure the packets arrive on the right queue. To make sure all are received on queue 1, use the 'ethtool -L <interface> combined 1' command.
