### ISSUE TITLE
about bpf_map share

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#189]
Whether a bpf_map can be shared between xdp programs ?

For example:
There is a define of xdp_stats_map  in  lesson basic03-map-counter.

When I load the xdp_prog_kern.o on two nics, if I can get the two nic rx_packets info from xdp_stats_map on userspace ?

**Comment by tohojo** [comment]
glennWang <notifications@github.com> writes:

> Whether a bpf_map can be shared between xdp programs ?

Yes - you can reuse a map by using bpf_map__reuse_fd() in libbpf.

> For example:
> There is a define of xdp_stats_map  in  lesson basic03-map-counter.
>
> When I load the xdp_prog_kern.o on two nics, if I can get the two nic
> rx_packets info from xdp_stats_map on userspace ?

That's different from reusing the map, though; you'd probably want to
still have two separate maps for each interface, and just have your
userspace program read both of them. That is certainly also possible,
just have the two maps pinned in two different places and make your
userspace program open and read both...
