### ISSUE TITLE
Question about checking if IPv6 falls into certain prefix?

### ISSUE THREAD

**Issue by PolynomialDivision** [xdp-project/xdp-tutorial#190]
Since, memcmp is not available, how do you check if an ipv6 falls into a certain prefix?
Actually, I wanted to do something like this:
https://github.com/openwrt/openwrt/blob/master/package/network/utils/owipcalc/src/owipcalc.c#L528-L551

**Comment by tohojo** [comment]
Polynomdivision <notifications@github.com> writes:

> Since, memcmp is not available, how do you check if an ipv6 falls into
> a certain prefix?

Well either you can do manual byte-per-byte comparisons (or cast to
larger data types and compare those for added efficiency), or you use
__builtin_memcmp() :)

**Comment by PolynomialDivision** [comment]
I already tried `__builtin_memcmp` but I think it is not available in 5.4er kernel? :/
I was tired yesterday after trying several things. Let's see if I can find a working solution, today. :)

We are working on some tutorial for the OpenWrt Community. I will keep u updated.

**Comment by tohojo** [comment]
__builtin_memcmp is an LLVM feature...

**Comment by PolynomialDivision** [comment]
I always have issues with the verifier. :/
Not even that simple function works:

```cpp
static __always_inline int check(struct cidr *a, struct in6_addr ip) {

	u_int8_t i = 15 - (128 - a->prefix) / 8;

	if (i >= 16)
		return 1;
	
	if (i < 0)
		return 0;

	if ((sizeof(a->addr.v6.s6_addr)/sizeof(a->addr.v6.s6_addr[0])) < 16)
		return 0;

	if ((sizeof(ip.s6_addr)/sizeof(ip.s6_addr[0])) < 16)
		return 0;

	uint8_t net1 = a->addr.v6.s6_addr[i];
	uint8_t net2 = ip.s6_addr[i];

	if (net1 == net2)
	{
		return 1;
	}
	return 0;
}
```
It fails with:

    variable stack access var_off=(0x0; 0xf) off=-16 size=1
    
https://github.com/PolynomialDivision/xdp-srv6-remover/blob/master/src/srv6_kern.c#L21-L39

**Comment by PolynomialDivision** [comment]
I think I finally have a working solution that the verifier accepts. :)
https://github.com/PolynomialDivision/xdp-srv6-remover/blob/master/src/srv6_kern.c#L61-L98 (not tested in xdp but in another c programm)

**Comment by PolynomialDivision** [comment]
It seems to work! :)
