### ISSUE TITLE
Does there has a plan to support BPF CO-RE？

### ISSUE THREAD

**Issue by woodliu** [xdp-project/xdp-tutorial#192]

**Comment by tohojo** [comment]
What do you mean, exactly?

**Comment by woodliu** [comment]
> What do you mean, exactly?

Make some tutorials that Use of [BPF CO-RE](https://github.com/libbpf/libbpf#bpf-co-re-compile-once--run-everywhere).

**Comment by tohojo** [comment]
charlie <notifications@github.com> writes:

>> What do you mean, exactly?
>
> Make some tutorials that Use of [BPF
> CO-RE](https://github.com/libbpf/libbpf#bpf-co-re-compile-once--run-everywhere).

Hmm, no concrete plans for that, no... Feel free to contribute some :)

**Comment by woodliu** [comment]
> charlie <notifications@github.com> writes:
> > What do you mean, exactly? Make some tutorials that Use of [BPF CO-RE](https://github.com/libbpf/libbpf#bpf-co-re-compile-once--run-everywhere).
> Hmm, no concrete plans for that, no... Feel free to contribute some :)

Hi，i am trying to use BPF CO-RE, but i face a problem with loading BPF prog.  I have no idea to figure it out, could you help me ?
Here is the code 
```
/* Copyright (c) 2017 Covalent IO, Inc. http://covalent.io
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of version 2 of the GNU General Public
 * License as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 */
#define KBUILD_MODNAME "foo"
#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

#define ETH_ALEN	6		/* Octets in one ethernet addr	 */

#ifndef memcpy
#define memcpy(dest, src, n) __builtin_memcpy((dest), (src), (n))
#endif

struct {
	__uint(type, BPF_MAP_TYPE_DEVMAP);
	__uint(key_size, sizeof(int));
	__uint(value_size, sizeof(int));
	__uint(max_entries, 100);
} tx_port SEC(".maps");

struct bpf_map_def SEC("maps") redirect_params = {
	.type = BPF_MAP_TYPE_HASH,
	.key_size = ETH_ALEN,
	.value_size = ETH_ALEN,
	.max_entries = 1,
};

/* Count RX packets, as XDP bpf_prog doesn't get direct TX-success
 * feedback.  Redirect TX errors can be caught via a tracepoint.
 */
struct {
	__uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
	__type(key, u32);
	__type(value, long);
	__uint(max_entries, 1);
} rxcnt SEC(".maps");

#define VLAN_MAX_DEPTH 10
struct hdr_cursor {
	void *pos;
};

static __always_inline int parse_ethhdr(struct hdr_cursor *nh, void *data_end,
					struct ethhdr **ethhdr)
{
	struct ethhdr *eth = nh->pos;
	int hdrsize = sizeof(*eth);
	struct vlan_hdr *vlh;
	__u16 h_proto;
	int i;

	/* Byte-count bounds check; check if current pointer + size of header
	 * is after data_end.
	 */
	if (nh->pos + hdrsize > data_end)
		return -1;

	nh->pos += hdrsize;
	*ethhdr = eth;
	vlh = nh->pos;
	h_proto = eth->h_proto;

	/* Use loop unrolling to avoid the verifier restriction on loops;
	 * support up to VLAN_MAX_DEPTH layers of VLAN encapsulation.
	 */
	
	// for (i = 0; i < VLAN_MAX_DEPTH; i++) {
	// 	if (!proto_is_vlan(h_proto))
	// 		break;

	// 	if (vlh + 1 > data_end)
	// 		break;

	// 	h_proto = vlh->h_vlan_encapsulated_proto;
	// 	vlh++;
	// }

	nh->pos = vlh;
	return h_proto; /* network-byte-order */
}

SEC("xdp_devmap/xdp_redirect_map")
int xdp_redirect_map_prog(struct xdp_md *ctx)
{
	void *data_end = (void *)(long)ctx->data_end;
	void *data = (void *)(long)ctx->data;
	struct ethhdr *eth = data;
	int rc = XDP_DROP;
	int vport, port = 0, m = 0;
	long *value;
	u32 key = 0;
	u64 nh_off;
	struct hdr_cursor nh;
	int eth_type;
	unsigned char *dst;

	nh_off = sizeof(*eth);
	if (data + nh_off > data_end)
		return rc;

	/* constant virtual port */
	vport = 0;

	/* count packet in global counter */
	value = bpf_map_lookup_elem(&rxcnt, &key);
	if (value)
		*value += 1;

	/* Parse Ethernet and IP/IPv6 headers */
	eth_type = parse_ethhdr(&nh, data_end, &eth);
	if (eth_type == -1)
		return rc;

	dst = bpf_map_lookup_elem(&redirect_params, eth->h_source);
	if (!dst)
		return rc;

	memcpy(eth->h_dest,dst,ETH_ALEN);

	/* send packet out physical port */
	return bpf_redirect_map(&tx_port, vport, 0);
}

/* Redirect require an XDP bpf_prog loaded on the TX device */
SEC("xdp_redirect_dummy")
int xdp_redirect_dummy_prog(struct xdp_md *ctx)
{
	return XDP_PASS;
}

char _license[] SEC("license") = "GPL";

```
The problem is when `dst = bpf_map_lookup_elem(&redirect_params, eth->h_source);`, it return error.
 Here is the stack:
```
libbpf: load bpf program failed: Permission denied
libbpf: -- BEGIN DUMP LOG ---
libbpf:
; void *data_end = (void *)(long)ctx->data_end;
0: (61) r2 = *(u32 *)(r1 +4)
; void *data = (void *)(long)ctx->data;
1: (61) r1 = *(u32 *)(r1 +0)
2: (b7) r3 = 0
; u32 key = 0;
3: (63) *(u32 *)(r10 -4) = r3
last_idx 3 first_idx 0
regs=8 stack=0 before 2: (b7) r3 = 0
4: (b7) r6 = 1
; if (data + nh_off > data_end)
5: (07) r1 += 14
; if (data + nh_off > data_end)
6: (2d) if r1 > r2 goto pc+31
 R1_w=pkt(id=0,off=14,r=14,imm=0) R2_w=pkt_end(id=0,off=0,imm=0) R3_w=invP0 R6_w=inv1 R10=fp0 fp-8=0000????
7: (bf) r2 = r10
;
8: (07) r2 += -4
; value = bpf_map_lookup_elem(&rxcnt, &key);
9: (18) r1 = 0xffff8c43f34f3e00
11: (85) call bpf_map_lookup_elem#1
; if (value)
12: (15) if r0 == 0x0 goto pc+3
 R0=map_value(id=0,off=0,ks=4,vs=8,imm=0) R6=inv1 R10=fp0 fp-8=mmmm????
; *value += 1;
13: (79) r1 = *(u64 *)(r0 +0)
 R0=map_value(id=0,off=0,ks=4,vs=8,imm=0) R6=inv1 R10=fp0 fp-8=mmmm????
14: (07) r1 += 1
15: (7b) *(u64 *)(r0 +0) = r1
 R0=map_value(id=0,off=0,ks=4,vs=8,imm=0) R1_w=inv(id=0) R6=inv1 R10=fp0 fp-8=mmmm????
; dst = bpf_map_lookup_elem(&redirect_params, eth->h_source);
16: (18) r1 = 0xffff8c439f431800
18: (85) call bpf_map_lookup_elem#1
R2 !read_ok
processed 17 insns (limit 1000000) max_states_per_insn 0 total_states 1 peak_states 1 mark_read 1

libbpf: -- END LOG --
libbpf: failed to load program 'xdp_redirect_map_prog'
libbpf: failed to load object 'xdp_redirect_map_bpf'
libbpf: failed to load BPF skeleton 'xdp_redirect_map_bpf': -4007
xdp_redirect_map_bpf__open_and_load: Permission denied
```

Could you give me some help? thank you!

**Comment by tohojo** [comment]
charlie <notifications@github.com> writes:

>> charlie <notifications@github.com> writes:
>> > What do you mean, exactly? Make some tutorials that Use of [BPF CO-RE](https://github.com/libbpf/libbpf#bpf-co-re-compile-once--run-everywhere).
>> Hmm, no concrete plans for that, no... Feel free to contribute some :)
>
> Hi，i am trying to use BPF CO-RE, but i face a problem with loading
> BPF prog.  I have no idea to figure it out, could you help me ?


> 	dst = bpf_map_lookup_elem(&redirect_params, eth->h_source);

it's complaining about this line; you're supposed to pass a pointer to
the key, not the value; so it's just complaining about an invalid
pointer.

Not sure if it'll allow you to use the packet data directly for a lookup
like this either; you may need to copy the data to a stack variable
first.

(This has nothing to do with CO-RE, BTW; it's just regular BPF verifier
behaviour :))

**Comment by woodliu** [comment]
> charlie <notifications@github.com> writes:
> > charlie ***@***.***> writes: > > What do you mean, exactly? Make some tutorials that Use of [BPF CO-RE](https://github.com/libbpf/libbpf#bpf-co-re-compile-once--run-everywhere). > Hmm, no concrete plans for that, no... Feel free to contribute some :) Hi，i am trying to use BPF CO-RE, but i face a problem with loading BPF prog. I have no idea to figure it out, could you help me ? dst = bpf_map_lookup_elem(&redirect_params, eth->h_source);
> it's complaining about this line; you're supposed to pass a pointer to the key, not the value; so it's just complaining about an invalid pointer. Not sure if it'll allow you to use the packet data directly for a lookup like this either; you may need to copy the data to a stack variable first. (This has nothing to do with CO-RE, BTW; it's just regular BPF verifier behaviour :))

Thank you for the reply. I will try to fix that with your advice. I think the only difference between BCC and CO-RE just the way when coding. And i found that ,when use XDP, it is not that ease to work with CO-RE, because you need to switch the network namespace...

**Comment by woodliu** [comment]
> > charlie [notifications@github.com](mailto:notifications@github.com) writes:
> > > charlie _**@**_.***> writes: > > What do you mean, exactly? Make some tutorials that Use of [BPF CO-RE](https://github.com/libbpf/libbpf#bpf-co-re-compile-once--run-everywhere). > Hmm, no concrete plans for that, no... Feel free to contribute some :) Hi，i am trying to use BPF CO-RE, but i face a problem with loading BPF prog. I have no idea to figure it out, could you help me ? dst = bpf_map_lookup_elem(&redirect_params, eth->h_source);
> > > it's complaining about this line; you're supposed to pass a pointer to the key, not the value; so it's just complaining about an invalid pointer. Not sure if it'll allow you to use the packet data directly for a lookup like this either; you may need to copy the data to a stack variable first. (This has nothing to do with CO-RE, BTW; it's just regular BPF verifier behaviour :))
> 
> Thank you for the reply. I will try to fix that with your advice. I think the only difference between BCC and CO-RE just the way when coding. And i found that ,when use XDP, it is not that ease to work with CO-RE, because you need to switch the network namespace...

And i do that just follow the way of [XDP-tuorial](https://github.com/woodliu/xdp-tutorial/blob/master/packet-solutions/xdp_prog_kern_03.c#L202)

**Comment by woodliu** [comment]
@tohojo I found the reason is that it not support get value like BCC(eth->h_source), should use BPF_CORE_READ instead.
