### ISSUE TITLE
XDP_REDIRECT - iperf3 TCP test shows high retransmission and low throughput

### ISSUE THREAD

**Issue by nsaeris** [xdp-project/xdp-tutorial#193]
I have a simple packet router (MyRouter) written using XDP. The program reads IP frames off one interface (net1/vlan1), update the destination mac address and redirect the updated frame to another interface (net2/vlan2). The XDP program attaches in xdpgeneric mode. It is running on Ubuntu 20.04 on VMware.

I have a test setup that looks like following
(Raspberrry Pi) -> MyRouter -> GCM VM

When I run iPerf3 from Pi hitting the server on GCP VM, I see high number of retransmission and low throughput.
`
pi@raspberrypi:~ $ iperf3 -c <GCP VM IP> -p 1883
Connecting to host <GCP VM IP>, port 1883
[  5] local <Pi IP> port 60544 connected to <GCP VM IP> port 1883
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   230 KBytes  1.88 Mbits/sec   40   2.67 KBytes
[  5]   1.00-2.00   sec  96.2 KBytes   788 Kbits/sec   23   2.67 KBytes
[  5]   2.00-3.00   sec  72.1 KBytes   591 Kbits/sec   18   2.67 KBytes
[  5]   3.00-4.00   sec   144 KBytes  1.18 Mbits/sec   22   6.68 KBytes
[  5]   4.00-5.00   sec   120 KBytes   985 Kbits/sec   23   4.01 KBytes
[  5]   5.00-6.00   sec   152 KBytes  1.25 Mbits/sec   24   2.67 KBytes
[  5]   6.00-7.00   sec  72.1 KBytes   591 Kbits/sec   18   2.67 KBytes
[  5]   7.00-8.00   sec   120 KBytes   985 Kbits/sec   20   2.67 KBytes
[  5]   8.00-9.00   sec  96.2 KBytes   788 Kbits/sec   17   2.67 KBytes
[  5]   9.00-10.00  sec  72.1 KBytes   591 Kbits/sec   18   2.67 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.15 MBytes   963 Kbits/sec  223             sender
[  5]   0.00-10.01  sec  1.11 MBytes   927 Kbits/sec                  receiver

iperf Done.
`

To rule out GCP or Internet routing issue, I ran the server in the same network (lan) and observed the same results.

Replacing the XDP program with vanilla linux IP forwarding (net.ipv4.ip_forward), the same test shows high throughput.
`
pi@raspberrypi:~ $ iperf3 -c <GCP VM IP> -p 1883
Connecting to host <GCP VM IP>, port 1883
[  5] local <Pi IP> port 60180 connected to <GCP VM IP> port 1883
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  33.0 MBytes   277 Mbits/sec    0    994 KBytes
[  5]   1.00-2.00   sec  33.8 MBytes   283 Mbits/sec    0    994 KBytes
[  5]   2.00-3.00   sec  34.8 MBytes   292 Mbits/sec    0    994 KBytes
[  5]   3.00-4.00   sec  33.7 MBytes   283 Mbits/sec    0    994 KBytes
[  5]   4.00-5.00   sec  33.8 MBytes   283 Mbits/sec    0    994 KBytes
[  5]   5.00-6.00   sec  33.8 MBytes   283 Mbits/sec    0    994 KBytes
[  5]   6.00-7.00   sec  33.7 MBytes   283 Mbits/sec    0    994 KBytes
[  5]   7.00-8.00   sec  34.7 MBytes   291 Mbits/sec    0    994 KBytes
[  5]   8.00-9.00   sec  33.7 MBytes   283 Mbits/sec    0    994 KBytes
[  5]   9.00-10.00  sec  34.3 MBytes   288 Mbits/sec    0   1.02 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   339 MBytes   285 Mbits/sec    0             sender
[  5]   0.00-10.03  sec   337 MBytes   282 Mbits/sec                  receiver

iperf Done.
`

I ran iperf3 with -u (udp) option and iperf3 reported same through for both XDP and Linux IP forwarding. This confirms the issue is specific to TCP.

I looked at issue (https://github.com/xdp-project/xdp-tutorial/issues/160). I tried updating the checksum in the XDP code but no improvement was observed. 

Any pointer or suggestions on troubleshooting and isolating this issue further?

**Comment by tohojo** [comment]
nsaeris <notifications@github.com> writes:

> Any pointer or suggestions on troubleshooting and isolating this issue
> further?

There's xdp_monitor (from samples/bpf in the kernel tree) that can show
you what return codes are being returned from XDP and whether there are
any errors. You can also look at ethtool statistics and see if there's
anything there. Finally, try dumping the packets post-REDIRECT (i.e.,
from the next hop machine, or using xdpdump) and looking at the flows in
Wireshark to see if there are any checksum errors or things like that...

**Comment by williamtu** [comment]
what if you tried disable TSO at the TCP sender side?
usually TSO is enabled and large-size packet is sent out, and XDP has to drop it.

**Comment by nsaeris** [comment]
Thank you for your inputs.

Here is some additional details I captured today. I think I am closer to understand the issue.

```
ip link
———

3: ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:50:56:82:ea:ca brd ff:ff:ff:ff:ff:ff
    altname enp19s0

4: ens224.3554@ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 xdpgeneric qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:50:56:82:ea:ca brd ff:ff:ff:ff:ff:ff
    prog/xdp id 71

5: ens224.3553@ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 xdpgeneric qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:50:56:82:ea:ca brd ff:ff:ff:ff:ff:ff
    prog/xdp id 72
```

ens224 is trunked port. ens224.3554 is vlan link for vlan 3554 and ens224.3553 is for vlan 3553. I have 2 instances of router. One moving packets from ens224.3554 to ens224.3553, and other moving from ens224.3553 to ens224.3554. The code is same but the next hop (mac) is different in the 2 directions.

Compiled and ran xdpdump
```
$ sudo ./xdpdump -D
Interface        Prio  Program name      Mode     ID   Tag               Chain actions
--------------------------------------------------------------------------------------
lo                     <No XDP program loaded!>
ens160                 <No XDP program loaded!>
ens224                 <No XDP program loaded!>
ens224.3554            xdp_router        skb      71   0fd1290ce9c75b7c
ens224.3553            xdp_router        skb      72   0fd1290ce9c75b7c
docker0                <No XDP program loaded!>
```

Used ethtool to set tso off

```
$ sudo ethtool -K ens224.3554 tso on
Actual changes:
tx-tcp-segmentation: on
tx-tcp-ecn-segmentation: on
tx-tcp-mangleid-segmentation: on
tx-tcp6-segmentation: on

$ sudo ethtool -K ens224.3553 tso on
Actual changes:
tx-tcp-segmentation: on
tx-tcp-ecn-segmentation: on
tx-tcp-mangleid-segmentation: on
tx-tcp6-segmentation: on

$ sudo ethtool -K ens224 tso on
Actual changes:
tx-tcp-ecn-segmentation: off [requested on]
tx-tcp-mangleid-segmentation: on

$ sudo ethtool -K ens224 tso off
Actual changes:
tx-tcp-segmentation: off
tx-tcp-mangleid-segmentation: off
tx-tcp6-segmentation: off

$ sudo ethtool -K ens224.3553 tso off
Actual changes:
tx-tcp-segmentation: off
tx-tcp-ecn-segmentation: off
tx-tcp-mangleid-segmentation: off
tx-tcp6-segmentation: off

$ sudo ethtool -K ens224.3554 tso off
Actual changes:
tx-tcp-segmentation: off
tx-tcp-ecn-segmentation: off
tx-tcp-mangleid-segmentation: off
tx-tcp6-segmentation: off
```

Cannot get stats for the vlan links
```
$ sudo ethtool -S ens224.3554
no stats available
$ sudo ethtool -S ens224.3553
no stats available
```

I ran ethtool -S before and after running iperf for 1 second. Following are the counts. The number after / is the output captured after the test and the number in [] is the difference. The delta reported is low indicating the low throughput I am seeing.
```
$ sudo ethtool -S ens224
NIC statistics:
     Tx Queue#: 0
       TSO pkts tx: 0
       TSO bytes tx: 0
       ucast pkts tx: 430 / 449 [19]
       ucast bytes tx: 205998 / 207708
       mcast pkts tx: 10
       mcast bytes tx: 900
       bcast pkts tx: 2
       bcast bytes tx: 84
       pkts tx err: 0
       pkts tx discard: 0
       drv dropped tx total: 0
          too many frags: 0
          giant hdr: 0
          hdr err: 0
          tso: 0
       ring full: 0
       pkts linearized: 0
       hdr cloned: 0
       giant hdr: 0
     Tx Queue#: 1
       TSO pkts tx: 0
       TSO bytes tx: 0
       ucast pkts tx: 806
       ucast bytes tx: 1076393
       mcast pkts tx: 30
       mcast bytes tx: 4200
       bcast pkts tx: 3
       bcast bytes tx: 1044
       pkts tx err: 0
       pkts tx discard: 0
       drv dropped tx total: 0
          too many frags: 0
          giant hdr: 0
          hdr err: 0
          tso: 0
       ring full: 0
       pkts linearized: 0
       hdr cloned: 0
       giant hdr: 0
     Tx Queue#: 2
       TSO pkts tx: 0
       TSO bytes tx: 0
       ucast pkts tx: 307 / 323 [16]
       ucast bytes tx: 25025 / 26366
       mcast pkts tx: 88
       mcast bytes tx: 6176
       bcast pkts tx: 0
       bcast bytes tx: 0
       pkts tx err: 0
       pkts tx discard: 0
       drv dropped tx total: 0
          too many frags: 0
          giant hdr: 0
          hdr err: 0
          tso: 0
       ring full: 0
       pkts linearized: 0
       hdr cloned: 0
       giant hdr: 0
     Tx Queue#: 3
       TSO pkts tx: 0
       TSO bytes tx: 0
       ucast pkts tx: 277 / 569 [292]
       ucast bytes tx: 125867 / 409834
       mcast pkts tx: 5667 / 5859
       mcast bytes tx: 497910 / 514806
       bcast pkts tx: 3
       bcast bytes tx: 744
       pkts tx err: 0
       pkts tx discard: 0
       drv dropped tx total: 0
          too many frags: 0
          giant hdr: 0
          hdr err: 0
          tso: 0
       ring full: 0
       pkts linearized: 0
       hdr cloned: 0
       giant hdr: 0
     Rx Queue#: 0
       LRO pkts rx: 0
       LRO byte rx: 0
       ucast pkts rx: 1693 / 1699 [6]
       ucast bytes rx: 1775130 / 1775504
       mcast pkts rx: 11951 / 12368
       mcast bytes rx: 1104342 / 1142368
       bcast pkts rx: 111 / 568
       bcast bytes rx: 6660 / 40216
       pkts rx OOB: 0
       pkts rx err: 0
       drv dropped rx total: 0
          err: 0
          fcs: 0
       rx buf alloc fail: 0
     Rx Queue#: 1
       LRO pkts rx: 0
       LRO byte rx: 0
       ucast pkts rx: 443 / 1000 [557]
       ucast bytes rx: 326851 / 378683
       mcast pkts rx: 8150 / 8459
       mcast bytes rx: 722676 / 749862
       bcast pkts rx: 0
       bcast bytes rx: 0
       pkts rx OOB: 0
       pkts rx err: 0
       drv dropped rx total: 0
          err: 0
          fcs: 0
       rx buf alloc fail: 0
     Rx Queue#: 2
       LRO pkts rx: 0
       LRO byte rx: 0
       ucast pkts rx: 751 / 827 [76]
       ucast bytes rx: 800993 / 809583
       mcast pkts rx: 3807 / 3969
       mcast bytes rx: 449902 / 466970
       bcast pkts rx: 12
       bcast bytes rx: 4592
       pkts rx OOB: 0
       pkts rx err: 0
       drv dropped rx total: 0
          err: 0
          fcs: 0
       rx buf alloc fail: 0
     Rx Queue#: 3
       LRO pkts rx: 0
       LRO byte rx: 0
       ucast pkts rx: 241 / 1901 [1660]
       ucast bytes rx: 247452 / 1284095
       mcast pkts rx: 3817 / 3994
       mcast bytes rx: 451838 / 470176
       bcast pkts rx: 0
       bcast bytes rx: 0
       pkts rx OOB: 0
       pkts rx err: 0
       drv dropped rx total: 0
          err: 0
          fcs: 0
       rx buf alloc fail: 0
     tx timeout count: 0
```

I captured the xdpdump on ens224.3554 and ens224.3554 
```
sudo ./xdpdump --rx-capture entry,exit -i ens224.3553 -w ens224.3553.pcap
sudo ./xdpdump --rx-capture entry,exit -i ens224.3554 -w ens224.3554.pcap
```

I don't see any incorrect checksum errors but I do see retransmission and duplicate acks, which I have been seeing in regular tcpdump as well....indicating either latency or packet loss.

I then loaded xdp-filter on the parent interface (ens224) to gather some additional stats. I could not load xdp-filter on end224.3554 or ens224.3553. The filter was setup to allow all.

When I add xdp-filter on the parent interface, my iperf test is successful. I can see the packets flowing through my router.

```
$ sudo ./xdp-filter load ens224 -m skb
```

Stats before the test:
```
$ sudo ./xdp-filter status
CURRENT XDP-FILTER STATUS:

Aggregate per-action statistics:
  XDP_ABORTED                                   0 pkts           0 KiB
  XDP_DROP                                      0 pkts           0 KiB
  XDP_PASS                                    172 pkts          16 KiB

Loaded on interfaces:
                                           Enabled features
xdpfilt_alw_all
  ens224 (skb mode)                        tcp,udp,ipv6,ipv4,ethernet,allow

Filtered ports:
                                           Mode             Hit counter

Filtered IP addresses:
                                           Mode             Hit counter

Filtered MAC addresses:
                                           Mode             Hit counter

$
```

My router metrics (3554/UP)
```
# TYPE packet_count_by_action_total counter
packet_count_by_action_total{action="1",direction="UP",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 0.0
packet_count_by_action_total{action="2",direction="UP",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 0.0
packet_count_by_action_total{action="3",direction="UP",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 196.0
packet_count_by_action_total{action="4",direction="UP",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 0.0
packet_count_by_action_total{action="5",direction="UP",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 0.0
# TYPE packet_count_by_protocol_total counter
packet_count_by_protocol_total{direction="UP",protocol="89",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 196.0
```

My router metrics (3553/DOWN)
```
# TYPE packet_count_by_action_total counter
packet_count_by_action_total{action="1",direction="DOWN",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 0.0
packet_count_by_action_total{action="2",direction="DOWN",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 0.0
packet_count_by_action_total{action="3",direction="DOWN",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 752.0
packet_count_by_action_total{action="4",direction="DOWN",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 0.0
packet_count_by_action_total{action="5",direction="DOWN",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 0.0
# TYPE packet_count_by_protocol_total counter
packet_count_by_protocol_total{direction="DOWN",protocol="89",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 752.0
$
```
Stats after the iperf test

```
$ sudo ./xdp-filter status
CURRENT XDP-FILTER STATUS:

Aggregate per-action statistics:
  XDP_ABORTED                                   0 pkts           0 KiB
  XDP_DROP                                      0 pkts           0 KiB
  XDP_PASS                                 219008 pkts      252444 KiB

Loaded on interfaces:
                                           Enabled features
xdpfilt_alw_all
  ens224 (skb mode)                        tcp,udp,ipv6,ipv4,ethernet,allow

Filtered ports:
                                           Mode             Hit counter

Filtered IP addresses:
                                           Mode             Hit counter

Filtered MAC addresses:
                                           Mode             Hit counter

$
```

Router up
```
# TYPE packet_count_by_action_total counter
packet_count_by_action_total{action="1",direction="UP",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 0.0
packet_count_by_action_total{action="2",direction="UP",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 0.0
packet_count_by_action_total{action="3",direction="UP",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 508.0
packet_count_by_action_total{action="4",direction="UP",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 0.0
packet_count_by_action_total{action="5",direction="UP",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 178367.0
# TYPE packet_count_by_protocol_total counter
packet_count_by_protocol_total{direction="UP",protocol="89",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 508.0
packet_count_by_protocol_total{direction="UP",protocol="6",routerId="d290ac2d-179a-41d4-bef2-679c0cb42f08"} 178367.0
```

Router down
```
# TYPE packet_count_by_action_total counter
packet_count_by_action_total{action="1",direction="DOWN",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 0.0
packet_count_by_action_total{action="2",direction="DOWN",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 0.0
packet_count_by_action_total{action="3",direction="DOWN",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 1386.0
packet_count_by_action_total{action="4",direction="DOWN",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 0.0
packet_count_by_action_total{action="5",direction="DOWN",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 38550.0
# TYPE packet_count_by_protocol_total counter
packet_count_by_protocol_total{direction="DOWN",protocol="6",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 38550.0
packet_count_by_protocol_total{direction="DOWN",protocol="89",routerId="03950f39-6a5d-4286-9ba9-4848e30bf4cb"} 1386.0
$
```

With xdp-filter, I tried enabling/disabling tso and it had no impact.

Now trying to chase why adding xdp-filter changed the traffic flow. I am looking into its code now but wanted to capture this before so that I don't loose this. 

Any pointers are certainly welcome.

**Comment by nsaeris** [comment]
Eventually I concluded that GSO (Generic Segmentation Offload) and GRO (Generic Receive Offload) was contributing to the issue I was seeing. I had to turn them off.

Here is good read if someone is interested: https://lwn.net/Articles/358910/

Also, came across following that is relevant to xdp generic. I don't see the change in the 5.8 kernel version I am using.
https://lkml.org/lkml/2020/2/28/299
