### ISSUE TITLE
How to use rcu_read_lock/rcu_read_unlock in eBPF/xdp program ?

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#203]
https://github.com/torvalds/linux/blob/master/kernel/bpf/helpers.c#L24

According to the link above. If the bpf_hash_map would be updated/deleted frequently on user space, I think the xdp program would have the following code to protect the map.

And then, how can I use rcu_read_lock/rcu_read_unlock in eBPF/xdp program ?

```
rcu_read_lock();

struct T *xx = bpf_map_lookup_elem(xx, xx);

/*
* do something...
* ...
*/

rcu_read_unlock();
```

**Comment by tohojo** [comment]
glennWang ***@***.***> writes:

> https://github.com/torvalds/linux/blob/master/kernel/bpf/helpers.c#L24
>
> According to the link above. If the bpf_hash_map would be updated
> frequently on user space, I think the xdp program would have the
> following code to protect the map.
>
> And then, how can I use rcu_read_lock/rcu_read_unlock in eBPF/xdp
> program ?

No, you don't need to do anything like that, the kernel makes sure the
objects stick around for the lifetime of the BPF program execution...

**Comment by glennWang** [comment]
Let me explain my scene.

In XDP program, as the following
```
struct datarec {
	__u64 rx_packets;
	__u64 rx_bytes;
};

struct datarec *val = bpf_map_lookup_elem(&hash_map, &key);
if (val) {
    	val->rx_packets++;
}
```

If my code on user space is as the following:
```
bpf_map_delete_elem(hash_map_fd, key)
```

As the kernel source code and called order, I can not see mechanism to protect in the call progress of bpf_map_lookup_elem() in eBPF/xdp  (Maybe I missed it).  
To call bpf_map_lookup_elem() on user space is ok, because of RCU lock.

May be when the interface receives a large number of packets, deleting the key on user space may lead to the reference of null pointer in xdp program.

https://github.com/torvalds/linux/blob/master/kernel/bpf/helpers.c#L29

https://github.com/torvalds/linux/blob/master/kernel/bpf/hashtab.c#L612

**Comment by tohojo** [comment]
Did you actually try writing such a program? The verifier will reject it if you don't check the return value from bpf_map_lookup_elem() before dereferencing the pointer. But this has nothing to do with RCU; that is about ensuring the object doesn't go away after you've loaded it from the map - which the kernel also takes care of for you...

**Comment by glennWang** [comment]
> Did you actually try writing such a program? 

Yes , I had writen such a program with checking the return value, and that is runing ok.

> that is about ensuring the object doesn't go away after you've loaded it from the map - which the kernel also takes care of for you

What puzzles me is that when I check the return pointer value is ok. But when I reference the pointer, the memory point by the pointer is freed by calling `bpf_map_delete_elem()` on user space runing on another cpu core.


I want to know the kernel how to take care of the situation. Could you introduce some doc or kernel source code.

**Comment by tohojo** [comment]
glennWang ***@***.***> writes:

>> Did you actually try writing such a program? 
>
> Yes , I had writen such a program with checking the return value, and
> that is runing ok.
>
>> that is about ensuring the object doesn't go away after you've loaded
>> it from the map - which the kernel also takes care of for you
>
> What puzzles me is that when I check the return pointer value is ok.
> But when I reference the pointer, the memory point by the pointer is
> freed by calling `bpf_map_delete_elem()` on user space runing on
> another cpu core.
>
> I want to know the kernel how to take care of the situation. Could you
> introduce some doc or kernel source code.

At the risk of repeating myself for the third time, the kernel takes
care of that for you, so you don't need to do anything in your BPF
program. See the comment in bpf_prog_run_xdp():

https://elixir.bootlin.com/linux/latest/source/include/linux/filter.h#L734

**Comment by glennWang** [comment]
> glennWang ***@***.***> writes:
> > Did you actually try writing such a program? Yes , I had writen such a program with checking the return value, and that is runing ok. > that is about ensuring the object doesn't go away after you've loaded > it from the map - which the kernel also takes care of for you What puzzles me is that when I check the return pointer value is ok. But when I reference the pointer, the memory point by the pointer is freed by calling `bpf_map_delete_elem()` on user space runing on another cpu core. I want to know the kernel how to take care of the situation. Could you introduce some doc or kernel source code.
> At the risk of repeating myself for the third time, the kernel takes care of that for you, so you don't need to do anything in your BPF program. See the comment in bpf_prog_run_xdp(): https://elixir.bootlin.com/linux/latest/source/include/linux/filter.h#L734

@tohojo Under your prompt, I get the following link. And now, I have see. Thanks a lot for your patience answer.

https://patchwork.ozlabs.org/project/netdev/patch/b70c47e0284823e6a5db600ae75c01eac4cf7922.1480538565.git.daniel@iogearbox.net/

The xdp callers all have the code snippet like the following.  Such as https://github.com/torvalds/linux/blob/master/drivers/net/ethernet/intel/i40e/i40e_xsk.c#L156
```
rcu_read_lock();
...
act = bpf_prog_run_xdp(xdp_prog, xdp);
...
rcu_read_unlock();
```

Thank you very much again.
