### ISSUE TITLE
Epoch timestamps 

### ISSUE THREAD

**Issue by Echo-chu331** [xdp-project/xdp-tutorial#204]
[experiment01-tailgrow](https://github.com/xdp-project/xdp-tutorial/blob/master/experiment01-tailgrow/xdp_prog_kern.c) add timestamps in extended tailroom at XDP processing time. But `bpf_ktime_get_ns` or `bpf_ktime_get_boot_ns`  (in bpf-helpers) only can get the time since the system was booted(in nanoseconds). 

 u64 bpf_ktime_get_ns(void):

              Description
                     Return the time elapsed since system boot, in
                     nanoseconds.  Does not include time the system was
                     suspended.  See: clock_gettime(CLOCK_MONOTONIC)
              Return Current ktime.

 u64 bpf_ktime_get_boot_ns(void):

              Description
                     Return the time elapsed since system boot, in
                     nanoseconds.  Does include the time the system was
                     suspended.  See: clock_gettime(CLOCK_BOOTTIME)
              Return Current ktime.

I want to get the time in terms of nanoseconds since UNIX Epoch in kernel-space. Are there functions to get epoch-relative timestamps?

**Comment by chenhengqi** [comment]
I have a simple idea.

Pass `diff = epoch_time - boot_time` from user space to kernel space through a map, then you can calculate `epoch_time` by adding `diff` and `boot_time`.

**Comment by tohojo** [comment]
Hengqi Chen ***@***.***> writes:

> I have a simple idea.
>
> Pass `diff = epoch_time - boot_time` from user space to kernel space
> through a map, then you can calculate `epoch_time` by adding `diff`
> and `boot_time`.

Yeah, or just do insert the boot-time timestamp and do the calculation
afterwards when you're reading the timestamp?

(And no, there is no access to any of the wall time clocks from BPF; you
can only get the monotonic and boot time clocks that you already found)
