### ISSUE TITLE
af_xdp getting packets, none of the xdp action like drop, pass, redirect has taken place

### ISSUE THREAD

**Issue by Adarsh97** [xdp-project/xdp-tutorial#205]
I am currently working with af_xdp, seeing a scenario in which af_xdp socket getting packets, even though I want to drop them by using xdp. I have tried putting XDP_DROP, PASS in xdp but still packets I can see in af_xdp socket, what i am doing wrong here ?

I am working with this example https://github.com/xdp-project/xdp-tutorial/tree/master/advanced03-AF_XDP

**Comment by tohojo** [comment]
Ping @bjoto,  @magnus-karlsson

**Comment by magnus-karlsson** [comment]
It seems like the example uses the default XDP program and not the one the is supplied with the example. This line makes me believe that:

xsk_cfg.libbpf_flags = 0;

If you want to load your own program, you need to set this to:

xsk_cfg.libbpf_flags = XSK_LIBBPF_FLAGS__INHIBIT_PROG_LOAD;

and load the XDP program yourself.

**Comment by Adarsh97** [comment]
I have set xsk_cfg.libbpf_flag, now xdp kernel program it is taking, but xsks map is not getting updated, so bpf redirect map is failing, may I know the reason for it, should the user need to update the map ?

**Comment by magnus-karlsson** [comment]
When you set the XSK_LIBBPF_FLAGS__INHIBIT_PROG_LOAD flag, you have to do everything yourself when it comes to the XDP program, and this includes creating the xskmap and populating it with the sockets(s). In the Linux repo you can take a look at sample/bpf/xdpsock_user.c for an example. If the -M option is provided to that program, it will manage the xskmap itself.

/Magnus

**Comment by chaudron** [comment]
Hi All, I quickly tested the example as supplied by the tutorial and it works fine:

If you start it without the --file option it will use the build in program. However, if you would supply the --file name options like in the tutorial, it will load the XDP program, setup the tables, and now you will see that half of the packets are being responded to by the ping instead of all. 

```
sudo ./af_xdp_user -d veth-adv03 --filename af_xdp_kern.o
[ebuild:~/...al/advanced03-AF_XDP]$ sudo ./af_xdp_user -d veth-adv03 --filename af_xdp_kern.o
AF_XDP RX:            10 pkts (         5 pps)           1 Kbytes (     0 Mbits/s) period:2.000194
       TX:             0 pkts (         0 pps)           0 Kbytes (     0 Mbits/s) period:2.000194

AF_XDP RX:            20 pkts (         5 pps)           2 Kbytes (     0 Mbits/s) period:2.000133
       TX:             0 pkts (         0 pps)           0 Kbytes (     0 Mbits/s) period:2.000133

AF_XDP RX:            29 pkts (         4 pps)           3 Kbytes (     0 Mbits/s) period:2.000122
       TX:             0 pkts (         0 pps)           0 Kbytes (     0 Mbits/s) period:2.000122
```

```
$ t ping -- -i 0.1
Running ping from inside test environment:

PING fc00:dead:cafe:1::1(fc00:dead:cafe:1::1) 56 data bytes
64 bytes from fc00:dead:cafe:1::1: icmp_seq=2 ttl=64 time=0.017 ms
64 bytes from fc00:dead:cafe:1::1: icmp_seq=4 ttl=64 time=0.011 ms
64 bytes from fc00:dead:cafe:1::1: icmp_seq=6 ttl=64 time=0.011 ms
64 bytes from fc00:dead:cafe:1::1: icmp_seq=8 ttl=64 time=0.012 ms
64 bytes from fc00:dead:cafe:1::1: icmp_seq=10 ttl=64 time=0.011 ms
^C
--- fc00:dead:cafe:1::1 ping statistics ---
11 packets transmitted, 5 received, 54.5455% packet loss, time 1040ms
rtt min/avg/max/mdev = 0.011/0.012/0.017/0.002 ms
```

If you would change the example code from PASS to DROP you will see the packets being dropped:

```
$ git diff
diff --git a/advanced03-AF_XDP/af_xdp_kern.c b/advanced03-AF_XDP/af_xdp_kern.c
index 62d3687..a7c4855 100644
--- a/advanced03-AF_XDP/af_xdp_kern.c
+++ b/advanced03-AF_XDP/af_xdp_kern.c
@@ -29,7 +29,7 @@ int xdp_sock_prog(struct xdp_md *ctx)
 
         /* We pass every other packet */
         if ((*pkt_count)++ & 1)
-            return XDP_PASS;
+            return XDP_DROP;
     }
 
     /* A set entry here means that the corresponding queue_id
```

Is the advanced03-AF_XDP example working as it's supposed to on your setup?

**Comment by Adarsh97** [comment]
I have tried by populating socket entry in the xsks map from user space,  now it is working as expected. 
Thanks @magnus-karlsson 
@chaudron I haven't tried running the advanced03-AF_XDP example with --file option. 
Anyway by setting the flag, loading the kernel program and populating the xsks map the example working as expected. 
 Hence closing the issue. Thanks for all.
