### ISSUE TITLE
Could Two xdp program attached to different nic access the same BPF_HASH_MAP ?

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#213]
For example, xdp1 program is attached to the nic1, and xdp2 program is attached to the nic2 .

xdp1 and xdp2 share the same black ip list BPF_HASH_MAP .

Could this plan be supported ?

**Comment by tohojo** [comment]
glennWang ***@***.***> writes:

> For example, xdp1 program is attached to the nic1, and xdp2 program is attached to the nic2 .
>
> xdp1 and xdp2 share the same black list BPF_HASH_MAP .
>
> Could this plan be supported ?

Sure, that already works today. You can also attach the same XDP program
to multiple interfaces...

**Comment by glennWang** [comment]
>  Sure, that already works today. 

https://github.com/xdp-project/xdp-tutorial/tree/master/basic04-pinning-maps
I can confirm that different userspace program can access the same bpf map through the pinning as the above example.
But I has no idea about two xdp program how to share the same bpf map. Is anywhere some example ?

> You can also attach the same XDP program to multiple interfaces...

And if a xdp program (that has a bpf map) is attached to multiple interfaces, there will be multiple different bpf map. 
Is I am right?

**Comment by tohojo** [comment]
glennWang ***@***.***> writes:

>>  Sure, that already works today. 
>
> https://github.com/xdp-project/xdp-tutorial/tree/master/basic04-pinning-maps
> I can confirm that different userspace program can access the same bpf map through the pinning as the above example.
> But I has no idea about two xdp program how to share the same bpf map. Is anywhere some example ?

If you just put two programs into the same source file (in different
sections) they can directly refer to the same map definition and
everything will happen automatically if you load the file with libbpf.
If they are in different files, or loaded separately, you'll have to
convince libbpf to reuse maps between the separate loads, which is what
assignment two in that basic04 lesson you linked above is about.

>> You can also attach the same XDP program to multiple interfaces...
>
> And if a xdp program (that has a bpf map) is attached to multiple
> interfaces, there will be multiple different bpf map. Is I am right?

No, if you load an XDP program and attach the same program to multiple
interfaces, there will only be a single BPF program in the kernel, and a
single map. It will just run on traffic on both interfaces...

**Comment by glennWang** [comment]
> glennWang ***@***.***> writes:
> > Sure, that already works today. https://github.com/xdp-project/xdp-tutorial/tree/master/basic04-pinning-maps I can confirm that different userspace program can access the same bpf map through the pinning as the above example. But I has no idea about two xdp program how to share the same bpf map. Is anywhere some example ?
> If you just put two programs into the same source file (in different sections) they can directly refer to the same map definition and everything will happen automatically if you load the file with libbpf. If they are in different files, or loaded separately, you'll have to convince libbpf to reuse maps between the separate loads, which is what assignment two in that basic04 lesson you linked above is about.
> > You can also attach the same XDP program to multiple interfaces... And if a xdp program (that has a bpf map) is attached to multiple interfaces, there will be multiple different bpf map. Is I am right?
> No, if you load an XDP program and attach the same program to multiple interfaces, there will only be a single BPF program in the kernel, and a single map. It will just run on traffic on both interfaces...

The answer was great, very specific and practical. Thanks a lot.

**Comment by tohojo** [comment]
glennWang ***@***.***> writes:

>> glennWang ***@***.***> writes:
>> > Sure, that already works today. https://github.com/xdp-project/xdp-tutorial/tree/master/basic04-pinning-maps I can confirm that different userspace program can access the same bpf map through the pinning as the above example. But I has no idea about two xdp program how to share the same bpf map. Is anywhere some example ?
>> If you just put two programs into the same source file (in different sections) they can directly refer to the same map definition and everything will happen automatically if you load the file with libbpf. If they are in different files, or loaded separately, you'll have to convince libbpf to reuse maps between the separate loads, which is what assignment two in that basic04 lesson you linked above is about.
>> > You can also attach the same XDP program to multiple interfaces... And if a xdp program (that has a bpf map) is attached to multiple interfaces, there will be multiple different bpf map. Is I am right?
>> No, if you load an XDP program and attach the same program to multiple interfaces, there will only be a single BPF program in the kernel, and a single map. It will just run on traffic on both interfaces...
>
> The answer was great, very specific and practical. Thanks a lot.

You're welcome! :)
