### ISSUE TITLE
The ipv6 address specified for ping is incorrect ?

### ISSUE THREAD

**Issue by gadrenayan** [xdp-project/xdp-tutorial#221]
Hi,

In the packet03 assignment3, the command below:
$ t enter -n right
$ ping fc00:dead:cafe:10::2

There is a typo, This ip address should change to fc00:dead:cafe:1::2
Similarly ip address in tcpdump outputs shoud also change.

**Comment by tohojo** [comment]
gadrenayan ***@***.***> writes:

> Hi,
>
> In the packet03 assignment3, the command below:
> $ t enter -n right
> $ ping fc00:dead:cafe:10::2
>
> There is a typo, This ip address should change to fc00:dead:cafe:1::2
> Similarly ip address in tcpdump outputs shoud also change.

It's not a typo, exactly; the example used in the text just had a few
more namespaces setup before running, so the subnet counter went all the
way up to 10 (and 11). This can happen for someone running through the
tutorial as well, depending on how many environments they setup at one
time. There's a note in the text indicating this right above the
example.

That being said, it probably doesn't hurt to change it to use subnets 1
and 2 in the example test...
