### ISSUE TITLE
AF_XDP issue in 'xsk_socket__create()' returns invalid argument(22)

### ISSUE THREAD

**Issue by Gopinath-Kalaiyarasan** [xdp-project/xdp-tutorial#222]
Hi,
I am writing an eBPF program to filter packets and redirects to AF_XDP socket and in user space program to read and parse the packets for further analysis. I am using libbpf library for user space program. I am not able to create socket using xsk_socket__create(), which returns an error Invalid argument(22).

I am using,
system: centOS 8
kernel: 4.18

Thanks,
Gopinath Kalaiyarasan

**Comment by tohojo** [comment]
Gopinath-Kalaiyarasan ***@***.***> writes:

> Hi,
> I am writing an eBPF program to filter packets and redirects to AF_XDP socket and in user space program to read and parse the packets for further analysis. I am using libbpf library for user space program. I am not able to create socket using xsk_socket__create(), which returns an error Invalid argument(22).
>
> I am using,
> system: centOS 8
> kernel: 4.18

Could you please share the full version of your kernel package? The 4.18
version number is meaningless on CentOS. Also, which version of clang
and libbpf are you using?

**Comment by Gopinath-Kalaiyarasan** [comment]
> Gopinath-Kalaiyarasan ***@***.***> writes:
> Hi, I am writing an eBPF program to filter packets and redirects to AF_XDP socket and in user space program to read and parse the packets for further analysis. I am using libbpf library for user space program. I am not able to create socket using xsk_socket__create(), which returns an error Invalid argument(22). I am using, system: centOS 8 kernel: 4.18
> Could you please share the full version of your kernel package? The 4.18 version number is meaningless on CentOS. Also, which version of clang and libbpf are you using?

Kernel: 4.18.0-305.3.1.el8.x86_64
clang version: 11.0.0
libbpf version: v0.4.0

**Comment by tohojo** [comment]
Gopinath-Kalaiyarasan ***@***.***> writes:

>> Gopinath-Kalaiyarasan ***@***.***> writes:
>> Hi, I am writing an eBPF program to filter packets and redirects to AF_XDP socket and in user space program to read and parse the packets for further analysis. I am using libbpf library for user space program. I am not able to create socket using xsk_socket__create(), which returns an error Invalid argument(22). I am using, system: centOS 8 kernel: 4.18
>> Could you please share the full version of your kernel package? The 4.18 version number is meaningless on CentOS. Also, which version of clang and libbpf are you using?
>
> Kernel: 4.18.0-305.3.1.el8.x86_64
> clang version: 11.0.0
> libbpf version: v0.4.0

And what hardware (and driver) are you trying this on?

**Comment by Gopinath-Kalaiyarasan** [comment]
> Gopinath-Kalaiyarasan ***@***.***> writes:
> > Gopinath-Kalaiyarasan ***@***.***> writes: > Hi, I am writing an eBPF program to filter packets and redirects to AF_XDP socket and in user space program to read and parse the packets for further analysis. I am using libbpf library for user space program. I am not able to create socket using xsk_socket__create(), which returns an error Invalid argument(22). I am using, system: centOS 8 kernel: 4.18 > Could you please share the full version of your kernel package? The 4.18 version number is meaningless on CentOS. Also, which version of clang and libbpf are you using? Kernel: 4.18.0-305.3.1.el8.x86_64 clang version: 11.0.0 libbpf version: v0.4.0
> And what hardware (and driver) are you trying this on?

Now, I am trying this on VM which is running on my local machine (is that causing the error ?)
I have a bare metal server which have i40e NIC but never tried to run the program on the server.

**Comment by tohojo** [comment]
Gopinath-Kalaiyarasan ***@***.***> writes:

>> Gopinath-Kalaiyarasan ***@***.***> writes:
>> > Gopinath-Kalaiyarasan ***@***.***> writes: > Hi, I am writing an eBPF program to filter packets and redirects to AF_XDP socket and in user space program to read and parse the packets for further analysis. I am using libbpf library for user space program. I am not able to create socket using xsk_socket__create(), which returns an error Invalid argument(22). I am using, system: centOS 8 kernel: 4.18 > Could you please share the full version of your kernel package? The 4.18 version number is meaningless on CentOS. Also, which version of clang and libbpf are you using? Kernel: 4.18.0-305.3.1.el8.x86_64 clang version: 11.0.0 libbpf version: v0.4.0
>> And what hardware (and driver) are you trying this on?
>
> Now, I am trying this on VM which is running on my local machine (is that causing the error ?)
> I have a bare metal server which have i40e NIC but never tried to run
> the program on the server.

Could very well be. The driver needs AF_XDP support; i40e has it, but
it's quite likely that your VM driver doesn't...

**Comment by Gopinath-Kalaiyarasan** [comment]
> Gopinath-Kalaiyarasan ***@***.***> writes:
> > Gopinath-Kalaiyarasan ***@***.***> writes: > > Gopinath-Kalaiyarasan ***@***.***> writes: > Hi, I am writing an eBPF program to filter packets and redirects to AF_XDP socket and in user space program to read and parse the packets for further analysis. I am using libbpf library for user space program. I am not able to create socket using xsk_socket__create(), which returns an error Invalid argument(22). I am using, system: centOS 8 kernel: 4.18 > Could you please share the full version of your kernel package? The 4.18 version number is meaningless on CentOS. Also, which version of clang and libbpf are you using? Kernel: 4.18.0-305.3.1.el8.x86_64 clang version: 11.0.0 libbpf version: v0.4.0 > And what hardware (and driver) are you trying this on? Now, I am trying this on VM which is running on my local machine (is that causing the error ?) I have a bare metal server which have i40e NIC but never tried to run the program on the server.
> Could very well be. The driver needs AF_XDP support; i40e has it, but it's quite likely that your VM driver doesn't...

Thank you @tohojo 

Regards,
Gopinath Kalaiyarasan
