### ISSUE TITLE
packet03 - failed to create map (name: 'tx_port')

### ISSUE THREAD

**Issue by walidbarakat** [xdp-project/xdp-tutorial#226]
Hi,
i'm trying to run packet03 solution, specifically xdp_router section, i run make command in "/xdp-tutorial/packet-solutions" directory and then run "mount -t bpf bpf /sys/fs/bpf/" after that "./xdp_loader -d eno2 -F --progsec xdp_router" but i get error : 
libbpf: failed to create map (name: 'tx_port'): Invalid argument(-22)
libbpf: failed to load object 'xdp_prog_kern.o'
ERR: loading BPF-OBJ file(xdp_prog_kern.o) (-22): Invalid argument
ERR: loading file: xdp_prog_kern.o

how should i get xdp_prog_kern.o ? or what i missed in general?

i'm running ubuntu 16 and kernel 4.8.0

thanks in advance.

**Comment by tohojo** [comment]
well ***@***.***> writes:

> Hi,
> i'm trying to run packet03 solution, specifically xdp_router section, i run make command in "/xdp-tutorial/packet-solutions" directory and then :
> **# mount -t bpf bpf /sys/fs/bpf/
> #  ./xdp_loader -d eno2 -F --progsec xdp_router
> _libbpf: failed to create map (name: 'tx_port'): Invalid argument(-22)
> libbpf: failed to load object 'xdp_prog_kern.o'
> ERR: loading BPF-OBJ file(xdp_prog_kern.o) (-22): Invalid argument
> ERR: loading file: xdp_prog_kern.o_**
>
> how should i get xdp_prog_kern.o ? or what i missed in general?
>
> i'm running ubuntu 16 and kernel 4.8.0

You need a newer kernel. 4.19 is the minimum supported by xdp-tutorial...

**Comment by walidbarakat** [comment]
thanks!
