### ISSUE TITLE
how to install libbpf for my new XDP project?

### ISSUE THREAD

**Issue by walidbarakat** [xdp-project/xdp-tutorial#233]
Hi,
 i'm trying to build an independent XDP project, the code from tutorial is running as it should with no problems. but when i compile my own one, clang complains about bpf header files not present, i copied common and headers file from the tutorial and executed the command "git submodule add https://github.com/libbpf/libbpf/ libbpf" to add libbpf to my repo.

any tips about what independencies should be installed beside libbpf to have a code running like the tutorial?

i'm compiling using command "clang -O2 -target bpf -c af_xdp_kern.c -I ./libbpf ./common -o af_xdp_kern.o"

**Comment by tohojo** [comment]
Have a look at the bpf-examples repository: https://github.com/xdp-project/bpf-examples

That's meant to be, among other things, an example of how to setup a build environment with libbpf and the right Makefile definitions to get things to work. You can clone it and adjust to your own needs, or just look at it and copy the bits you find useful...

**Comment by walidbarakat** [comment]
thanks @tohojo :')
