### ISSUE TITLE
Would  XDP  and TC (Ingress) attached to the same net device always run on the same cpu core or not ?

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#235]
Is the situation different under different mode ？

HW, Native, SKB

**Comment by tohojo** [comment]
By default they would, unless you do things like use cpumap redirect in the XDP program...

**Comment by glennWang** [comment]
> By default they would, unless you do things like use cpumap redirect in the XDP program...

If xdp receive pkt on cpu core 1 and then using cpumap redirect to cpu core2,  the copy overhead would on core 1 or core 2 ？

**Comment by tohojo** [comment]
glennWang ***@***.***> writes:

>> By default they would, unless you do things like use cpumap redirect in the XDP program...
>
> If xdp receive pkt on cpu core 1 and then using cpumap redirect to cpu
> core2,  the copy overhead would on core 1 or core 2 ？

Core 2; that's the whole point of cpumap: moving as much processing as
possible to a different CPU. You can even attach a second XDP program to
the map entries to split the XDP processing as well :)

**Comment by glennWang** [comment]
> glennWang ***@***.***> writes:
> > By default they would, unless you do things like use cpumap redirect in the XDP program... If xdp receive pkt on cpu core 1 and then using cpumap redirect to cpu core2, the copy overhead would on core 1 or core 2 ？
> Core 2; that's the whole point of cpumap: moving as much processing as possible to a different CPU. You can even attach a second XDP program to the map entries to split the XDP processing as well :)

`You can even attach a second XDP program to the map entries to split the XDP processing as well`

Hi, @tohojo , I don`t understand this sentence. Could you put a detail explanation. It's better to show the pseudo code.

**Comment by tohojo** [comment]
glennWang ***@***.***> writes:

>> glennWang ***@***.***> writes:
>> > By default they would, unless you do things like use cpumap redirect in the XDP program... If xdp receive pkt on cpu core 1 and then using cpumap redirect to cpu core2, the copy overhead would on core 1 or core 2 ？
>> Core 2; that's the whole point of cpumap: moving as much processing as possible to a different CPU. You can even attach a second XDP program to the map entries to split the XDP processing as well :)
>
> `You can even attach a second XDP program to the map entries to split
> the XDP processing as well`
>
> Hi, @tohojo , I don`t understand this sentence. Could you put a detail
> explanation. It's better to show the pseudo code.

See this patch (and the series it's in) for details:
***@***.***/

**Comment by glennWang** [comment]
> glennWang ***@***.***> writes:
> > glennWang ***@***.***> writes: > > By default they would, unless you do things like use cpumap redirect in the XDP program... If xdp receive pkt on cpu core 1 and then using cpumap redirect to cpu core2, the copy overhead would on core 1 or core 2 ？ > Core 2; that's the whole point of cpumap: moving as much processing as possible to a different CPU. You can even attach a second XDP program to the map entries to split the XDP processing as well :) `You can even attach a second XDP program to the map entries to split the XDP processing as well` Hi, @tohojo , I don`t understand this sentence. Could you put a detail explanation. It's better to show the pseudo code.
> See this patch (and the series it's in) for details: ***@***.***/


The address of this patch is hidden. Can you please paste it again?

**Comment by tohojo** [comment]
Argh, stupid filter. Try this link, and the link to lore in the commit message: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9216477449f33cdbc9c9a99d49f500b7fbb81702
