### ISSUE TITLE
AF_XDP Packets workflow question

### ISSUE THREAD

**Issue by beirvin** [xdp-project/xdp-tutorial#240]
if packets com from NIC, userspace receive packets by AF_XDP type socket, whether there are copy(or same) packets still go through the linux kernel network stack？

**Comment by tohojo** [comment]
Nope. When using AF_XDP there's an XDP program running on the interface which will redirect packets to the socket, so they won't go through the stack as well. You can, however, modify that XDP program to only redirect a subset of packets, so you can steer some traffic to AF_XDP and some to the stack...

**Comment by beirvin** [comment]
> 
> Nope. When using AF_XDP there's an XDP program running on the interface which will redirect packets to the socket, so they won't go through the stack as well. You can, however, modify that XDP program to only redirect a subset of packets, so you can steer some traffic to AF_XDP and some to the stack...



> 
> Nope. When using AF_XDP there's an XDP program running on the interface which will redirect packets to the socket, so they won't go through the stack as well. You can, however, modify that XDP program to only redirect a subset of packets, so you can steer some traffic to AF_XDP and some to the stack...

Thanks a lot. The reason why I ask for this question is because I can't find linux XDP program souce code for redirecting packets, I am trying to find it out.

**Comment by beirvin** [comment]
> 
> 
> > Nope. When using AF_XDP there's an XDP program running on the interface which will redirect packets to the socket, so they won't go through the stack as well. You can, however, modify that XDP program to only redirect a subset of packets, so you can steer some traffic to AF_XDP and some to the stack...
> 
> Thanks a lot. The reason why I ask for this question is because I can't find linux XDP program souce code for redirecting packets, I am trying to find it out.

Hi, I already find the relative linux source code, but I am not very clear that how xsk_load_xdp_prog() function works and return the XDP_REDIRECT. I will try to find it out. thanks again.
./net/xdp/xsk.c
      -->xsk_socket__create()
           -->xsk_socket__create_shared()
              -->xsk->fd = socket(AF_XDP, SOCK_RAW, 0);
              -->__xsk_setup_xdp_prog(xsk, NULL);
                 -->xsk_init_xdp_res(xsk, xsks_map_fd)
                    -->xsk_load_xdp_prog(xsk);
