### ISSUE TITLE
about __builtin_memcpy

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#241]
```
#ifndef memcpy
#define memcpy(dest, src, n) __builtin_memcpy((dest), (src), (n))
#endif
```
When I use this func, the len `n` must be a fixed value. If not, I would get a error like the following. How could I use a dynamic value as the len ?
```
 error: A call to built-in function 'memcpy' is not supported.
                memcpy(to, from, len);
                ^
```

**Comment by tohojo** [comment]
glennWang ***@***.***> writes:

> ```
> #ifndef memcpy
> #define memcpy(dest, src, n) __builtin_memcpy((dest), (src), (n))
> #endif
> ```
> When I use this func, the len `n` must be a fixed value. If not, I would get a error like the following. How could I use a dynamic value as the len ?
> ```
>  error: A call to built-in function 'memcpy' is not supported.
>                 memcpy(to, from, len);
>                 ^
> ```

You can run it in a loop and copy a few fixed chunks at a time?

**Comment by glennWang** [comment]
> glennWang ***@***.***> writes:
> ``` #ifndef memcpy #define memcpy(dest, src, n) __builtin_memcpy((dest), (src), (n)) #endif ``` When I use this func, the len `n` must be a fixed value. If not, I would get a error like the following. How could I use a dynamic value as the len ? ``` error: A call to built-in function 'memcpy' is not supported. memcpy(to, from, len); ^ ```
> You can run it in a loop and copy a few fixed chunks at a time?

Oh. It seems only can be so.
