### ISSUE TITLE
bad map relo against 'mapname' in section 'MAPS' when storing array

### ISSUE THREAD

**Issue by Wqrld** [xdp-project/xdp-tutorial#245]
I'm trying to store a arbitrary C array in a bpf map, as i need a quick way to loop over every item in the array without doing a lot of map lookups, however the verifier fails to load.

kernelspace code:
```c

struct bpf_map_def SEC("MAPS") xdp_bogon_map = {
	.type = BPF_MAP_TYPE_ARRAY,
	.key_size = sizeof(__u8),
	.value_size = 1276,
	.max_entries = 1,
};

	__u32 zerokey = 0;
	struct subnet *bogonList[255];
	*bogonList = bpf_map_lookup_elem(&xdp_bogon_map, &zerokey);

	if (*bogonList)
	{
		bpf_printk("[XDP] bogon list found");
	}
```

error:
```
-> # ./load-stats --dev ens18 -A -F
libbpf: elf: skipping unrecognized data section(6) MAPS
libbpf: elf: skipping unrecognized data section(7) .rodata.str1.1
libbpf: prog 'xdp_stats1_func': bad map relo against 'xdp_bogon_map' in section 'MAPS'
ERR: loading BPF-OBJ file(kernel_main.o) (-2): No such file or directory
ERR: loading file: kernel_main.o
```

If I remove this part of the kernel code the program loads fine, but i cannot seem to figure out what is wrong

EDIT: I am aware that a LPM trie would probably better for matching against ips, but this is in general about an array for which the content is not known at compile time.

**Comment by tohojo** [comment]
Wqrld ***@***.***> writes:

> I'm trying to store a arbitrary C array in a bpf map, as i need a quick way to loop over every item in the array without doing a lot of map lookups, however the verifier fails to load.
>
>
> kernelspace code:
> ```c
>
> struct bpf_map_def SEC("MAPS") xdp_bogon_map = {
> 	.type = BPF_MAP_TYPE_ARRAY,
> 	.key_size = sizeof(__u8),
> 	.value_size = 1276,
> 	.max_entries = 1,
> };
>
> 	__u32 zerokey = 0;
> 	struct subnet *bogonList[255];
> 	*bogonList = bpf_map_lookup_elem(&xdp_bogon_map, &zerokey);
>
> 	if (*bogonList)
> 	{
> 		bpf_printk("[XDP] bogon list found");
> 	}
> ```
>
> error:
> ```
> -> # ./load-stats --dev ens18 -A -F
> libbpf: elf: skipping unrecognized data section(6) MAPS
> libbpf: elf: skipping unrecognized data section(7) .rodata.str1.1
> libbpf: prog 'xdp_stats1_func': bad map relo against 'xdp_bogon_map' in section 'MAPS'
> ERR: loading BPF-OBJ file(kernel_main.o) (-2): No such file or directory
> ERR: loading file: kernel_main.o
> ```
>
> If I remove this part of the kernel code the program loads fine, but i
> cannot seem to figure out what is wrong

There's a hint a few lines above, specifically this:

> libbpf: elf: skipping unrecognized data section(6) MAPS

you need to use lower-case 'maps' as the section name :)

However, for what you're doing you could just define a static global
variable; libbpf will turn that into a map for you and from BPF you can
access it light a regular global. Needs a newer version of LLVM and
libbpf than what we're currently using in the tutorial, though...

**Comment by Wqrld** [comment]
> Wqrld ***@***.***> writes:
> I'm trying to store a arbitrary C array in a bpf map, as i need a quick way to loop over every item in the array without doing a lot of map lookups, however the verifier fails to load. kernelspace code: ```c struct bpf_map_def SEC("MAPS") xdp_bogon_map = { .type = BPF_MAP_TYPE_ARRAY, .key_size = sizeof(__u8), .value_size = 1276, .max_entries = 1, }; __u32 zerokey = 0; struct subnet *bogonList[255]; *bogonList = bpf_map_lookup_elem(&xdp_bogon_map, &zerokey); if (*bogonList) { bpf_printk("[XDP] bogon list found"); } ``` error: ``` -> # ./load-stats --dev ens18 -A -F libbpf: elf: skipping unrecognized data section(6) MAPS libbpf: elf: skipping unrecognized data section(7) .rodata.str1.1 libbpf: prog 'xdp_stats1_func': bad map relo against 'xdp_bogon_map' in section 'MAPS' ERR: loading BPF-OBJ file(kernel_main.o) (-2): No such file or directory ERR: loading file: kernel_main.o ``` If I remove this part of the kernel code the program loads fine, but i cannot seem to figure out what is wrong
> There's a hint a few lines above, specifically this:
> libbpf: elf: skipping unrecognized data section(6) MAPS
> you need to use lower-case 'maps' as the section name :) However, for what you're doing you could just define a static global variable; libbpf will turn that into a map for you and from BPF you can access it light a regular global. Needs a newer version of LLVM and libbpf than what we're currently using in the tutorial, though...

The small things you just miss when reading over your own code haha, Thanks for the hint 👍 
I will look into the global variable idea, that should be a lot easier than the current workarounds

**Comment by tohojo** [comment]
> The small things you just miss when reading over your own code haha,
> Thanks for the hint

You're welcome :)
