### ISSUE TITLE
packet03-redirecting: Failed to update bpf map file

### ISSUE THREAD

**Issue by withlin** [xdp-project/xdp-tutorial#264]
### system configration

```
//ubuntu hirsute
root@ubuntu-hirsute:~# uname -r
5.11.0-41-generic

```

### docker info

```
root@ubuntu-hirsute:~# docker version
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

root@ubuntu-hirsute:~/withlin/socket-ebpf/bpf# docker ps
CONTAINER ID   IMAGE     COMMAND                  CREATED       STATUS       PORTS                                     NAMES
61bf049ec98e   nginx     "/docker-entrypoint.…"   2 hours ago   Up 2 hours   0.0.0.0:49159->80/tcp, :::49159->80/tcp   nginx2
166120b40c84   nginx     "/docker-entrypoint.…"   2 hours ago   Up 2 hours   0.0.0.0:49158->80/tcp, :::49158->80/tcp   nginx1
root@ubuntu-hirsute:~/withlin/socket-ebpf/bpf# docker inspect --format='{{.NetworkSettings.SandboxKey}}' 166120b40c84
/var/run/docker/netns/ca21784a5d03
root@ubuntu-hirsute:~/withlin/socket-ebpf/bpf#  sudo nsenter --net=/var/run/docker/netns/ca21784a5d03  ethtool -S eth0
NIC statistics:
     peer_ifindex: 25
     rx_queue_0_xdp_packets: 0
     rx_queue_0_xdp_bytes: 0
     rx_queue_0_drops: 0
     rx_queue_0_xdp_redirect: 0
     rx_queue_0_xdp_drops: 0
     rx_queue_0_xdp_tx: 0
     rx_queue_0_xdp_tx_errors: 0
     tx_queue_0_xdp_xmit: 0
     tx_queue_0_xdp_xmit_errors: 0
root@ubuntu-hirsute:~/withlin/socket-ebpf/bpf# ip link | grep 308:
root@ubuntu-hirsute:~/withlin/socket-ebpf/bpf# ip link | grep 25
25: vethebed2eb@if24: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default
root@ubuntu-hirsute:~/withlin/socket-ebpf/bpf# docker inspect --format='{{.NetworkSettings.SandboxKey}}' 61bf049ec98e
/var/run/docker/netns/c75b5ee26748
root@ubuntu-hirsute:~/withlin/socket-ebpf/bpf# nsenter --net=/var/run/docker/netns/c75b5ee26748 ethtool -S eth0
NIC statistics:
     peer_ifindex: 27
     rx_queue_0_xdp_packets: 0
     rx_queue_0_xdp_bytes: 0
     rx_queue_0_drops: 0
     rx_queue_0_xdp_redirect: 0
     rx_queue_0_xdp_drops: 0
     rx_queue_0_xdp_tx: 0
     rx_queue_0_xdp_tx_errors: 0
     tx_queue_0_xdp_xmit: 0
     tx_queue_0_xdp_xmit_errors: 0
root@ubuntu-hirsute:~/withlin/socket-ebpf/bpf# ip link | grep 27:
    link/ether 08:00:27:ce:cb:12 brd ff:ff:ff:ff:ff:ff
27: vetha00a49f@if26: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 xdp qdisc noqueue master docker0 state UP mode DEFAULT group default

```

#### nginx1

172.17.0.2
vethebed2eb
02:42:ac:11:00:02

####  nginx2

172.17.0.3
vetha00a49f
02:42:ac:11:00:03

### packet03-redirecting

```
root@ubuntu-hirsute:~/withlin/xdp-tutorial/packet03-redirecting# ./xdp_loader --dev vetha00a49f --force --progsec xdp_redirect_map
Success: Loaded BPF-object(xdp_prog_kern.o) and used section(xdp_redirect_map)
 - XDP prog attached on device:vetha00a49f(ifindex:27)
 - Pinning maps in /sys/fs/bpf/vetha00a49f/

root@ubuntu-hirsute:~/withlin/xdp-tutorial/packet03-redirecting# ./xdp_prog_user -d vethebed2eb -r  vetha00a49f  --src-mac 02:42:ac:11:00:02 --dest-mac 02:42:ac:11:00:03
map dir: /sys/fs/bpf/vethebed2eb
redirect from ifnum=25 to ifnum=27
WARN: Failed to update bpf map file: err(9):Bad file descriptor
can't write iface params

```

**Comment by withlin** [comment]
@tohojo @magnus-karlsson  ping

**Comment by tohojo** [comment]
> ***@***.***:~/withlin/xdp-tutorial/packet03-redirecting# ./xdp_prog_user -d vethebed2eb -r  vetha00a49f  --src-mac 02:42:ac:11:00:02 --dest-mac 02:42:ac:11:00:03
> map dir: /sys/fs/bpf/vethebed2eb
> redirect from ifnum=25 to ifnum=27
> WARN: Failed to update bpf map file: err(9):Bad file descriptor
> can't write iface params
>
> ```

"Bad file descriptor" indicates that the map_fd you're passing to
bpf_update_map() is not valid, and it's set to -1 before you update the
code... So, erm, did you update the code to actually open the map fd
like the assignment tells you to do? Just running the code as-is won't
work :)

**Comment by withlin** [comment]
@tohojo  Thank you very much.  I thought it was -1. it work for me.

**Comment by Achelics** [comment]
> @tohojo Thank you very much. I thought it was -1. it work for me.

@withlin I just want know how dou you resolve it.

**Comment by Achelics** [comment]
@withlin 
I met the same question.
----------------------------------------------
map dir: /sys/fs/bpf/enp3s0
redirect from ifnum=4 to ifnum=2
WARN: Failed to update bpf map file: err(9):Bad file descriptor
can't write iface params

**Comment by withlin** [comment]
> "Bad file descriptor" indicates that the map_fd you're passing to
bpf_update_map() is not valid, and it's set to -1 before you update the
code... So, erm, did you update the code to actually open the map fd
like the assignment tells you to do? Just running the code as-is won't
work :)

```
map_fd = bpf_obj_get("/sys/fs/bpf/vethd81d88c/redirect_params");

```

@Achelics

**Comment by Achelics** [comment]
> > "Bad file descriptor" indicates that the map_fd you're passing to
> > bpf_update_map() is not valid, and it's set to -1 before you update the
> > code... So, erm, did you update the code to actually open the map fd
> > like the assignment tells you to do? Just running the code as-is won't
> > work :)
> 
> ```
> map_fd = bpf_obj_get("/sys/fs/bpf/vethd81d88c/redirect_params");
> ```
> 
> @Achelics

Could you tell me where is "map_fd" ? How I can chage the value of map_fd

**Comment by Achelics** [comment]
@withlin I change the map_fd success. but now i met new question.
map dir: /sys/fs/bpf/enp5s0
redirect from ifnum=4 to ifnum=5
WARN: Failed to update bpf map file: err(7):Argument list too long
can't write iface params
