### ISSUE TITLE
Packet01 tutorial sequence number strange result.

### ISSUE THREAD

**Issue by wmaxfield** [xdp-project/xdp-tutorial#274]
Everything is good until icmp6h->icmp6_sequenc.  It always comes back as same number.
I added printk because I could never use the sequence number to trigger an XDP_ABORTED.

There is NO xdp_prog_kern.c in the solutions.  Only solutions for packet02 and 03, and your suggestions are obtuse when things are failing badly.   I have NO idea if I am referencing the sequence number properly, but it does compile and load.

any suggestions?

static __always_inline int parse_icmp6hdr(struct hdr_cursor *nh,
                      void *data_end,
                      struct icmp6hdr **icmp6hdr)
{
    struct icmp6hdr *icmp6h = nh->pos;

    if (icmp6h + 1 > data_end)
        return -1;

    nh->pos   = icmp6h + 1;
    *icmp6hdr = icmp6h;

    int seq = bpf_ntohs(icmp6h->icmp6_sequence);
    bpf_printk("seq=%d",seq);

    return icmp6h->icmp6_type;
}

----
pi@raspberrypi:~/xdp-tutorial/packet01-parsing $ sudo ./xdp_loader --dev veth-basic02 --force
Success: Loaded BPF-object(xdp_prog_kern.o) and used section(xdp_packet_parser)
 - XDP prog attached on device:veth-basic02(ifindex:4)
 - Unpinning (remove) prev maps in /sys/fs/bpf/veth-basic02/
 - Pinning maps in /sys/fs/bpf/veth-basic02/
pi@raspberrypi:~/xdp-tutorial/packet01-parsing $ t ping
Running ping from inside test environment:

PING fc00:dead:cafe:1::1(fc00:dead:cafe:1::1) 56 data bytes
64 bytes from fc00:dead:cafe:1::1: icmp_seq=1 ttl=64 time=0.169 ms
64 bytes from fc00:dead:cafe:1::1: icmp_seq=2 ttl=64 time=0.228 ms
64 bytes from fc00:dead:cafe:1::1: icmp_seq=3 ttl=64 time=0.229 ms
64 bytes from fc00:dead:cafe:1::1: icmp_seq=4 ttl=64 time=0.171 ms
64 bytes from fc00:dead:cafe:1::1: icmp_seq=5 ttl=64 time=0.229 ms
^C
--- fc00:dead:cafe:1::1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 145ms
rtt min/avg/max/mdev = 0.169/0.205/0.229/0.030 ms
pi@raspberrypi:~/xdp-tutorial/packet01-parsing $ sudo cat /sys/kernel/debug/tracing/trace_pipe
           ping6-15458   [000] dns1 19755.788749: bpf_trace_printk: seq=14912
           ping6-15458   [000] d.s1 19756.809342: bpf_trace_printk: seq=14912
           ping6-15458   [000] d.s1 19757.849363: bpf_trace_printk: seq=14912
           ping6-15458   [000] d.s1 19758.889338: bpf_trace_printk: seq=14912
           ping6-15458   [000] d.s1 19759.929403: bpf_trace_printk: seq=14912

any suggestions?

**Comment by tohojo** [comment]
wmaxfield ***@***.***> writes:

> Everything is good until icmp6h->icmp6_sequenc.  It always comes back as same number.
> I added printk because I could never use the sequence number to trigger an XDP_ABORTED.
>
> There is NO xdp_prog_kern.c in the solutions.  Only solutions for packet02 and 03, and your suggestions are obtuse when things are failing badly.   I have NO idea if I am referencing the sequence number properly, but it does compile and load.
>
>
> any suggestions?
>
> static __always_inline int parse_icmp6hdr(struct hdr_cursor *nh,
>                       void *data_end,
>                       struct icmp6hdr **icmp6hdr)
> {
>     struct icmp6hdr *icmp6h = nh->pos;
>
>     if (icmp6h + 1 > data_end)
>         return -1;
>
>     nh->pos   = icmp6h + 1;
>     *icmp6hdr = icmp6h;
>
>     int seq = bpf_ntohs(icmp6h->icmp6_sequence);
>     bpf_printk("seq=%d",seq);
>
>     return icmp6h->icmp6_type;
> }

This bit of code looks fine, but it is obviously printing something
that's not the ICMP header. Bit hard to figure out why without having
the rest of the code, though...

**Comment by wmaxfield** [comment]
I finally determined what the problem is.  In the tutorial, the comment is:

"After parsing the ICMPv6 header, it is finally time to make our decisions based on the packet payload. In this case, we are interested in the sequence number. The data structure is quite deeply nested, but the header file also defines a convenient alias, so the sequence number can be accessed as icmp6h->icmp6_sequence (but don’t forget byte order conversion)."

  That is not quite right, especially for me, who can be stupid.  A more correct phrase to use might be  "point to the data just past the header and then use the sequence number alias to access it."  A possible solution is given:
 
`        int rslt= parse_ip6hdr(&nh,data_end,&ipv6h);

        if (rslt ==IPPROTO_ICMPV6){
          struct icmp6hdr *icmpv6h = (void*)(ipv6h+1);
         // required for bounds check
          if (icmpv6h +1 > (struct icmp6hdr*)data_end){
              bpf_printk("icmpv6 header size error. exiting.");
              return -1;
          }

          if (icmpv6h->icmp6_type==ICMPV6_ECHO_REQUEST){
              bpf_printk(" ..is echo request ");
              int seq = bpf_ntohs(icmpv6h->icmp6_sequence);
              bpf_printk(" sequence=%d",seq);
              if (seq & 1){
                  bpf_printk(" dropped ");
                  action=XDP_DROP;
              }
          }`

**Comment by wmaxfield** [comment]
I apologize.  The parse_ip6hdr() is updated to be:
`static __always_inline int parse_ip6hdr(struct hdr_cursor *nh,
					void *data_end,
					struct ipv6hdr **ip6hdr){
    struct ipv6hdr *ip6h = nh->pos;
    int hdrsize = sizeof(*ip6h);

    /* Byte-count bounds check; check if current pointer + size of header
     * is after data_end.
     */
    if (ip6h +1 > (struct ipv6hdr*)data_end)
        return -1;

    nh->pos += hdrsize;
    *ip6hdr = ip6h;

    return ip6h->nexthdr; /* network-byte-order */

}`

**Comment by tohojo** [comment]
wmaxfield ***@***.***> writes:

> I apologize.  The parse_ip6hdr() is updated to be:
> `static __always_inline int parse_ip6hdr(struct hdr_cursor *nh,
> 					void *data_end,
> 					struct ipv6hdr **ip6hdr){
>     struct ipv6hdr *ip6h = nh->pos;
>     int hdrsize = sizeof(*ip6h);
>
>     /* Byte-count bounds check; check if current pointer + size of header
>      * is after data_end.
>      */
>     if (ip6h +1 > (struct ipv6hdr*)data_end)
>         return -1;
>
>     nh->pos += hdrsize;
>     *ip6hdr = ip6h;
>
>     return ip6h->nexthdr; /* network-byte-order */
>
> }`

Ah, right, so the bug was that you didn't increment the nh->pos pointer
in your `parse_ip6hdr()` function when completing assignment 2? We could
certainly add a hint about that to the text :)

**Comment by wmaxfield** [comment]
It has to be incremented twice.  I got that from Advanced03, which turned on the light bulb.

Having explicit code solution really does help, even if the hints are not good enough for me, due to a lower IQ.
