### ISSUE TITLE
Splitting a packet into two packets in XDP layer

### ISSUE THREAD

**Issue by Ngalstyan4** [xdp-project/xdp-tutorial#276]
If I understand it right, XDP allows raw packet modifications and even allows resizing the packet. XDP processing happens before networking stack has parsed any protocols or allocated `sk_buff`. 

Does this mean that we can use XDP to split a packet into several packets and have the rest of networking stack think several packets were transmitted in the first place?

It seems to me this would be possible by the following:
1.  Call `xdp_adjust_tail` to adjust the packet size to the total size of PACKET1+PACKET2
2. Update the payload for PACKET1 and update its length at protocol header
3. Copy/create relevant headers(eth, IP, transport) for PACKET2 right after the payload of PACKET1
4. Add PACKET2 payload and update length in headers 
5. return `XDP_PASS`

Before trying this in code and adding an example here, wanted to see if I am missing some obvious reason why this is impossible. Thanks!

**Comment by tohojo** [comment]
Narek Galstyan ***@***.***> writes:

> If I understand it right, XDP allows raw packet modifications and even
> allows resizing the packet. XDP processing happens before networking
> stack has parsed any protocols or allocated `sk_buff`.
>
> Does this mean that we can use XDP to split a packet into several
> packets and have the rest of networking stack think several packets
> were transmitted in the first place?
>
> It seems to me this would be possible by the following:
> 1.  Call `xdp_adjust_tail` to adjust the packet size to the total size of PACKET1+PACKET2
> 2. Update the payload for PACKET1 and update its length at protocol header
> 3. Copy/create relevant headers(eth, IP, transport) for PACKET2 right after the payload of PACKET1
> 4. Add PACKET2 payload and update length in headers 
> 5. return `XDP_PASS`
>
>
> Before trying this in code and adding an example here, wanted to see
> if I am missing some obvious reason why this is impossible. Thanks!

Yeah, that won't work; no actual splitting will be done after you PASS
the packet, it will be turned into a single skb with some weird stuff at
the end... :)

**Comment by Ngalstyan4** [comment]
Is there other currently available or future possible interface for splitting/creating packets in XDP layer?
Do you know of any documentation/resources that I could use to better understand XDP internals and what it would take to support packet creation there?

In any case, thanks for clarification, @tohojo, and feel free to close this issue.

**Comment by tohojo** [comment]
Narek Galstyan ***@***.***> writes:

> Is there other currently available or future possible interface for
> splitting/creating packets in XDP layer?

I am not aware of anyone working to support splitting of packets, no. As
for creating them, there's a now a possibility of using XDP from
bpf_prog_run() from userspace. That is probably not what you're after,
and it's optimised for bulk packet generation not one-off packet
injection:

https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=de55c9a1967c798fba6d8afe19826f8f03049db3

> Do you know of any documentation/resources that I could use to better
> understand XDP internals and what it would take to support packet
> creation there?

I don't think any documentation exists for the internal kernel APIs if
that's what you mean. You'll "just" have to read the source (and the
commit messages!), I'm afraid :(

> In any case, thanks for clarification, @tohojo, and feel free to close
> this issue.

You're welcome!
