### ISSUE TITLE
Include error detected of #include <bpf/bpf_helpers.h>

### ISSUE THREAD

**Issue by Roy-Carter** [xdp-project/xdp-tutorial#289]
Hey . i've tried setting up the tutorial as the documentation says , built it with make and when I came to the xdp_pass_kern.c file 
to view my first example i've encountered a problem 

> cannot open source file "bpf/bpf_helpers.h"C/C++(1696)

Did someone ever encountered it [before]? I tried to redo all my steps and download everything but it still seem to show it , even though I do infact see that file.

I can clearly see that libbpf is added within my project after I included the submodules but still it shows it can't find the path.
(https://gyazo.com/9741c08fdea27c19508cb3d0fa85d72d)

**Comment by tohojo** [comment]
Roy Carter ***@***.***> writes:

> Hey . i've tried setting up the tutorial as the documentation says , built it with make and when I came to the xdp_pass_kern.c file 
> to view my first example i've encountered a problem 
>
>> cannot open source file "bpf/bpf_helpers.h"C/C++(1696)
>
> Did someone ever encountered it before ? I tried to redo all my steps
> and download everything but it still seem to show it , even though I
> do infact see that file.

Did you clone the libbpf submodule as well? Either 'git clone
--recurse-submodules' on initial clone, or using 'git submodule update
--init' afterwards?

**Comment by tohojo** [comment]
Roy Carter ***@***.***> writes:

> Yes I did @tohojo , I used the  init method and I do intact see the
> libbpf within my VScode folder and I can see those files but for some
> reason when I use make it says the error I mentioned on the file
> itself !

Oh, so this is a vscode error message, not the compiler? Maybe vscode is
not picking up the include path from the Makefile correctly?

**Comment by Roy-Carter** [comment]
> Roy Carter ***@***.***> writes:
> Yes I did @tohojo , I used the init method and I do intact see the libbpf within my VScode folder and I can see those files but for some reason when I use make it says the error I mentioned on the file itself !
> Oh, so this is a vscode error message, not the compiler? Maybe vscode is not picking up the include path from the Makefile correctly?

Do you know a way in which I can handle this problem ? Seems unlikely as I followed many tutorials on YouTube that did the exact same. What IDE would you recommend using with EBPF?

**Comment by Roy-Carter** [comment]
I did do it already once but I'll show you the output of what comes : its pretty long but as a newbie I couldn't find anything wrong with it ? 
and when checking libbpf/src/build/ I do infact see all the correct header files .
[https://gyazo.com/6be1938259ac48d445eeabe0d674597f](url)
What can cause VScode to not identify the header file ?

`roycarter@roycarter-VirtualBox:~/Dev/xdp-tutorial$ make
make -C basic03-map-counter
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic03-map-counter'
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/libbpf/src'
mkdir -p ./staticobjs
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c bpf.c -o staticobjs/bpf.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c btf.c -o staticobjs/btf.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c libbpf.c -o staticobjs/libbpf.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c libbpf_errno.c -o staticobjs/libbpf_errno.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c netlink.c -o staticobjs/netlink.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c nlattr.c -o staticobjs/nlattr.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c str_error.c -o staticobjs/str_error.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c libbpf_probes.c -o staticobjs/libbpf_probes.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c bpf_prog_linfo.c -o staticobjs/bpf_prog_linfo.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c xsk.c -o staticobjs/xsk.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c btf_dump.c -o staticobjs/btf_dump.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c hashmap.c -o staticobjs/hashmap.o
ar rcs libbpf.a staticobjs/bpf.o staticobjs/btf.o staticobjs/libbpf.o staticobjs/libbpf_errno.o staticobjs/netlink.o staticobjs/nlattr.o staticobjs/str_error.o staticobjs/libbpf_probes.o staticobjs/bpf_prog_linfo.o staticobjs/xsk.o staticobjs/btf_dump.o staticobjs/hashmap.o
mkdir -p ./sharedobjs
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c bpf.c -o sharedobjs/bpf.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c btf.c -o sharedobjs/btf.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c libbpf.c -o sharedobjs/libbpf.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c libbpf_errno.c -o sharedobjs/libbpf_errno.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c netlink.c -o sharedobjs/netlink.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c nlattr.c -o sharedobjs/nlattr.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c str_error.c -o sharedobjs/str_error.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c libbpf_probes.c -o sharedobjs/libbpf_probes.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c bpf_prog_linfo.c -o sharedobjs/bpf_prog_linfo.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c xsk.c -o sharedobjs/xsk.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c btf_dump.c -o sharedobjs/btf_dump.o
cc -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -fPIC -fvisibility=hidden -DSHARED  -c hashmap.c -o sharedobjs/hashmap.o
cc -shared -Wl,--version-script=libbpf.map \
              -Wl,-soname,libbpf.so.0 \
              sharedobjs/bpf.o sharedobjs/btf.o sharedobjs/libbpf.o sharedobjs/libbpf_errno.o sharedobjs/netlink.o sharedobjs/nlattr.o sharedobjs/str_error.o sharedobjs/libbpf_probes.o sharedobjs/bpf_prog_linfo.o sharedobjs/xsk.o sharedobjs/btf_dump.o sharedobjs/hashmap.o  -lelf -o libbpf.so.0.0.6
ln -sf libbpf.so.0.0.6 libbpf.so.0
ln -sf libbpf.so.0 libbpf.so
sed -e "s|@PREFIX@|/usr|" \
        -e "s|@LIBDIR@|/usr/lib64|" \
        -e "s|@VERSION@|0.0.6|" \
        < libbpf.pc.template > libbpf.pc
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/libbpf/src'
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/libbpf/src'
if [ ! -d 'build/usr/include/bpf' ]; then install -d -m 755 'build/usr/include/bpf'; fi; install bpf.h libbpf.h btf.h xsk.h libbpf_util.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h -m 644 'build/usr/include/bpf'
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/libbpf/src'
make -C ../common/
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/common'
gcc -g -Wall -I../libbpf/src//build/usr/include/  -I../headers -c -o common_params.o common_params.c
gcc -g -Wall -I../libbpf/src//build/usr/include/  -I../headers -c -o common_user_bpf_xdp.o common_user_bpf_xdp.c
gcc -g -Wall -I../libbpf/src//build/usr/include/  -I../headers -c -o common_libbpf.o common_libbpf.c
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/common'
cc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o xdp_load_and_stats ../common//common_params.o ../common//common_user_bpf_xdp.o \
 xdp_load_and_stats.c -l:libbpf.a -lelf 
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_prog_kern.ll xdp_prog_kern.c
llc -march=bpf -filetype=obj -o xdp_prog_kern.o xdp_prog_kern.ll
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic03-map-counter'
make -C basic01-xdp-pass
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic01-xdp-pass'
gcc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o xdp_pass_user ../common//common_params.o \
 xdp_pass_user.c -l:libbpf.a -lelf 
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_pass_kern.ll xdp_pass_kern.c
llc -march=bpf -filetype=obj -o xdp_pass_kern.o xdp_pass_kern.ll
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic01-xdp-pass'
make -C basic04-pinning-maps
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic04-pinning-maps'
cc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o xdp_loader ../common//common_libbpf.o ../common//common_params.o ../common//common_user_bpf_xdp.o \
 xdp_loader.c -l:libbpf.a -lelf 
cc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o xdp_stats ../common//common_libbpf.o ../common//common_params.o ../common//common_user_bpf_xdp.o \
 xdp_stats.c -l:libbpf.a -lelf 
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_prog_kern.ll xdp_prog_kern.c
llc -march=bpf -filetype=obj -o xdp_prog_kern.o xdp_prog_kern.ll
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic04-pinning-maps'
make -C basic02-prog-by-name
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic02-prog-by-name'
cc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o xdp_loader ../common//common_params.o ../common//common_user_bpf_xdp.o \
 xdp_loader.c -l:libbpf.a -lelf 
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_prog_kern.ll xdp_prog_kern.c
llc -march=bpf -filetype=obj -o xdp_prog_kern.o xdp_prog_kern.ll
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic02-prog-by-name'
make -C basic-solutions
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
cc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o xdp_stats ../common//common_libbpf.o ../common//common_params.o ../common//common_user_bpf_xdp.o \
 xdp_stats.c -l:libbpf.a -lelf 
cc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o xdp_loader ../common//common_libbpf.o ../common//common_params.o ../common//common_user_bpf_xdp.o \
 xdp_loader.c -l:libbpf.a -lelf 
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
make -C packet03-redirecting
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/packet03-redirecting'
cc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o xdp_prog_user ../common/common_params.o ../common/common_user_bpf_xdp.o \
 xdp_prog_user.c -l:libbpf.a -lelf 
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_prog_kern.ll xdp_prog_kern.c
llc -march=bpf -filetype=obj -o xdp_prog_kern.o xdp_prog_kern.ll
make -C ../common/../basic-solutions xdp_loader
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
make[2]: 'xdp_loader' is up to date.
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
cp ../common/../basic-solutions/xdp_loader xdp_loader
make -C ../common/../basic-solutions xdp_stats
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
make[2]: 'xdp_stats' is up to date.
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
cp ../common/../basic-solutions/xdp_stats xdp_stats
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/packet03-redirecting'
make -C packet01-parsing
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/packet01-parsing'
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_prog_kern.ll xdp_prog_kern.c
llc -march=bpf -filetype=obj -o xdp_prog_kern.o xdp_prog_kern.ll
make -C ../common/../basic-solutions xdp_loader
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
make[2]: 'xdp_loader' is up to date.
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
cp ../common/../basic-solutions/xdp_loader xdp_loader
make -C ../common/../basic-solutions xdp_stats
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
make[2]: 'xdp_stats' is up to date.
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
cp ../common/../basic-solutions/xdp_stats xdp_stats
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/packet01-parsing'
make -C packet-solutions
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/packet-solutions'
cc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o xdp_prog_user ../common/common_params.o ../common/common_user_bpf_xdp.o \
 xdp_prog_user.c -l:libbpf.a -lelf 
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_prog_kern_02.ll xdp_prog_kern_02.c
llc -march=bpf -filetype=obj -o xdp_prog_kern_02.o xdp_prog_kern_02.ll
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_prog_kern_03.ll xdp_prog_kern_03.c
llc -march=bpf -filetype=obj -o xdp_prog_kern_03.o xdp_prog_kern_03.ll
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_vlan01_kern.ll xdp_vlan01_kern.c
llc -march=bpf -filetype=obj -o xdp_vlan01_kern.o xdp_vlan01_kern.ll
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_vlan02_kern.ll xdp_vlan02_kern.c
llc -march=bpf -filetype=obj -o xdp_vlan02_kern.o xdp_vlan02_kern.ll
make -C ../common/../basic-solutions xdp_loader
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
make[2]: 'xdp_loader' is up to date.
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
cp ../common/../basic-solutions/xdp_loader xdp_loader
make -C ../common/../basic-solutions xdp_stats
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
make[2]: 'xdp_stats' is up to date.
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
cp ../common/../basic-solutions/xdp_stats xdp_stats
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/packet-solutions'
make -C packet02-rewriting
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/packet02-rewriting'
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_prog_kern.ll xdp_prog_kern.c
llc -march=bpf -filetype=obj -o xdp_prog_kern.o xdp_prog_kern.ll
make -C ../common/../basic-solutions xdp_loader
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
make[2]: 'xdp_loader' is up to date.
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
cp ../common/../basic-solutions/xdp_loader xdp_loader
make -C ../common/../basic-solutions xdp_stats
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
make[2]: 'xdp_stats' is up to date.
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
cp ../common/../basic-solutions/xdp_stats xdp_stats
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/packet02-rewriting'
make -C tracing03-xdp-debug-print
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/tracing03-xdp-debug-print'
gcc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o trace_read ../common//common_params.o \
 trace_read.c -l:libbpf.a -lelf 
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_prog_kern.ll xdp_prog_kern.c
llc -march=bpf -filetype=obj -o xdp_prog_kern.o xdp_prog_kern.ll
make -C ../common//../basic-solutions xdp_loader
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
make[2]: 'xdp_loader' is up to date.
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
cp ../common//../basic-solutions/xdp_loader xdp_loader
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/tracing03-xdp-debug-print'
make -C tracing04-xdp-tcpdump
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/tracing04-xdp-tcpdump'
gcc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o xdp_sample_pkts_user ../common//common_params.o \
 xdp_sample_pkts_user.c -l:libbpf.a -lelf -lpcap
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_sample_pkts_kern.ll xdp_sample_pkts_kern.c
llc -march=bpf -filetype=obj -o xdp_sample_pkts_kern.o xdp_sample_pkts_kern.ll
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/tracing04-xdp-tcpdump'
make -C tracing01-xdp-simple
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/tracing01-xdp-simple'
cc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o trace_load_and_stats ../common//common_params.o ../common//common_user_bpf_xdp.o \
 trace_load_and_stats.c -l:libbpf.a -lelf 
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o trace_prog_kern.ll trace_prog_kern.c
llc -march=bpf -filetype=obj -o trace_prog_kern.o trace_prog_kern.ll
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o xdp_prog_kern.ll xdp_prog_kern.c
llc -march=bpf -filetype=obj -o xdp_prog_kern.o xdp_prog_kern.ll
make -C ../common//../basic-solutions xdp_loader
make[2]: Entering directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
make[2]: 'xdp_loader' is up to date.
make[2]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/basic-solutions'
cp ../common//../basic-solutions/xdp_loader xdp_loader
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/tracing01-xdp-simple'
make -C tracing02-xdp-monitor
make[1]: Entering directory '/home/roycarter/Dev/xdp-tutorial/tracing02-xdp-monitor'
cc -Wall -I../libbpf/src//build/usr/include/ -g -I../headers/ -L../libbpf/src/ -o trace_load_and_stats ../common//common_params.o ../common//common_user_bpf_xdp.o \
 trace_load_and_stats.c -l:libbpf.a -lelf 
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o trace_prog_kern.ll trace_prog_kern.c
llc -march=bpf -filetype=obj -o trace_prog_kern.o trace_prog_kern.ll
make[1]: Leaving directory '/home/roycarter/Dev/xdp-tutorial/tracing02-xdp-monitor'`

**Comment by Roy-Carter** [comment]
Weird .. I came back after a couple of hours and suddenly it decides to correctly detect it ! weird VSCode behaviour .. 
really thanking you for your help @tohojo at least now I have some better understanding of how I know my compilation process has succeed !

**Comment by tohojo** [comment]
Roy Carter ***@***.***> writes:

> Weird .. I came back after a couple of hours and suddenly it decides to correctly detect it ! weird VSCode behaviour .. 
> really thanking you for your help @tohojo at least now I have some better understanding of how I know my compilation process has succeed ! 

Great! You're welcome :)
