### ISSUE TITLE
XDP limitation on ingress path only

### ISSUE THREAD

**Issue by huang195** [xdp-project/xdp-tutorial#290]
I've seen this XDP limitation being mentioned a few times. It's one of the main difference between XDP and TC hook points. But's not really explained by XDP hook point is only unidirectional. I couldn't find much information about this topic searching on google. If someone can point me towards the right direction to understand this limitation, I'd greatly appreciate it!

**Comment by tohojo** [comment]
What do you need explained? The XDP hook only works on ingress, because
there is not (yet) any hook implemented in the egress direction... There
have been discussions on this, but nothing has materialised thus far.

**Comment by tohojo** [comment]
Hai Huang ***@***.***> writes:

> @tohojo thanks for that quick reply. If I understand you correctly,
> the fact that XDP hook point only works on ingress is just that it has
> not been implemented, not because some design decision that prevents
> XDP hook point from working on egress. Is that fair to say?

Well, yeah, it could in principle be implemented at some point in the
future. It's not trivial, though, but we do want to add it in some form
or another.

> Also, is there a timeline when egree hook point is going to be
> available?

As everything Linux: Whenever someone works out all the issues and
writes the code :)

Or in other words, no, no timeline...

> Are the discussions you mentioned through Slack or kernel mailing
> list? Can you give a pointer? Thanks!

I think the last time it was discussed was when we added the devmap TX
hook; see this thread:
***@***.***

**Comment by huang195** [comment]
@tohojo great, thanks for clarification. The thread link you were sending didn't come through it seem.

**Comment by tohojo** [comment]
Argh, useless github email filter. Here you go: https://lore.kernel.org/all/20200513014607.40418-8-dsahern@kernel.org/

**Comment by huang195** [comment]
@tohojo great! will close the issue now. Thanks for the pointers!
