### ISSUE TITLE
queue_id in xsks_map

### ISSUE THREAD

**Issue by tjcw** [xdp-project/xdp-tutorial#313]
I am trying to get my test case https://github.com/tjcw/xdp-tutorial/tree/master/ebpf-filter to work. It should redirect packets to user space where they can be evaluated, but what it is doing is letting all the packets through with XDP_PASS.
I had it working for a single device queue with a call to xsk_socket__create ; but I'm not able to arrange for the device to send all packets to a single queue so I have revised the test case to configure 16 AF_XDP sockets on the 16 queues that the device uses, and to call xsk_socket__create_shared for each queue.
When I run 'ping' on a client machine I get this in the trace
```
          <idle>-0       [091] dNs.1 440321.015093: bpf_trace_printk: index=0 mapped=0000000000000000

          <idle>-0       [091] dNs.1 440321.015106: bpf_trace_printk: stats_record_action action=2

          <idle>-0       [091] dNs.1 440321.015108: bpf_trace_printk: index=0 mapped=0000000000000000

          <idle>-0       [091] dNs.1 440321.015109: bpf_trace_printk: stats_record_action action=2
 
```
Is the mapping between the queue number passed to xsk_socket__create_shared and the rx_queue_index the obvious one ?

**Comment by tjcw** [comment]
I instrumented the test case (in the eBPF program), and the problem seems to be that no entries are being set in the xsks_map. How can I check that libxdp is getting hold of the xsks map correctly to share with the kernel ?

**Comment by tjcw** [comment]
It looks like the problem is that I am not calling xsk_setup_xdp_prog , which would  be a fault of my move to BFP 1.0 and xdp. I will leave this issue open until I have checked this.

**Comment by tohojo** [comment]
Ping @magnus-karlsson as he has a better grasp of how this is actually supposed to work...

**Comment by magnus-karlsson** [comment]
If you want to create 16 sockets each bound to different queue ids but the same umem, you need to have one each of rx, tx, fq, and cq per socket. You seem to only have one fq/cq pair for all of them which is not going to work. Note that if you bind sockets to the same netdev and queue_id, then these should share the fq/cq pair like you do today. But this is not what you want, if I understand your example correctly.

In the bpf-examples repo, you can find the AF_XDP-forwarding sample. It created multiple sockets bound to different queue ids all sharing the same umem. Please refer to that for an example.

Forget about the XSK_LIBXDP_FLAGS__INHIBIT_PROG_LOAD for now. If you set this, you have to do everything yourself including loading programs, creating maps, populating them and so on.

**Comment by tjcw** [comment]
Thanks @magnus-karlsson . I think I will need a custom default xdp program, because for my test case when my eBPF pogram returns XDP_PASS I want the packet to go to the kernel, and not be redirected to user space if there is an entry in the xsks map.

**Comment by magnus-karlsson** [comment]
> Thanks @magnus-karlsson . I think I will need a custom default xdp program, because for my test case when my eBPF pogram returns XDP_PASS I want the packet to go to the kernel, and not be redirected to user space if there is an entry in the xsks map.

Got it. Yes, you need your own XDP program.

**Comment by magnus-karlsson** [comment]
For an example on how to create maps, populate them and load the your XDP program yourself using libbpf, you can take a look at the libxdp source code, as it does this for you in the simple case when everything should go to user-space, i.e. when you do not use the INHIBIT.... flag.

**Comment by tjcw** [comment]
The libxdp code doesn't seem to show clearly how to load my XDP program myself. Also that doesn't seem to do what I want; for the case when I load the default program anbd my progran, the "xsks_map" refers to different blocks of storage in the 2 programs, and putting entries into this map means the dafault program sees them and my program doesnt; I instrumented the code and saw that.
My next approach was to revise the default program so that it included the function from my program, but that results in errors in the attached log file.
[log2.txt](https://github.com/xdp-project/xdp-tutorial/files/9734718/log2.txt)
What am I doing wrong ?

**Comment by tjcw** [comment]
I had an error in naming my function xdp_sock_prog where the metadata specified xdp_def_prog . That fixed, I get a failure to load with log lines
```
libxdp: Couldn't find run order struct _xdp_def_prog
libxdp: btf_get_datasec looking for .xdp_run_config found .maps
libxdp: btf_get_datasec looking for .xdp_run_config found .rodata
libxdp: btf_get_datasec looking for .xdp_run_config found .xdp_run_config
libxdp: Couldn't find run order struct _xdp_def_prog
libxdp: Released lock fd 179
libxdp: Found multiprog with id 1834 and 10 component progs
ERROR: Cannot set up socket 9
ERROR: Can't setup AF_XDP sockets "Argument list too long"
xsk_socket__create returns 0
xsk_ring_prod__reserve returns 2048, XSK_RING_PROD__DEFAULT_NUM_DESCS is 2048
xsk_socket__create returns 0
xsk_ring_prod__reserve returns 2048, XSK_RING_PROD__DEFAULT_NUM_DESCS is 2048
xsk_socket__create returns 0
xsk_ring_prod__reserve returns 2048, XSK_RING_PROD__DEFAULT_NUM_DESCS is 2048
xsk_socket__create returns 0
xsk_ring_prod__reserve returns 2048, XSK_RING_PROD__DEFAULT_NUM_DESCS is 2048
xsk_socket__create returns 0
xsk_ring_prod__reserve returns 2048, XSK_RING_PROD__DEFAULT_NUM_DESCS is 2048
xsk_socket__create returns 0
xsk_ring_prod__reserve returns 2048, XSK_RING_PROD__DEFAULT_NUM_DESCS is 2048
xsk_socket__create returns 0
xsk_ring_prod__reserve returns 2048, XSK_RING_PROD__DEFAULT_NUM_DESCS is 2048
xsk_socket__create returns 0
xsk_ring_prod__reserve returns 2048, XSK_RING_PROD__DEFAULT_NUM_DESCS is 2048
xsk_socket__create returns 0
xsk_ring_prod__reserve returns 2048, XSK_RING_PROD__DEFAULT_NUM_DESCS is 2048
xsk_socket__create returns -7
root@r28b29-n10:/home/tjcw/workspace/xdp-tutorial/ebpf-filter# 
```
I am investigating

**Comment by tjcw** [comment]
I now have the function in eBPF that I want, though I have had to put it in the default eBPF program which is not ideal since the server should support multiple eth devices with different eBPF programs. @magnus-karlsson is there something I need to specify to get an xsks map to be shared between the default eBPF program and a user eBPF program ? Also I haven't found the maps in the linux file system yet for sharing with user space programs.
