### ISSUE TITLE
What's the license of this project?

### ISSUE THREAD

**Issue by TyrionQu** [xdp-project/xdp-tutorial#321]
We tried to use some codes of this project into business software, but I can't find any license of this project. Do you have any license to limit business behavior?

**Comment by tohojo** [comment]
GPL 2.0, mostly. The source code files have SPDX headers indicating
this (with a few exceptions).

Note that BPF limits which helpers you can use if your code is not
GPL-compatible, so I'd recommend licensing any BPF code as GPL in any
case...

**Comment by TyrionQu** [comment]
Thanks for your quickly response. Another question for GPL 2.0: if we use these codes as one dynamical libraries and install them into one physical box, should we open all application codes?

**Comment by TyrionQu** [comment]
I also checked kernel xsk.h, which is dual license LGPL-2.1 OR BSD-2-Clause. Why won't it change this project into these two license?

**Comment by tohojo** [comment]
Tyrion Qu ***@***.***> writes:

> I also checked kernel xsk.h, which is dual license LGPL-2.1 OR
> BSD-2-Clause. Why won't it change this project into these two license?

The 'LGPL-2.1 OR BSD-2-Clause' means that the code is licensed under
either license; i.e., you can pick which of those two licenses you want
to comply with when using the code (or do both of course).

As for GPL-2.0, *generally*, if you're linking GPL-2.0 code into your
application, that means the whole application needs to be GPL-2.0.
However, I'm not a lawyer and this is not legal advice; please seek
proper legal council for these kinds of questions...

**Comment by TyrionQu** [comment]
Got it, thanks.
