### ISSUE TITLE
Cannot load an ebpf program with an error "invalid func unknown#177"

### ISSUE THREAD

**Issue by huang195** [xdp-project/xdp-tutorial#326]
So I have a pretty straight forward ebpf code that hooks to sockets, and when a socket goes to `TCP_CLOSE` state, I would like to keep track of some metrics. The relevant code snippet looks like:

```
case BPF_SOCK_OPS_STATE_CB:
       switch(skops->args[1]) {
           case BPF_TCP_CLOSE:
                bpf_printk("remote = %x:%d, local = %x:%d\n", skops->remote_ip4, skops->remote_port, skops->local_ip4, skops->local_port);
                break;
       }
```

This compiles fine, but when trying to load it with `bpftool`, it gives the following cryptic error message:

```
; bpf_printk("remote = %x:%d, local = %x:%d\n", skops->remote_ip4, skops->remote_port, skops->local_ip4, skops->local_port);
13: (61) r1 = *(u32 *)(r6 +24)
14: (7b) *(u64 *)(r10 -48) = r1
15: (61) r1 = *(u32 *)(r6 +64)
16: (77) r1 >>= 16
17: (7b) *(u64 *)(r10 -40) = r1
18: (61) r1 = *(u32 *)(r6 +28)
19: (7b) *(u64 *)(r10 -32) = r1
20: (61) r1 = *(u32 *)(r6 +68)
21: (dc) r1 = be16 r1
22: (7b) *(u64 *)(r10 -24) = r1
23: (bf) r3 = r10
24: (07) r3 += -48
25: (18) r1 = 0xffff9b1a597130d0
27: (b7) r2 = 31
28: (b7) r4 = 32
29: (85) call unknown#177
invalid func unknown#177
processed 35 insns (limit 1000000) max_states_per_insn 0 total_states 2 peak_states 2 mark_read 1
```

The code simply tries to print out remote/local ip and port of a TCP connection before it is closed. I'm not sure what the error message `invalid func unknown#177` is referring to. Any hints on what this might be related to?

Interestingly, I tried to play around with the `bpf_printk()` statement, and if I change it to:

```
bpf_printk("remote = %x:%d, local = %x\n", skops->remote_ip4, skops->remote_port, skops->local_ip4);
```

i.e., not printing out the local port number, this code compiles and loads fine. Not exactly sure how to explain why a simple printk statement would cause the loading to fail.

**Comment by tohojo** [comment]
This is because BPF limits how many arguments you can have to a function
call, which also affects printk. There's a newer helper that lifts this
limitation, but the libbpf version in the xdp-tutorial doesn't have
support for this...

**Comment by huang195** [comment]
@tohojo oh wow, I don't think I would have ever guessed that the error message was related to having too many arguments to bpf_printk() from the error message `invalid func unknown#177`. I knew that error messages are cryptic, but this one is just out there :) Many thanks! This easily saved me days. Closing!
