### ISSUE TITLE
cgroup v1 vs v2

### ISSUE THREAD

**Issue by huang195** [xdp-project/xdp-tutorial#329]
I am playing with sockops examples, and it seems when that cgroupv2 is used, there's no issue attaching a loaded ebpf program to a particular cgroup, but when cgroupv1 is used, how do I do the same attachment?

On the VM where cgroupv2 is used, I see:

```
root@ibm-ebpf1:~# mount | grep cgroup2
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
root@ibm-ebpf1:~# ls /sys/fs/cgroup/unified/
cgroup.controllers  cgroup.max.descendants  cgroup.stat             cgroup.threads  init.scope   kubepods.slice   system.slice
cgroup.max.depth    cgroup.procs            cgroup.subtree_control  cpu.pressure    io.pressure  memory.pressure  user.slice
```

So, after loading a sockops program, I can just do

```
bpftool cgroup attach "/sys/fs/cgroup/unified" sock_ops pinned "/sys/fs/bpf/sockop"
```

This works perfectly as packets of all processes on that system will now get trapped by the attached sockops program.

Cgroupv1 on the other hand splits each type of controller in a different directory, e.g., (this is on a different machine)

```
~/bin # ls /sys/fs/cgroup
blkio             cpu,cpuacct       cpuset            freezer           memory            net_cls,net_prio  perf_event        rdma
cpu               cpuacct           devices           hugetlb           net_cls           net_prio          pids              systemd
```

So how does `bpftool cgroup attach` work with this directory structure? I tried to use a few subdirectories here, e.g., `pids`, `net_cls`, etc., but they all gave the same error message `Error: failed to attach program`. 

Any ideas how to deal with cgroup v1 or it only works with cgroup v2? Thanks!

**Comment by tohojo** [comment]
> Any ideas how to deal with cgroup v1 or it only works with cgroup v2?
> Thanks!

It only works with cgroupv2...

**Comment by huang195** [comment]
@tohojo Good to know. Just encountered an Openshift cluster with only cgroup v1 on the worker nodes and was wondering if the sockops code would work there. Thanks for confirming that it doesn't. Closing.
