### ISSUE TITLE
access to conntrack/nftables from XDP

### ISSUE THREAD

**Issue by huang195** [xdp-project/xdp-tutorial#349]
Is it possible to access conntrack or nftables from an eBPF program attached to XDP? Looking through the list of bpf helper functions, none seem to be relevant. Can someone confirm if this is the current state?

**Comment by tohojo** [comment]
Hai Huang ***@***.***> writes:

> Is it possible to access conntrack or nftables from an eBPF program
> attached to XDP? Looking through the list of bpf helper functions,
> none seem to be relevant. Can someone confirm if this is the current
> state?

Support for lookup up conntrack entries via kfuncs was added by this series:

***@***.***

with write support added by:
***@***.***

The latter went into kernel 6.0...

**Comment by huang195** [comment]
Oh and also, is nftables not accessible via kernel helper functions?

**Comment by tohojo** [comment]
*sigh* - silly github email gateway.

  https://lore.kernel.org/r/20220114163953.1455836-1-memxor@gmail.com

  with write support added by:
  https://lore.kernel.org/r/20220721134245.2450-1-memxor@gmail.com

And no, there's no interface to nftables other than the conntrack lookup...

**Comment by huang195** [comment]
Yep, that worked. Thanks for the pointers! Closing.
