### ISSUE TITLE
Attaching the same XDP program to multiple interfaces

### ISSUE THREAD

**Issue by moscati** [xdp-project/xdp-tutorial#354]
Hi,

In my understanding, if I load an XDP program and attach the same program to multiple interfaces, there will only be a single BPF program in the kernel, and a single map. It will just run on traffic on both interfaces.

My question is how to redirect the packets to the appropriate AF_XDP socket using bpf_redirect_map.

Let's assume I have 2 interfaces (eth0 and eth1) and I have 4 queues on each of them. 
I create 4+4 AF_XDP sockets to whom I would like to redirect the packets.
I don't understand how to define and use xsks_map of type BPF_MAP_TYPE_XSKMAP for this purpose.
It seems that BPF_MAP_TYPE_XSKMAP key is queue index. How can I take in consideration the interface?

**Comment by tohojo** [comment]
You can use anything you like as an index, most examples just use the
queue index. So you could just do:

key = qidx << 32 | ifindex;

or whatever you want. As long as the userspace component populating the
map agrees with the kernel program things will work just fine...

**Comment by moscati** [comment]
I believe that key_size for BPF_MAP_TYPE_XSKMAP should be 32bit because that what bpf_redirect_map expects.
 
Anyway I tried something similar like
key = qidx << 16 | ifindex;

The problem is that BPF_MAP_TYPE_XSKMAP doesn't accept key bigger than max_entries -1.

Is it defined as array map?

**Comment by tohojo** [comment]
Angelo Moscati ***@***.***> writes:

> I believe that key_size for BPF_MAP_TYPE_XSKMAP should be 32bit because that what bpf_redirect_map expects.
>  
> Anyway I tried something similar like
> key = qidx << 16 | ifindex;
>
> The problem is that BPF_MAP_TYPE_XSKMAP doesn't accept key bigger than max_entries -1.
>
> Is it defined as array map?

Yup, it is. You could use a denser packing scheme, or use a separate
hashmap as an indirection for sequential allocation, I suppose...

**Comment by moscati** [comment]
Thanks
