### ISSUE TITLE
Makefile gives error in Ubuntu-20.04

### ISSUE THREAD

**Issue by gookhan** [xdp-project/xdp-tutorial#364]
Hi everybody,

I was following the tutorial and installed the dependencies but when I used configure in the repository, it shows that libbpf support has some problems. Output is shown below:

clang: 12.0.0-3ubuntu1-20.04.5
libbpf support: submodule
ELF support: yes
zlib support: yes
libxdp support: submodule
Configuring libxdp to use our libbpf submodule
Found clang binary 'clang' with version 12 (from 'Ubuntu clang version 12.0.0-3ubuntu1-20.04.5')
not using emacs: 
libbpf support: custom v1.1.0
  perf_buffer__consume support: no
  btf__load_from_kernel_by_id support: no
  btf__type_cnt support: no
  bpf_object__next_map support: no
  bpf_object__next_program support: no
  bpf_program__insn_cnt support: no
  bpf_map_create support: no
  perf_buffer__new_raw support: no
  bpf_xdp_attach support: no
zlib support: yes
ELF support: yes
pcap support: yes
secure_getenv support: yes

I think if I find a way to enable libbpf support, it will solve my problem. If you have any advice, it would be great to hear.

Thanks in advance!

**Comment by carltimmer** [comment]
I have the same problem on the same OS.
I can download and compile the xdp-tools repo and its libxdp and libbpf libraries no problem. 
But compiling those same libs thru xdp-tutorial chokes on libxdp.
It appears that configure runs differently in those 2 repos.

**Comment by carltimmer** [comment]
I cloned a new, clean repo and did "make". Here is the output until the first part of choking on compiling libxdp:


clang: 11.0.0-2~ubuntu20.04.1
libbpf support: submodule
Submodule 'lib/libbpf' (https://github.com/libbpf/libbpf) registered for path 'lib/libbpf'
Submodule 'lib/xdp-tools' (https://github.com/xdp-project/xdp-tools) registered for path 'lib/xdp-tools'
Cloning into '/daqfs/xdp-tutorial/lib/libbpf'...
Cloning into '/daqfs/xdp-tutorial/lib/xdp-tools'...
Submodule path 'lib/libbpf': checked out '1596a09b5de2a50ab8d44218fc29b6d42f886305'
Submodule path 'lib/xdp-tools': checked out 'cdd93184d18ceaf2200ec4bf63a30b7e11938177'
ELF support: yes
zlib support: yes
libxdp support: submodule
Configuring libxdp to use our libbpf submodule
Found clang binary 'clang' with version 11 (from 'Ubuntu clang version 11.0.0-2~ubuntu20.04.1')
not using emacs: 
libbpf support: custom v1.1.0
  perf_buffer__consume support: no
    gcc -o config.FhZhNi/libbpftest config.FhZhNi/libbpftest.c -Werror -Iconfig.FhZhNi/include -Xlinker --unresolved-symbols=ignore-in-object-files
    In file included from config.FhZhNi/libbpftest.c:1:
    config.FhZhNi/include/bpf/libbpf.h:70:54: error: ‘enum bpf_link_type’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
       70 | LIBBPF_API const char *libbpf_bpf_link_type_str(enum bpf_link_type t);
          |                                                      ^~~~~~~~~~~~~
    In file included from config.FhZhNi/libbpftest.c:3:
    config.FhZhNi/include/bpf/btf.h:208:14: error: ‘enum btf_func_linkage’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
      208 |         enum btf_func_linkage linkage, int proto_type_id);
          |              ^~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
  btf__load_from_kernel_by_id support: no
    gcc -o config.FhZhNi/libbpftest config.FhZhNi/libbpftest.c -Werror -Iconfig.FhZhNi/include -Xlinker --unresolved-symbols=ignore-in-object-files
    In file included from config.FhZhNi/libbpftest.c:1:
    config.FhZhNi/include/bpf/libbpf.h:70:54: error: ‘enum bpf_link_type’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
       70 | LIBBPF_API const char *libbpf_bpf_link_type_str(enum bpf_link_type t);
          |                                                      ^~~~~~~~~~~~~
    In file included from config.FhZhNi/libbpftest.c:3:
    config.FhZhNi/include/bpf/btf.h:208:14: error: ‘enum btf_func_linkage’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
      208 |         enum btf_func_linkage linkage, int proto_type_id);
          |              ^~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
  btf__type_cnt support: no
    gcc -o config.FhZhNi/libbpftest config.FhZhNi/libbpftest.c -Werror -Iconfig.FhZhNi/include -Xlinker --unresolved-symbols=ignore-in-object-files
    In file included from config.FhZhNi/libbpftest.c:1:
    config.FhZhNi/include/bpf/libbpf.h:70:54: error: ‘enum bpf_link_type’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
       70 | LIBBPF_API const char *libbpf_bpf_link_type_str(enum bpf_link_type t);
          |                                                      ^~~~~~~~~~~~~
    In file included from config.FhZhNi/libbpftest.c:3:
    config.FhZhNi/include/bpf/btf.h:208:14: error: ‘enum btf_func_linkage’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
      208 |         enum btf_func_linkage linkage, int proto_type_id);
          |              ^~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
  bpf_object__next_map support: no
    gcc -o config.FhZhNi/libbpftest config.FhZhNi/libbpftest.c -Werror -Iconfig.FhZhNi/include -Xlinker --unresolved-symbols=ignore-in-object-files
    In file included from config.FhZhNi/libbpftest.c:1:
    config.FhZhNi/include/bpf/libbpf.h:70:54: error: ‘enum bpf_link_type’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
       70 | LIBBPF_API const char *libbpf_bpf_link_type_str(enum bpf_link_type t);
          |                                                      ^~~~~~~~~~~~~
    In file included from config.FhZhNi/libbpftest.c:3:
    config.FhZhNi/include/bpf/btf.h:208:14: error: ‘enum btf_func_linkage’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
      208 |         enum btf_func_linkage linkage, int proto_type_id);
          |              ^~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
  bpf_object__next_program support: no
    gcc -o config.FhZhNi/libbpftest config.FhZhNi/libbpftest.c -Werror -Iconfig.FhZhNi/include -Xlinker --unresolved-symbols=ignore-in-object-files
    In file included from config.FhZhNi/libbpftest.c:1:
    config.FhZhNi/include/bpf/libbpf.h:70:54: error: ‘enum bpf_link_type’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
       70 | LIBBPF_API const char *libbpf_bpf_link_type_str(enum bpf_link_type t);
          |                                                      ^~~~~~~~~~~~~
    In file included from config.FhZhNi/libbpftest.c:3:
    config.FhZhNi/include/bpf/btf.h:208:14: error: ‘enum btf_func_linkage’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
      208 |         enum btf_func_linkage linkage, int proto_type_id);
          |              ^~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
  bpf_program__insn_cnt support: no
    gcc -o config.FhZhNi/libbpftest config.FhZhNi/libbpftest.c -Werror -Iconfig.FhZhNi/include -Xlinker --unresolved-symbols=ignore-in-object-files
    In file included from config.FhZhNi/libbpftest.c:1:
    config.FhZhNi/include/bpf/libbpf.h:70:54: error: ‘enum bpf_link_type’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
       70 | LIBBPF_API const char *libbpf_bpf_link_type_str(enum bpf_link_type t);
          |                                                      ^~~~~~~~~~~~~
    In file included from config.FhZhNi/libbpftest.c:3:
    config.FhZhNi/include/bpf/btf.h:208:14: error: ‘enum btf_func_linkage’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
      208 |         enum btf_func_linkage linkage, int proto_type_id);
          |              ^~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
  bpf_map_create support: no
    gcc -o config.FhZhNi/libbpftest config.FhZhNi/libbpftest.c -Werror -Iconfig.FhZhNi/include -Xlinker --unresolved-symbols=ignore-in-object-files
    In file included from config.FhZhNi/libbpftest.c:1:
    config.FhZhNi/include/bpf/libbpf.h:70:54: error: ‘enum bpf_link_type’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
       70 | LIBBPF_API const char *libbpf_bpf_link_type_str(enum bpf_link_type t);
          |                                                      ^~~~~~~~~~~~~
    In file included from config.FhZhNi/libbpftest.c:3:
    config.FhZhNi/include/bpf/btf.h:208:14: error: ‘enum btf_func_linkage’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
      208 |         enum btf_func_linkage linkage, int proto_type_id);
          |              ^~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
  perf_buffer__new_raw support: no
    gcc -o config.FhZhNi/libbpftest config.FhZhNi/libbpftest.c -Werror -Iconfig.FhZhNi/include -Xlinker --unresolved-symbols=ignore-in-object-files
    In file included from config.FhZhNi/libbpftest.c:1:
    config.FhZhNi/include/bpf/libbpf.h:70:54: error: ‘enum bpf_link_type’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
       70 | LIBBPF_API const char *libbpf_bpf_link_type_str(enum bpf_link_type t);
          |                                                      ^~~~~~~~~~~~~
    In file included from config.FhZhNi/libbpftest.c:3:
    config.FhZhNi/include/bpf/btf.h:208:14: error: ‘enum btf_func_linkage’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
      208 |         enum btf_func_linkage linkage, int proto_type_id);
          |              ^~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
  bpf_xdp_attach support: no
    gcc -o config.FhZhNi/libbpftest config.FhZhNi/libbpftest.c -Werror -Iconfig.FhZhNi/include -Xlinker --unresolved-symbols=ignore-in-object-files
    In file included from config.FhZhNi/libbpftest.c:1:
    config.FhZhNi/include/bpf/libbpf.h:70:54: error: ‘enum bpf_link_type’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
       70 | LIBBPF_API const char *libbpf_bpf_link_type_str(enum bpf_link_type t);
          |                                                      ^~~~~~~~~~~~~
    In file included from config.FhZhNi/libbpftest.c:3:
    config.FhZhNi/include/bpf/btf.h:208:14: error: ‘enum btf_func_linkage’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
      208 |         enum btf_func_linkage linkage, int proto_type_id);
          |              ^~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
zlib support: yes
ELF support: yes
pcap support: yes
secure_getenv support: yes

lib
make[1]: Warning: File '../config.mk' has modification time 122 s in the future

  libbpf
    CC       install/lib/libbpf.a
make[2]: Warning: File 'Makefile' has modification time 121 s in the future
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
    INSTALL  install/lib/libbpf.a
make[2]: Warning: File 'Makefile' has modification time 108 s in the future
make[2]: warning:  Clock skew detected.  Your build may be incomplete.

  libxdp
    CC       install/lib/libxdp.a
make[2]: Warning: File 'version.mk' has modification time 108 s in the future
make[3]: Warning: File '../version.mk' has modification time 108 s in the future
make[4]: Warning: File '../../version.mk' has modification time 108 s in the future
libxdp.c:244:20: error: static declaration of ‘btf__load_from_kernel_by_id’ follows non-static declaration
  244 | static struct btf *btf__load_from_kernel_by_id(__u32 id)
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libxdp.c:30:
/daqfs/xdp-tutorial/lib/install/include/bpf/btf.h:120:24: note: previous declaration of ‘btf__load_from_kernel_by_id’ was here
  120 | LIBBPF_API struct btf *btf__load_from_kernel_by_id(__u32 id);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by tohojo** [comment]
Carl Timmer ***@***.***> writes:

> I cloned a new, clean repo and did "make". Here is the output until
> the first part of choking on compiling libxdp:

Right, thanks! I think this is actually a bug that we fixed in xdp-tools
a while ago, but the submodule in the tutorial is out of date. Let me
fix that...

**Comment by tohojo** [comment]
Please try the latest master. You'll need to do a `git submodule update` after pulling (or just try with a clean checkout).

**Comment by carltimmer** [comment]
That worked! Thanks!

**Comment by tohojo** [comment]
Carl Timmer ***@***.***> writes:

> That worked! Thanks!

Awesome! You're welcome :)
