### ISSUE TITLE
After running "make" it says, config.mk: No such file or directory

### ISSUE THREAD

**Issue by Zapperdax** [xdp-project/xdp-tutorial#366]
$ make
../lib/defines.mk:4: ../lib/../config.mk: No such file or directory
make: *** No rule to make target '../lib/../config.mk'.  Stop.

I installed all the dependencies, and tried running the first basic01-xdp-pass, and encountered this issue.

**Comment by shivkumar301** [comment]
I was also facing the same issue:

Try this:
$ cd xdp-tutorial
$ sudo ./configure
$ make

This will configure the libraries and compile all the programs inside xdp-tutorial.
It worked for me.
After that, you can compile the program by running the "make" command in individual folders.

**Comment by Zapperdax** [comment]
Yes @shivkumar301 , it worked after I did that. Thanks

**Comment by liulangwa** [comment]
thanks
