### ISSUE TITLE
Xdp mode via api? 

### ISSUE THREAD

**Issue by Adarsh97** [xdp-project/xdp-tutorial#372]
How can we know the mode in which xdp is loaded in the system, the mode means driver mode (native) skb mode( generic) or hw mode? 
Do we have any api for checking the mode the system is supporting? 
@magnus-karlsson @tohojo @davem330 @dmitris

**Comment by magnus-karlsson** [comment]
You have the netdev_xdp_act you can use to probe for various XDP support. You find it in linux/netdev.h.
