### ISSUE TITLE
Can AF XDP modify tcp payload in user-space

### ISSUE THREAD

**Issue by xd121614** [xdp-project/xdp-tutorial#377]
I use AF XDP redirect traffic to user-space program successfully. And user-space program just print and forward the packet. Is it possible to do some complex action, such as drop or modify tcp payload(pkt len maybe changed)? So that AF XDP technology could be used in the application-layer-firewall or db-firewall field.

**Comment by xd121614** [comment]
What I know it's easy to drop(don't put pkt in tx queue), but hard to modify tcp payload when modify pkt len > raw pkt len.
Is there some opensource example for action modify and forward new pkt with different len.

**Comment by tohojo** [comment]
xd121614 ***@***.***> writes:

> What I know it's easy to drop(don't put pkt in tx queue), but hard to
> modify tcp payload when modify pkt len > raw pkt len.

Ah, right, if by "modify the TCP payload" you mean "build a full-fledged
TCP middlebox" then yeah, you're going to have to do some more work that
just modifying the packet contents.

> Is there some opensource example for action modify and forward new pkt
> with different len.

No idea. TCP middleboxes fall squarely into the "don't do that" category
for me personally, so I have no interest in helping with this, sorry.

**Comment by xd121614** [comment]
Not extractly full-fledged.Just modify pkt and put it in tx. What confused me is that how to adjust tx xdp_desc
struct xdp_desc {
	__u64 addr;
	__u32 len;
	__u32 options;
}
When pkt len changed ,addr and len also need change.
