### ISSUE TITLE
About umem frame_headroom

### ISSUE THREAD

**Issue by hi-glenn** [xdp-project/xdp-tutorial#386]
kernel space side:
```c
...

bpf_xdp_adjust_head(ctx, -4);

return bpf_redirect_map(&xsk_map, 0, 0);
```

userspace side:
```c
struct xsk_umem_config cfg = {
	.fill_size = XSK_RING_PROD__DEFAULT_NUM_DESCS * 2,
	.comp_size = XSK_RING_CONS__DEFAULT_NUM_DESCS,
	.frame_size = opt_xsk_frame_size,
	.frame_headroom = 4,
	.flags = opt_umem_flags
};
```

My code as the above,  I want to add some info into the headroom in kernel space, and get the info in userspace, then reuse the packet (swap mac, addr, port) and send it back ignoring the headroom.

And now,  I use `xsk_umem__get_data(mem_ptr, addr)`  to read the pkt.  And the pkt start with the info (inserted in kernel space),  not the orginal received pkt.

[docs](https://docs.kernel.org/networking/af_xdp.html) say ` There is also an option to set the headroom of each single buffer in the UMEM. If you set this to N bytes, it means that the packet will start N bytes into the buffer leaving the first N bytes for the application to use. The final option is the flags field, but it will be dealt with in separate sections for each UMEM flag.`

I am confused. Where did I misunderstand ?

**Comment by hi-glenn** [comment]
> XDP guarantees that there will be 256 bytes of headroom before the packet, so you do not need to use the frame_headroom option. It is just extra on top of that. In the XDP program, I would use bpf_xdp_adjust_meta() to indicate how much metadata you want to be provided to user-space before the packet. In user space, addr in the descriptor would then point to the packet and 4 bytes before that you would find your metadata.

According to the method you mentioned, I have obtained the result I wanted, thanks a lot for your timely and detailed answer.

However, I am still confused. When should I use frame_headroom and `bpf_xdp_adjust_head()` ?

**Comment by magnus-karlsson** [comment]
You can use frame_headroom e.g., to align your packet + metadata on a cache line boundary for performance reasons or if you need more than 256 bytes of headroom. Use bpf_xdp_adjust_head if you want to grow or shrink your packet (not your metadata) from its head.
