### ISSUE TITLE
Is AF_XDP socket thread-safe for TX ring and other rings ?

### ISSUE THREAD

**Issue by incapdns** [xdp-project/xdp-tutorial#391]
Suppose I have two AF_XDP sockets (two XSK).

Each xsk socket was passed as a parameter to the thread (max two threads) and both XSK socket share the same UMEM

1. Is it safe to call `xsk_ring_prod__reserve(&xsk->tx, 1, &idx_tx)` on both threads concurrently without a blocking mechanism taking into account that they both share the same UMEM?

2. I must implement a blocking mechanism before calling: `xsk_ring_prod__reserve(&umem->fq, 1, &idx_fq);` in both threads ?

**Comment by magnus-karlsson** [comment]
1 is safe as long as xsk->tx refers to different sockets in the two threads which seems to be the case in your example. On the other hand, having multiple threads use the same socket is not thread safe.

2: Depends. If you bound the two sockets to the same netdev and queue_id, then yes as there is only one fq. If you bind the sockets to different queue ids (or netdevs), then you end up with two separate fqs (one for each socket) and you do not have this problem.

**Comment by incapdns** [comment]
> If you bind the sockets to different queue ids (or netdevs), then you end up with two separate fqs (one for each socket) and you do not have this problem.

So if I have two xsk sockets associated with different queues on the same interface, I don't need to implement locks on `umem->fq` even if the same umem is associated with both sockets?

**Comment by incapdns** [comment]
Oh, sorry, I misinterpreted your answer, now stopping to think, you meant "two separate fqs", therefore, it means two umem for each one.

Am I right ?

**Comment by magnus-karlsson** [comment]
> So if I have two xsk sockets associated with different queues on the same interface, I don't need to implement locks on umem->fq even if the same umem is associated with both sockets?

Correct.

> Oh, sorry, I misinterpreted your answer, now stopping to think, you meant "two separate fqs", therefore, it means two umem for each one.

No, you have one umem but two separate fqs that both go to that single umem. Check the documentation about SHARED_UMEM mode in Documentation/networking/af_xdp.rst and/or by checking the AF_XDP-forwarding example in this repo: https://github.com/xdp-project/bpf-examples if you need some examples.

So your first hunch was correct :-).

**Comment by incapdns** [comment]
I apologize for the delay in responding, but I checked the code mentioned, and realized that it is indeed possible, just use xsk_socket__create_shared and pass the Fill and Completion queue parameter instead of the xsk_socket__create function.

But what is the purpose of the `xsk_prod_nb_free` function used in line 1054 (https://github.com/xdp-project/bpf-examples/blob/master/AF_XDP-interaction/af_xdp_user.c) ?

**Comment by magnus-karlsson** [comment]
It is used to check how many entries that are free in the ring. This so that the whole ring can be filled with entries a couple of lines later. Note that xsk_ring_prod__reserve(fq, N, &idx) returns 0 if N entries are not available. This makes sure that will never happen.

**Comment by incapdns** [comment]
So let me see if I understand, I will make some statements to review my knowledge acquired so far:

[Considering I only have one netdev / interface on the system, eth0]

1. It is **not** possible to have two XSK sockets **that have their own respective FILL/COMPLETION rings** pointing to the same queue, example:
```
xsk_socket__create_shared(
        &xsk->xsk,
        opt_if,
        0,
        umem->umem,
        &xsk->rx,
        &xsk->tx,
        &xsk->fq,
        &xsk->cq,
        &cfg
    );
```
Another XSK:
```
xsk_socket__create_shared(
        &xsk->xsk,
        opt_if,
        0,
        umem->umem,
        &xsk->rx,
        &xsk->tx,
        &xsk->fq,
        &xsk->cq,
        &cfg
    );
```

That said, in the next call to xsk_socket__create_shared, I must specify another queue_id so that the xsk_ring_prod struct is initialized correctly, or pass null

2. The rings present in xsk_socket_info (rx/tx/fq/cq) have their own memory region, this means that even if they share the same UMEM, I can create a thread for each xsk socket and perform produce and consume calls without me worry about co-occurrence (as long as only one thread is associated with each xsk, that is, one thread for each xsk)

3. To complement 2., if I only have an FQ and CQ, for example, initialized together when creating the UMEM, I need to block when producing the FILL

**Comment by magnus-karlsson** [comment]
Correct on all three accounts.

**Comment by incapdns** [comment]
Thank you very much for the support.
