### ISSUE TITLE
What is the solution to reusing pinned maps?

### ISSUE THREAD

**Issue by hbina** [xdp-project/xdp-tutorial#428]
https://github.com/xdp-project/xdp-tutorial/blob/717f2546641a161312f085b326a6a4cbff494f8d/basic04-pinning-maps/README.org?plain=1#L148

I don't see anything that is remotely similar to this?

```c
int pinned_map_fd = bpf_obj_get("/sys/fs/bpf/veth0/xdp_stats_map");
struct bpf_object *obj = bpf_object__open(cfg.filename);
struct bpf_map    *map = bpf_object__find_map_by_name(obj, "xdp_stats_map");
bpf_map__reuse_fd(map, pinned_map_fd);
bpf_object__load(obj);
```

Is it a matter of passing the "reuse-maps" option? That doesn't really make sense when the assignment says to check if the map already exists, otherwise create. This is just not going to create it?

**Comment by cataldor** [comment]
Hello @hbina 
I'm still learning XDP, but i can try to help you with this.. hopefully it is not too late.

I think to understand this issue better, we need to separate the problem and the solution.

First what are we trying to achieve? basically, when someone has reloaded a BPF program we want to (i) detect it and (ii) reuse the existing map (as discussed in the tutorial, we do not want to restart the counters from zero)

To detect it, the assignment 1 discusses some possibilities (map id, bpf program id, ...)

Once you have detected it, you have two options: (i) assignment 1: just reload the bpf program, without reusing anything. This should make all counters zero. (ii) assignment 2: reuse the existing map.

This reusing operation is what you have pasted here. Basically you will load the new bpf program (pointed by `cfg.filename`), but swap the bpf mapped pin for your existing fd (from the previous BPF). This way you can keep the counter values.
