### ISSUE TITLE
Avoid loading and attaching xdp_dispatcher

### ISSUE THREAD

**Issue by pvvm** [xdp-project/xdp-tutorial#435]
Hello,
Is it possible to avoid loading xdp_dispatcher and, instead, directly load the XDP program I want using **load_bpf_and_xdp_attach** function from this tutorial or **xdp_program__attach?**
For example, even if my system supports xdp_dispatcher, I want it to load the program directly, without a xdp_dispatcher intermediating the process.

**Comment by pvvm** [comment]
I found a way to do that using **bpf_xdp_attach** instead of **xdp_program__attach**. But before that I had to get the **bpf_object**, load it, get a **bpf_program** using **bpf_object__next_program**, and finally attaching with **bpf_xdp_attach**.

**Comment by tohojo** [comment]
Pedro Mizuno ***@***.***> writes:

> I found a way to do that using **bpf_xdp_attach** instead of
> **xdp_program__attach**. But before that I had to get the
> **bpf_object**, load it, get a **bpf_program** using
> **bpf_object__next_program**, and finally attaching with
> **bpf_xdp_attach**.

If you're doing this you might as well skip using libxdp at all, and
just use libbpf natively :)

I am curious why you need to skip the dispatcher?

**Comment by tohojo** [comment]
Pedro Mizuno ***@***.***> writes:

> So, I'm stuck with this other problem. Would you know a way to run
> bpf_prog_test_run_opts on a program attached to the dispatcher?

Yes! There's xdp_program__test_run() for exactly this purpose :)

You can use it with a program that has not been loaded at all, or you
can use it with one that has already been attached to a dispatcher (as
long as your kernel is new enough to support multiple attachments of the
same program)

**Comment by pvvm** [comment]
Oh wow! That's really great, I've just tested it and it's working well! Thank you very much!

And the only thing that keeps bugging me is the following message, that is spammed when I run that function:
"libbpf: elf: skipping unrecognized data section(7) xdp_metadata"
Would you know what this is about?

Also, would you know if there is any documentation listing the functions from libbpf and libxdp, what they do, etc? Because sometimes finding a proper one to use can be a bit challenging

**Comment by tohojo** [comment]
Pedro Mizuno ***@***.***> writes:

> Oh wow! That's really great, I've just tested it and it's working well! Thank you very much!
>
> And the only thing that keeps bugging me is the following message, that is spammed when I run that function:
> "libbpf: elf: skipping unrecognized data section(7) xdp_metadata"
> Would you know what this is about?

Yeah, that particular wart we never did manage to get rid of. Basically,
libbpf insists on owning all section names, and emits warnings for
anything it doesn't know about. You can silence the warning by changing
the libbpf logging function (see silence_libbpf_logging() in the
xdp-tools source tree for an example of how to do this).

> Also, would you know if there is any documentation listing the
> functions from libbpf and libxdp, what they do, etc? Because sometimes
> finding a proper one to use can be a bit challenging

The most comprehensive listing of functions is in the respective header
files. We do have a man page for libxdp, but it's not quite
comprehensive, I'm afraid. I am not aware of any authoritative
documentation for libbpf.

**Comment by pvvm** [comment]
Oh that's good to know, thanks!

Also, is it possible to redirect the frame tested with xdp_program__test_run back with AF_XDP (maybe BPF_F_TEST_XDP_LIVE_FRAMES)? For example, I call xdp_program__test_run and send a frame, do something with it in the XDP program, and use bpf_redirect_map to send it back with AF_XDP.

If not, can we "inject" a frame into UMEM and send it using the TX path of AF_XDP?

**Comment by tohojo** [comment]
Pedro Mizuno ***@***.***> writes:

> Oh that's good to know, thanks!
>
> Also, is it possible to redirect the frame tested with
> xdp_program__test_run back with AF_XDP (maybe
> BPF_F_TEST_XDP_LIVE_FRAMES)? For example, I call xdp_program__test_run
> and send a frame, do something with it in the XDP program, and use
> bpf_redirect_map to send it back with AF_XDP.
>
> If not, can we "inject" a frame into UMEM and send it using the TX
> path of AF_XDP?

Erm, huh? Why would you want to do that? If you're injecting the packet
from userspace in the first place, why not just send it out directly via
AF_XDP?

**Comment by pvvm** [comment]
In a project I'm working on right now, ideally, I would have all processing related to sending and receiving packets done in an XDP program. So, when a machine that has the XDP program wants to send a packet out, it triggers the XDP program with bpf_prog_run, does the required processing to create a packet, and redirect it with AF_XDP to, then, use the TX path.
And I agree that it might cause unnecessary overhead to keep doing it in XDP and going across AF_XDP, instead of directly injecting from userspace. But it would be great to have a way to do that anyway, so I could compare both approaches, if both are possible ofc.
So, is it possible to redirect a packet from bpf_prog_run using AF_XDP? I tried using BPF_F_TEST_XDP_LIVE_FRAMES, and it doesn't seem to be working in my case.
Also, from what I understood, it is possible to inject packets from userspace, correct? Would you have any leads to where I can find more information about it?

**Comment by tohojo** [comment]
Pedro Mizuno ***@***.***> writes:

> In a project I'm working on right now, ideally, I would have all processing related to sending and receiving packets done in an XDP program. So, when a machine that has the XDP program wants to send a packet out, it triggers the XDP program with bpf_prog_run, does the required processing to create a packet, and redirect it with AF_XDP to, then, use the TX path.
> And I agree that it might cause unnecessary overhead to keep doing it in XDP and going across AF_XDP, instead of directly injecting from userspace. But it would be great to have a way to do that anyway, so I could compare both approaches, if both are possible ofc.
> So, is it possible to redirect a packet from bpf_prog_run using AF_XDP? I tried using BPF_F_TEST_XDP_LIVE_FRAMES, and it doesn't seem to be working in my case.
> Also, from what I understood, it is possible to inject packets from userspace, correct? Would you have any leads to where I can find more information about it?

But why does AF_XDP need to be in the picture here. With
BPF_F_TEST_XDP_LIVE_FRAMES you can just redirect the packet directly to
the interface you want to sent it out to, no reason to take another trip
through userspace...

The best example to look at for this is probably the source code of
xdp-trafficgen:
https://github.com/xdp-project/xdp-tools/tree/master/xdp-trafficgen

**Comment by pvvm** [comment]
Sorry, I wasn't clear about this part. I might need to send packets back to userspace in order handle scheduling for sending packets there. It doesn't seem viable or easy for me to do that in XDP.
Also, sorry for this trivial question, but is it possible to use bpf_redirect() to send packets out from the same interface that is receiving packets?

**Comment by tohojo** [comment]
Pedro Mizuno ***@***.***> writes:

> Sorry, I wasn't clear about this part. I might need to send packets
> back to userspace in order handle scheduling for sending packets
> there.

Right, but then why not just send them directly using AF_XDP instead of
going through bpf_prog_run()?

> It doesn't seem viable or easy for me to do that in XDP.

Not currently, no.

> Also, sorry for this trivial question, but is it possible to use
> bpf_redirect() to send packets out from the same interface that is
> receiving packets?

Yup, that corresponds semantically to just returning XDP_TX, but the
frame takes a detour through the redirect code path, whereas XDP_TX is
handled directly in the driver. But sure, certainly possible :)

**Comment by pvvm** [comment]
> Right, but then why not just send them directly using AF_XDP instead of going through bpf_prog_run()?

Yeah, it seems that sending directly from userspace using AF_XDP seems a better choice. My initial idea was to have both sides of packet processing (send and receive) be done in the XDP program, for sake of following a single path, instead of having one at XDP and another at userspace.
So, I imagine that for packets I want to send from userspace I can do all its processing at userspace and send it through XDP, while packets received from the network, I'll process them XDP and, perhaps, redirect it to AF_XDP.

> Yup, that corresponds semantically to just returning XDP_TX, but the frame takes a detour through the redirect code path, whereas XDP_TX is handled directly in the driver. But sure, certainly possible :)

Oh that makes sense. Thank you very much for all the help!

**Comment by tohojo** [comment]
Pedro Mizuno ***@***.***> writes:

>> Right, but then why not just send them directly using AF_XDP instead of going through bpf_prog_run()?
>
> Yeah, it seems that sending directly from userspace using AF_XDP seems a better choice. My initial idea was to have both sides of packet processing (send and receive) be done in the XDP program, for sake of following a single path, instead of having one at XDP and another at userspace.
> So, I imagine that for packets I want to send from userspace I can do all its processing at userspace and send it through XDP, while packets received from the network, I'll process them XDP and, perhaps, redirect it to AF_XDP.

Yeah, that would make sense semantically, but to work well we would need
a proper TX path hook. bpf_prog_run() can serve as a replacement, but
it's a little hacky, and probably won't perform well.

One thing you could try to get this symmetry is to run everything
through a veth pair. So you attach an AF_XDP socket to one end of a
veth, and then you run an XDP program on the other end, and one on the
physical NIC. Then you can just redirect back and forth between the
physical NIC and the veth device, and gain symmetry that way. It does
have some overhead, but I'm pretty sure it will perform better than
anything involving bpf_prog_run()...

>> Yup, that corresponds semantically to just returning XDP_TX, but the frame takes a detour through the redirect code path, whereas XDP_TX is handled directly in the driver. But sure, certainly possible :)
>
> Oh that makes sense. Thank you very much for all the help!

You're welcome!

**Comment by pvvm** [comment]
Just one more question, is there any function from libbpf or libxdp that allows for injection of packets to UMEM, for it to be sent using AF_XDP?

**Comment by tohojo** [comment]
Pedro Mizuno ***@***.***> writes:

> Just one more question, is there any function from libbpf or libxdp
> that allows for injection of packets to UMEM, for it to be sent using
> AF_XDP?

What do you mean, "injection to umem"? The umem buffers are just memory
areas in userspace, you just memcpy() to them?

**Comment by pvvm** [comment]
Oh that makes sense. I was wondering is there was anything fancier.
Thanks again!
