### ISSUE TITLE
A solution for basic04 would be helpful

### ISSUE THREAD

**Issue by DoctorSher** [xdp-project/xdp-tutorial#46]
First, thank you for these tutorial resources. It's awesome that you're putting this out there.

I am struggling with basic04 assignment 1. After a certain amount of beating my head against the wall, it would be helpful if I could look at a solution (or an example program which solves this problem) to understand the changes and move on. However, the tutorial doesn't have a solution for this step. After a fair amount of digging around, I thought about skipping this assignment and moving on, but the next step in the tutorial (packet01) pulls in *our* solution from basic04 via Makefile, so it seems like I cannot move on without solving it. 

So I am not asking for things empty-handed, here are the things that I have tried:
1. Use `bpf_obj_get` to retrieve the file descriptor for the pinned map by supplying the pathname to the pinned map file in bpffs. I do not understand why, but each call to `bpf_obj_get` increments the fd by 1. So if my initial map_fd is 3, `bpf_obj_get` will return 4, 5, 6, etc... Some [other documentation](https://prototype-kernel.readthedocs.io/en/latest/bpf/ebpf_maps.html) recommended [this program](https://github.com/netoptimizer/prototype-kernel/blob/master/kernel/samples/bpf/xdp_ddos01_blacklist_cmdline.c) for example usage of `bpf_obj_get` and has a very similar format to our program, but it also does not solve this specific problem (it is a TODO).
2. The assignment suggests to remember the original map_id. So I took the map_id from the info struct populated by the original call to `check_map_fd_info` in main, and passed it into the `stats_poll` function. For each poll loop, I use `bpf_obj_get_info_by_fd` to see if the map_id has changed at that particular file descriptor. However, it never changes, despite me loading a new BPF map with xdp_loader. I assume the problem is I am getting the map_id from the original map file descriptor, and the new map has a different file descriptor. If this is true, that would imply I need to probe when the file descriptor changes, which takes me back to the solution I tried previously and does not work.

Although having a solution in the tutorial would probably be best to ensure the tutorial is self contained, that may be more appropriate in the long term. In the short term, any help is appreciated. Thanks.

**Comment by DoctorSher** [comment]
As an update: I was not using bpf_obj_get correctly for attempt 1 (it is expected that it would increment the fd every time). I am still not sure what the canonical way to do this assignment would be, but I just called `stat` on the pinned map pathname to see if it changed. A bit out-of-band but it gets the job done so I could move on.

**Comment by tohojo** [comment]
Adam Drescher <notifications@github.com> writes:

> As an update: I was not using bpf_obj_get correctly for attempt 1 (it
> is expected that it would increment the fd every time). I am still not
> sure what the canonical way to do this assignment would be, but I just
> called `stat` on the pinned map pathname to see if it changed. A bit
> out-of-band but it gets the job done so I could move on.

Great that you managed to progress! But you're right, a solution would
probably be useful. Will keep this issue open until we get around to
writing one :)
