### ISSUE TITLE
Parsing the IP header

### ISSUE THREAD

**Issue by FOSquare** [xdp-project/xdp-tutorial#47]
I was struggling with the assignment of parsing the IP header

See my code below:
static __always_inline int parse_ip6hdr(struct hdr_cursor *nh,
                                        void *data_end,
                                        struct ipv6hdr **ip6hdr)
{
        struct ipv6hdr *ip6h = *nexthdr;
        if (ip6h + 1 > data_end)
                return -1;
}

There is complain of nexthdr,  I check the definition of the ipv6.h.
I tried struct ipv6hdr         struct ipv6hdr *ip6h = **ip6hdr.nexthdr and  struct ipv6hdr *ip6h = &(nh->pos);
it does not work neither. 
Could you provide me with a correct sentence of parsing the IP header. Thanks a lot.

**Comment by tohojo** [comment]
FOSquare <notifications@github.com> writes:

> I was struggling with the assignment of parsing the IP header
>
> See my code below:
> static __always_inline int parse_ip6hdr(struct hdr_cursor *nh,
>                                         void *data_end,
>                                         struct ipv6hdr **ip6hdr)
> {
>         struct ipv6hdr *ip6h = *nexthdr;
>         if (ip6h + 1 > data_end)
>                 return -1;
> }
>
> There is complain of nexthdr,  I check the definition of the ipv6.h.
> I tried struct ipv6hdr         struct ipv6hdr *ip6h = **ip6hdr.nexthdr and  struct ipv6hdr *ip6h = &(nh->pos);
> it does not work neither.

The nh->pos element is already a void pointer, so you can just do

	struct ipv6hdr *ip6h = nh->pos;

**Comment by FOSquare** [comment]
Thank you so much, it is working. 

64 bytes from fc00:dead:cafe:1::1: icmp_seq=2 ttl=64 time=0.054 ms
64 bytes from fc00:dead:cafe:1::1: icmp_seq=4 ttl=64 time=0.049 ms
64 bytes from fc00:dead:cafe:1::1: icmp_seq=6 ttl=64 time=0.044 ms
