### ISSUE TITLE
Should we change parse_ethhdr helper?

### ISSUE THREAD

**Issue by netoptimizer** [xdp-project/xdp-tutorial#59]
@tohojo changed parse_ethhdr() to skip VLANs in commit 455cb401ae9 to skip all VLAN headers, and lets the return value be in host byte order.

1. Is it good/expected that VLANs are skipped?

As ethhdr pointer still points to the original, thus callers can still detect this is a VLAN packet, by looking at eth->h_proto, and use proto_is_vlan(eth->h_proto).  Which is that @aspsk did in solution to packet02 ([packet-solutions/xdp_prog_kern_02.c](https://github.com/xdp-project/xdp-tutorial/blob/master/packet-solutions/xdp_prog_kern_02.c#L84))

2. ```h_proto``` being return as host byte order also seems wrong.

First of all, it's not a constant thus compiler cannot do this compile-time.
Second, cannot use ```proto_is_vlan()``` in the return value, as this helper expect network-byte-order.

**Comment by tohojo** [comment]
Yeah, I think we could probably lose the bpf_nthos() call, but I think
the helper is most useful as-is wrt. eating the VLAN tags...

**Comment by netoptimizer** [comment]
I'm working on this... but I noticed that the loop unroll, that does the VLAN header parsing is sometimes removed and optimized out by the compiler.  This needs some more investigations...

It actually happens for ```xdp_vlan_swap_func``` in [packet-solutions/xdp_prog_kern_02.c](https://github.com/xdp-project/xdp-tutorial/blob/master/packet-solutions/xdp_prog_kern_02.c#L69)

Hint I inspect the BPF byte-code via this command:
```
 llvm-objdump -S packet-solutions/xdp_prog_kern_02.o
```

**Comment by tohojo** [comment]
Jesper Dangaard Brouer <notifications@github.com> writes:

> I'm working on this... but I noticed that the loop unroll, that does
> the VLAN header parsing is sometimes removed and optimized out by the
> compiler.  This needs some more investigations...

Ugh :/
