### ISSUE TITLE
advanced03-AF_XDP

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#60]
Is there a plan to supply the code like other tutorials ?

And I can compile it with command make in the project.

**Comment by chaudron** [comment]
This is in the works. Submitted a pull request last Friday. 

https://github.com/xdp-project/xdp-tutorial/pull/58

**Comment by chaudron** [comment]
This is in the works. Submitted a pull request last Friday. 

https://github.com/xdp-project/xdp-tutorial/pull/58

**Comment by glennWang** [comment]
> This is in the works. Submitted a pull request last Friday.
> 
> #58

@chaudron 

**You are great.
Thanks a lot.**

**Comment by glennWang** [comment]
Could you tell me what system you are using and what kernel you are using to make this tutorial？

For example，I'm using Ubuntu18.04 with kernel 4.19.67.

@chaudron

**Comment by netoptimizer** [comment]
@glennWang have you tested @chaudron code/branch ?

**Comment by glennWang** [comment]
@netoptimizer @chaudron 

Yes, but I have some problems.

**Firstly，compile is ok. My problems are the followings：**
 
**Assignment 1:**
$ t setup --name veth-adv03
Setting up new environment 'veth-adv03'
RTNETLINK answers: Permission denied.
Error during setup, removing partially-configured environment 'veth-adv03'

Edit /etc/sysctl.conf set the following  and  execute command $  /sbin/sysctl -p  will solve the promlem.
net.ipv6.conf.all.disable_ipv6 = 0

And then execute command 
$ ./af_xdp_user -d veth-adv03  
ERROR: Can't setup AF_XDP socket "Operation not supported"

I don't know how to solve this problem.


**Secondly, my environment is the following:**
Vagrantfile (dnf update -y && dnf upgrade -y):

Vagrant.configure(2) do |config|
  config.vm.box = "generic/fedora29"
  config.vm.box_check_update = false
  config.vm.define "f29" do |m|
    m.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 2
      v.customize ["modifyvm", :id, "--name", "f29"]
      v.customize ["modifyvm", :id, "--nictype1", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype2", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype3", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype4", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype5", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype6", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype7", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype8", "82543GC"]
    end
    m.vm.hostname = "f29"
    m.vm.synced_folder ".", "/vagrant", disabled: false
    m.vm.network "private_network", ip: "172.17.2.4", netmask: "255.255.255.0", :mac => "040404161203"
    m.vm.network "private_network", ip: "172.17.2.6", netmask: "255.255.255.0", :mac => "040404161206"
  end
end

$ uname -a
Linux f29 5.2.7-100.fc29.x86_64 #1 SMP Thu Aug 8 05:30:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/*release
Fedora release 29 (Twenty Nine)
NAME=Fedora
VERSION="29 (Twenty Nine)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Twenty Nine)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
Fedora release 29 (Twenty Nine)
Fedora release 29 (Twenty Nine)

**Comment by chaudron** [comment]
Did you use the latest bpf-next kernel with at least the following options enabled?

CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_XDP_SOCKETS=y

**Comment by glennWang** [comment]
Sorry, I didn't use bpf-next kernel.

Later, I'll have a try again.

Firstly, I have to learn how to use bpf-next kernel in Fedora29.

**Comment by chaudron** [comment]
Use this link:

https://fedoraproject.org/wiki/Building_a_custom_kernel#Building_Vanilla_upstream_kernel

Don't forget to enable the XDP_SOCKET configuration

**Comment by glennWang** [comment]
OK.

Thanks for your detailed reply.

I will have a try in the near future.

**Comment by glennWang** [comment]
@chaudron @netoptimizer 

Sorry, I'm later.

My Mac book hd is too small  to compile the kernel.

There is a little problem.

https://github.com/chaudron/xdp-tutorial.git   is ok and advanced03-AF_XDP worked successfully.

However, when I compile the advanced03-AF_XDP  from https://github.com/xdp-project/xdp-tutorial.git, I get the following error:

_af_xdp_user.c:19:10: fatal error: bpf/xsk.h: No such file or directory
 #include <bpf/xsk.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [../common//common.mk:105: af_xdp_user] Error 1_

**Comment by tohojo** [comment]
Hmm, maybe we need to put that header in include/ as well? @netoptimizer what do you think?

**Comment by chaudron** [comment]
> Hmm, maybe we need to put that header in include/ as well? @netoptimizer what do you think?

If you would update to the latest libbpf this should get installed

**Comment by glennWang** [comment]
Hi,  guys.

I want to make a authority DNS server based on  af_xdp.

Is there any recommanded high performance third party opensource code can be used on parsing and packetization ?

Thanks a lot !
