### ISSUE TITLE
This is in the works. Submitted a pull request last Friday.（advanced03-AF_XDP）

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#61]
This is in the works. Submitted a pull request last Friday. 

https://github.com/xdp-project/xdp-tutorial/pull/58

_Originally posted by @chaudron in https://github.com/xdp-project/xdp-tutorial/issues/60#issuecomment-522654269_

Could you tell me what system you are using and what kernel you are using to make this tutorial？

For example，I'm using Ubuntu18.04 with kernel 4.19.67.

**Comment by chaudron** [comment]
I'm using a Fedora29 machine with the latest bpf-next kernel, https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git

**Comment by glennWang** [comment]
Thanks.
