### ISSUE TITLE
advanced03-AF_XDP Assignment 1 and Assignment 3

### ISSUE THREAD

**Issue by glennWang** [xdp-project/xdp-tutorial#68]
Hello ,
I don't understand why  _./af_xdp_user -d veth-adv03_  without  _--filename af_xdp_kern.o_  also can load a xdp program and eat all pings.

After _./af_xdp_user -d veth-adv03_,  using cmd  _ip a show veth-adv03_, the result shows that it have loaded a xdp program truly.

If _./af_xdp_user -d veth-adv03_  has loaded a xdp program truly, which xxx.o  has been loaded ?

**Comment by chaudron** [comment]
Libbpf takes care of this, see the following: 

https://github.com/libbpf/libbpf/blob/476e158b07ea5f36f4475735330c1152ffe15acc/src/xsk.c#L241

It will load a default XDP program.
