### ISSUE TITLE
How to generate traffic for virtual interfaces in local?

### ISSUE THREAD

**Issue by mlouielu** [xdp-project/xdp-tutorial#71]
Hi there

I want to test the XDP program, but the script only provides `t ping`, which is ICMP, and small size packet, I can modify the ping parameter, but still this is only ICMP.

How can I generate traffic for virtual interfaces to test other types of traffic? (e.g. by iperf3?)

Thanks

**Comment by tohojo** [comment]
Louie Lu <notifications@github.com> writes:

> Hi there
>
> I want to test the XDP program, but the script only provides `t ping`,
> which is ICMP, and small size packet, I can modify the ping parameter,
> but still this is only ICMP.
>
> How can I generate traffic for virtual interfaces to test other types
> of traffic? (e.g. by iperf3?)

`t exec` allows you to execute arbitrary commands inside the
environment. Or use `t enter` to spawn a new shell running inside it
