### ISSUE TITLE
advanced03-AF_XDP does not compile missing header file xsk.h

### ISSUE THREAD

**Issue by netoptimizer** [xdp-project/xdp-tutorial#72]
The [advanced03-AF_XDP](https://github.com/xdp-project/xdp-tutorial/tree/master/advanced03-AF_XDP) example/assignment does not compile on my system.  It is missing a header include file named: ```bpf/xsk.h```.

Output is:
```
advanced03-AF_XDP]$ make
cc -Wall -I../libbpf/src//root/usr/include/ -g -I/usr/include/x86_64-linux-gnu -I../headers/ -L../libbpf/src/ -o af_xdp_user ../common//common_params.o ../common//common_user_bpf_xdp.o \
 af_xdp_user.c -l:libbpf.a -lelf  -lpthread
af_xdp_user.c:19:10: fatal error: bpf/xsk.h: No such file or directory
 #include <bpf/xsk.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [../common//common.mk:105: af_xdp_user] Error 1
```

The header file ```xsk.h``` is provided by [libbpf](https://github.com/libbpf/libbpf/blob/master/src/xsk.h), but not under subdir ```bpf/```. In my git tree the file is located in: libbpf/src/xsk.h and XDP-tutorial does have this (```../libbpf/src/```) as *object* search/link dir in above compile command.

I guess libbpf should have "installed" this header file in: ```../libbpf/src//root/usr/include/``` but it only contains:

```
$ ls -1 libbpf/src//root/usr/include/bpf/
bpf.h
btf.h
libbpf.h
```

**Comment by netoptimizer** [comment]
I do have the latest [libbpf](https://github.com/libbpf/libbpf/) version:
```
$ git submodule status 
 476e158b07ea5f36f4475735330c1152ffe15acc libbpf (v0.0.4-46-g476e158b07ea)
```
This is (currently) the latest [commit](https://github.com/libbpf/libbpf/commit/476e158b07ea5f36f4475735330c1152ffe15acc) for libbpf.

**Comment by netoptimizer** [comment]
Hmm... this was weird, after above mentioned commit dbd66f148e and compiling all assignments successfully, somehow libbpf were also "re-installed", and now my local ```libbpf/src//root/usr/include/bpf/``` dir contains:

```
$ ls -1 libbpf/src//root/usr/include/bpf/
bpf.h
btf.h
libbpf.h
libbpf_util.h
xsk.h
```

And now, the advanced03-AF_XDP example compiles.

**Comment by chaudron** [comment]
Is this still a problem based on #73 comment? I tried it using the vagrant method from this pull request and do not get the errors https://github.com/xdp-project/xdp-tutorial/pull/70

**Comment by chaudron** [comment]
Any update on the above @netoptimizer? As it works fine in my setup

**Comment by netoptimizer** [comment]
Notice that in commit 064365f77c85e7 I renamed libbpf install path from ```root``` to ```build```

```
From: libbpf/src/root/usr/include/bpf/
To:   libbpf/src/build/usr/include/bpf/
```

**Comment by netoptimizer** [comment]
I'm going to close this, because this was a case of stalled files from other libbpf submodule checkouts.

In commit 064365f77c85e7 have tried to fix this by having ```make clean``` also removing the build version of libbpf.  If people hit this again, we first as them to run ```make clean``` and try again.

I didn't find a way to create a Makefile dependency that can detect that libbpf submodule was changed, and force a rebuild of the libbpf build dir.

**Comment by tohojo** [comment]
Jesper Dangaard Brouer <notifications@github.com> writes:

> I didn't find a way to create a Makefile dependency that can detect
> that libbpf submodule was changed, and force a rebuild of the libbpf
> build dir.

I was thinking about trying out git-subtrac:
https://github.com/apenwarr/git-subtrac

This should make it easier to track the submodule dependency correctly;
not sure if it'll solve this particular problem, but it may be worth
testing it?

**Comment by netoptimizer** [comment]
No, please don't.

This is a tutorial that needs to be easy to get started with, I don't want people/users to depend on installing a git subcommand like ```subtrac``` before getting started...

**Comment by tohojo** [comment]
Jesper Dangaard Brouer <notifications@github.com> writes:

> No, please don't.
>
> This is a tutorial that needs to be easy to get started with, I don't
> want people/users to depend on installing a git subcommand like
> ```subtrac``` before getting started...

If I understand it correctly, the subtrac binary is only needed for
updating the submodule; cloning should just work (and would not need the
--recurse-submodules); that is part of the appeal :)
