### ISSUE TITLE
advanced03-AF_XDP - Can't setup AF_XDP socket "Operation not supported"

### ISSUE THREAD

**Issue by mcnevesinf** [xdp-project/xdp-tutorial#75]
Hi
I'm trying to run Assignment 1 on a VirtualBox VM equipped with Ubuntu 18.04. I upgraded the kernel to version 5.2.13 to make sure it supports AF_XDP operations, at least when the built-in XDP program is being used.

I can compile all programs in the tutorial and set up the test lab environment normally. However, when I try to run the example program for assignment 1 I get this error:

Can't setup AF_XDP socket "Operation not supported" 

The error persists even if I try to force "skb-mode" to avoid potential issues with the nic driver. It seems the error originates in the following command, which is part of the "xsk_socket__create" function from libbpf.

err = getsockopt(xsk->fd, SOL_XDP, XDP_OPTIONS, &opts, &optlen);

Any idea on how to solve it?

**Comment by tohojo** [comment]
mcnevesinf <notifications@github.com> writes:

> Hi
> I'm trying to run Assignment 1 on a VirtualBox VM equipped with Ubuntu 18.04. I upgraded the kernel to version 5.2.13 to make sure it supports AF_XDP operations, at least when the built-in XDP program is being used.
>
> I can compile all programs in the tutorial and set up the test lab environment normally. However, when I try to run the example program for assignment 1 I get this error:
>
> Can't setup AF_XDP socket "Operation not supported" 
>
> The error persists even if I try to force "skb-mode" to avoid potential issues with the nic driver. It seems the error originates in the following command, which is part of the "xsk_socket__create" function from libbpf.
>
> err = getsockopt(xsk->fd, SOL_XDP, XDP_OPTIONS, &opts, &optlen);
>
> Any idea on how to solve it?

Did you compile the kernel yourself? If so, did you enable CONFIG_XDP_SOCKETS?

**Comment by mcnevesinf** [comment]
Thanks for the quick reply. I did NOT compile the kernel myself. I took the version available in https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.2.13/ (build for amd64).

CONFIG_XDP_SOCKETS is enabled as well as CONFIG_BPF and their related flags.

**Comment by tohojo** [comment]
mcnevesinf <notifications@github.com> writes:

> Thanks for the quick reply. I did NOT compile the kernel myself. I took the version available in https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.2.13/ (build for amd64).
>
> CONFIG_XDP_SOCKETS is enabled as well as CONFIG_BPF and their related
> flags.

Ah. Support for XDP_OPTIONS was not added until kernel 5.3...

**Comment by mcnevesinf** [comment]
Great. I installed kernel 5.3-rc7 and now I'm able to run the program. However, I got stuck in a different issue, namely ping packets are being eaten but there is no packet to process.

It seems function `xsk_ring_cons__peek` in `handle_receive_packets` is always returning zero. I tried to follow its execution path and it looks like function `xsk_cons_nb_avail` also returns always zero (`cached_prod` and `cached_cons` are both zero). I'm again running in skb-mode so I think the VM NIC should not be the problem.

**Comment by tohojo** [comment]
mcnevesinf <notifications@github.com> writes:

> Great. I installed kernel 5.3-rc7 and now I'm able to run the program.

Awesome! I also submitted a patch to libbpf to fix this issue for older
kernels: https://patchwork.ozlabs.org/patch/1159891/

> However, I got stuck in a different issue, namely ping packets are
> being eaten but there is no packet to process.
>
> It seems function `xsk_ring_cons__peek` in `handle_receive_packets` is
> always returning zero. I tried to follow its execution path and it
> looks like function `xsk_cons_nb_avail` also returns always zero
> (`cached_prod` and `cached_cons` are both zero). I'm again running in
> skb-mode so I think the VM NIC should not be the problem.

Hmm, no idea about that part; @netoptimizer or @chaudron ? :)

**Comment by chaudron** [comment]
This is odd but I've always been running with the latest bpf-next. Do you see any packets after let's say 32 packets have been sent?

In addition, are you testing this with the veth interfaces as in the example, or with the VM interface as you mention? If the later can you try with the veth as explained in the readme?

Also for assignment 2 do you at least see every other packet being forwarded?

**Comment by mcnevesinf** [comment]
> This is odd but I've always been running with the latest bpf-next. Do you see any packets after let's say 32 packets have been sent?
No. There is no packet at all and it seems to be independent of the number of packets sent.
> In addition, are you testing this with the veth interfaces as in the example, or with the VM interface as you mention? If the later can you try with the veth as explained in the readme?
I tested with both. Same behavior. I also tested with a physical NIC (considering both single queue and multi-queue scenarios) and the problem persists. 
> Also for assignment 2 do you at least see every other packet being forwarded?
Yep. It seems XDP_PASS in kernel space program works fine.

**Comment by chaudron** [comment]
Could this be related to #76, can you try to use the libbpf of your distribution?

**Comment by mcnevesinf** [comment]
> Could this be related to #76, can you try to use the libbpf of your distribution?

I tried with the distro libbpf and it solves the problem thus I'm closing this issue. Thanks for the support.
