### ISSUE TITLE
Where to download the lab setup F29-xdp-tutorial.qcow2 image?

### ISSUE THREAD

**Issue by vincentmli** [xdp-project/xdp-tutorial#77]
Hi,

I want to use the test lab VM image, where I can get it?

Thanks!

**Comment by tohojo** [comment]
Vincent Li <notifications@github.com> writes:

> Hi,
>
> I want to use the test lab VM image, where I can get it?

It's under "releases" in the github interface...

**Comment by chaudron** [comment]
If you want to build it yourself with the latest bpf-next kernel take a look at the https://github.com/chaudron/xdp-tutorial version. It has a vagrant configuration /vagrant.
