### ISSUE TITLE
basic04-pinning-maps：libbpf: BTF is required, but is missing or corrupted.

### ISSUE THREAD

**Issue by sofardware** [xdp-project/xdp-tutorial#85]
When I try basic04-pinning-maps with the follow command after Make， there is erros as follow：
[root@localhost basic04-pinning-maps]# sudo ./xdp_loader --dev veth-basic03 --force --progsec xdp_pass
libbpf: BTF is required, but is missing or corrupted.
ERR: loading BPF-OBJ file(xdp_prog_kern.o) (-2): No such file or directory
ERR: loading file: xdp_prog_kern.o

[root@localhost basic04-pinning-maps]# sudo ./xdp_loader --dev lo --force --progsec xdp_pass
libbpf: BTF is required, but is missing or corrupted.
ERR: loading BPF-OBJ file(xdp_prog_kern.o) (-2): No such file or directory
ERR: loading file: xdp_prog_kern.o
----------------------------------------------
[root@localhost basic04-pinning-maps]# ls /sys/fs/
bpf/     cgroup/  pstore/  selinux/ xfs/     
[root@localhost basic04-pinning-maps]# ls /sys/fs/bpf/

**Comment by tohojo** [comment]
sofardware <notifications@github.com> writes:

> When I try basic04-pinning-maps with the follow command after Make， there is erros as follow：
> [root@localhost basic04-pinning-maps]# sudo ./xdp_loader --dev veth-basic03 --force --progsec xdp_pass
> libbpf: BTF is required, but is missing or corrupted.
> ERR: loading BPF-OBJ file(xdp_prog_kern.o) (-2): No such file or directory
> ERR: loading file: xdp_prog_kern.o

Ah, seems I accidentally committed the conversion of the map definition
in that example to use the new BTF map definition syntax, which requires
LLVM9. Since we haven't decided to require that for the tutorial yet,
I'll just revert that change.

**Comment by vcunat** [comment]
...and now there's the reverse problem.  Old-style maps are no longer supported by libbpf (>= 1.0).

**Comment by tohojo** [comment]
Vladimír Čunát ***@***.***> writes:

> ...and now there's the reverse problem.  Old-style maps are no longer
> supported by libbpf (>= 1.0).

Yes, some work is needed to update the tutorial for "modern" libbpf
usage. Help is welcome!

**Comment by vcunat** [comment]
We still haven't even managed to migrate the production code to work with libbpf 1.0, so I was rather hoping to find inspiration...

**Comment by tohojo** [comment]
Vladimír Čunát ***@***.***> writes:

> We still haven't even managed to migrate the production code to work
> with libbpf 1.0, so I was rather hoping to find inspiration...

Have a look at the bpf-examples repository - that has more up-to-date
code examples: https://github.com/xdp-project/bpf-examples

**Comment by vcunat** [comment]
Thanks, though I was looking into both repos in parallel already (and many other places).
