### ISSUE TITLE
unknown func bpf_csum_diff#28

### ISSUE THREAD

**Issue by linengier** [xdp-project/xdp-tutorial#88]
when I use packet-solutions program to load xdp prog by cmd 'xdp_loader --filename xdp_prog_kern_03.o --progsec xdp_icmp_echo --dev wlp8s0b1 ', it show me "unknown func bpf_csum_diff#28".
My linux is ubuntu18.04 kernel version is 4.15.0.

**Comment by tohojo** [comment]
linengier <notifications@github.com> writes:

> when I use packet-solutions program to load xdp prog by cmd 'xdp_loader --filename xdp_prog_kern_03.o --progsec xdp_icmp_echo --dev wlp8s0b1 ', it show me "unknown func bpf_csum_diff#28".
> My linux is ubuntu18.04 kernel version is 4.15.0.

bpf_csum_diff() should be there even in 4.15; but there are other
missing features from that release, so I'd recommend you upgrade your
kernel to at least v4.18 or 4.19; and newer the better :)

**Comment by linengier** [comment]
> linengier <notifications@github.com> writes:
> when I use packet-solutions program to load xdp prog by cmd 'xdp_loader --filename xdp_prog_kern_03.o --progsec xdp_icmp_echo --dev wlp8s0b1 ', it show me "unknown func bpf_csum_diff#28". My linux is ubuntu18.04 kernel version is 4.15.0.
> bpf_csum_diff() should be there even in 4.15; but there are other missing features from that release, so I'd recommend you upgrade your kernel to at least v4.18 or 4.19; and newer the better :)

thanks,tohojo.when I upgrade kernel to 4.19, it works.
