### ISSUE TITLE
 compliing the project faild in arm 64

### ISSUE THREAD

**Issue by magnate3** [xdp-project/xdp-tutorial#93]
I   complile the project but fails in arm 64. because of libz.so.
so,I solve the problem by the following steps :
################ make & install zlib-1.2.8 ####################

./configure

make && make install
headers will be installed in   /usr/local/include/ and  libz.so.1.2.8  will be installed in /usr/local/lib/
ls /usr/local/include/

ls /usr/local/lib/

################edit common/common.mk ####################

LDFLAGS ?= -L$(LIBBPF_DIR) -L/usr/local/lib

LIBS = -l:libbpf.a -lelf $(USER_LIBS) -lz -l:libz.so.1.2.8

the solution is here:https://github.com/magnate3/xdp

**Comment by tohojo** [comment]
magnate3 <notifications@github.com> writes:

> I   complile the project but fails in arm 64. because of libz.so.
> so,I solve the problem by the following steps :
> ################  download zlib-1.2.8.tar.gz################
> ################ make & install zlib-1.2.8 ####################
>
> ./configure
>
> make && make install
> headers will be installed in   /usr/local/include/ and  libz.so.1.2.8  will be installed in /usr/local/lib/
> ls /usr/local/include/
>
> ls /usr/local/lib/
>
> ################edit common/common.mk ####################
>
> LDFLAGS ?= -L$(LIBBPF_DIR) -L/usr/local/lib
>
> LIBS = -l:libbpf.a -lelf $(USER_LIBS) -lz -l:libz.so.1.2.8

Doesn't your distro provide a libz-devel (or libz-dev) package?

**Comment by magnate3** [comment]
I have installed  libz-devel in my os ,but in the process of compling report  
undefined reference to 'gzopen()';
undefined reference to 'gzwrite()';
undefined reference to 'gzclose()';

so,I   make & install zlib-1.2.8 and finally solve the problem.

**Comment by magnate3** [comment]
I have installed libz-devel in my os ,but in the process of compling report
undefined reference to 'gzopen()';
undefined reference to 'gzwrite()';
undefined reference to 'gzclose()';

so,I make & install zlib-1.2.8 and finally solve the problem.

**Comment by tohojo** [comment]
magnate3 <notifications@github.com> writes:

> I have installed libz-devel in my os ,but in the process of compling report
> undefined reference to 'gzopen()';
> undefined reference to 'gzwrite()';
> undefined reference to 'gzclose()';
>
> so,I make & install zlib-1.2.8 and finally solve the problem.

With the libz-devel package it should be enough to just add the -lz
linker flag.

Did you manually update the libbpf version, BTW? The version referenced
in the git submodule does not depend on zlib...

**Comment by tohojo** [comment]
magnate3 <notifications@github.com> writes:

> I  the following steps  
> 1、 git submodule add https://github.com/libbpf/libbpf/ libbpf

Yeah, no reason to do that.

If you clone the repo with --recurse-submodules, or just do

git submodule init
git submodule update

after a clone (without doing any 'submodule add'), you'll get the
specific revision of libbpf we've tested against, and not have any
problems with new versions.

We'll update the build system to include zlib when we do pull forward
the libbpf version.

**Comment by magnate3** [comment]
thank you very much ,your way can also solve my proble. cloud you tell me where I can share my notes about the kernel achivements of xdp

**Comment by tohojo** [comment]
magnate3 <notifications@github.com> writes:

> thank you very much ,your way can also solve my proble. cloud you tell
> me where I can share my notes about the kernel achivements of xdp

Hmm, good question. There's not really a repository for these kinds of
things; so I think your best bet may be to just publish it somewhere
else and share the link, for example on the xdp-newbies list...

**Comment by dmitris** [comment]
here's the issue I hit: `git clone --recurse-submodules  https://github.com/xdp-project/xdp-tutorial` as @magnate3  wrote above works fine, but `git clone --recurse-submodules --remote-submodules https://github.com/xdp-project/xdp-tutorial` gets a wrong version of libbpf and correspondingly the ZLIB compile failure.
